src/endpoints/accounts/account.controller.ts, src/endpoints/tokens/token.service.ts
=> 404 error instead of 500 for account-specific nft/token endpoint

src/common/caching.service.ts, src/endpoints/tokens/token.service.ts
also, better error handling when metadata cannot be fetched from IPFS
=> extract thumbnail info only for media-related nfts

src/crons/cache.warmer.service.ts, src/endpoints/network/network.service.ts
take raw economics and account information when refreshing with cache warmer
=> Cache warmer use raw info

src/endpoints/network/network.service.ts
temporary economics update until observers report correct total supply on epoch change
=> temporary economics update

src/endpoints/nodes/node.service.ts
Fix of current 500 error on nodes endpoint.
https://explorer.elrond.com/nodes?issues=true&type=validator
=> Fix Nodes Filter Issues

src/endpoints/tokens/token.asset.service.ts
- if a token asset is improperly formatted, the refresh of all assets is halted
- try/catch when parsing individual token asset
=> Individual asset refresh error handling

src/common/caching/entities/cache.info.ts, src/crons/cache.warmer.service.ts, src/endpoints/tokens/entities/token.ts, src/endpoints/tokens/token.module.ts, src/endpoints/tokens/token.service.ts
- Informations about esdt token transactions and holders are hard to find
- Display esdt token transactions and holders in list and details
- Run a cron job that will keep informations in sync
=> Esdt tokens transactions and holders informations

src/endpoints/tokens/token.transfer.service.ts, src/endpoints/transactions/transaction.service.ts
- /transactions endpoint is too heavy when trying to process request withOperations and withScResults flags
- Process transactions in batches
- Minimize calls to ES
=> improvements for transactions list

src/endpoints/collections/collection.service.ts
- Collections don't have any assets (logo, website)
- Collections properties are processed one by one
- Show collection assets on list
- Batch process assets and collections properties
=> batch process collection properties and show assets

src/endpoints/accounts/account.controller.ts, src/endpoints/tokens/token.controller.ts, src/endpoints/transactions/entities/transactions.query.options.ts, src/endpoints/transactions/transaction.controller.ts, src/endpoints/transactions/transaction.service.ts
-  Transaction logs not displayed on list.
- Filter logs for transaction and scResults
- Show logs for transaction and scResults
=> show transaction logs on list

src/endpoints/tokens/token.asset.service.ts
- checkout repo command does not wait for the checkout to finish
- use Promise object to resolve the response
- duration of checkout should be a few seconds instead of almost instantaneously
=> use promise when checkout repo

src/endpoints/tokens/entities/token.detailed.ts, src/endpoints/tokens/token.service.ts
- supply as string (temporary fix)
=> supply as string

config/configuration.ts, src/main.ts
- initialize datadog before creating nest app to handle public api calls as well
=> Datadog initializer

config/dapp.config.devnet.json, config/dapp.config.mainnet.json, config/dapp.config.testnet.json, src/endpoints/dapp-config/dapp.config.controller.ts, src/endpoints/dapp-config/dapp.config.module.ts, src/endpoints/dapp-config/dapp.config.service.ts, src/endpoints/dapp-config/entities/dapp.network.ts, src/endpoints/endpoints.controllers.module.ts, src/endpoints/endpoints.services.module.ts
- Hard to find a configuration for elrond dapps.
- Create a endpoint that shows the necessary configuration for dapps on elrond depending on network.
=> Dapp config

docker-compose.yml
- Missing dependencies in docker-compose
- Add rabbitmq in docker-compose
=> add rabbitmq in docker-compose

src/endpoints/tokens/token.transfer.service.ts, src/endpoints/transactions/entities/transaction.log.event.identifier.ts, src/endpoints/transactions/entities/transaction.operation.action.ts, src/endpoints/transactions/entities/transaction.operation.ts, src/endpoints/transactions/transaction.get.service.ts, src/endpoints/transactions/transaction.service.ts, src/utils/transaction.utils.ts
- Freeze transactions does not return any operations
- Build a operation from freeze transaction smart contract results
=> support for freeze operation

src/endpoints/accounts/account.controller.ts, src/endpoints/accounts/account.service.ts, src/endpoints/accounts/entities/account.esdt.history.ts, src/endpoints/accounts/entities/account.history.ts, src/test/integration/accounts.e2e-spec.ts
=> Account history

src/endpoints/nodes/node.service.ts
- filter out the nodes who do not have sorting criteria as attribute
=> Add query filter on sort only if node has property (#449)

src/endpoints/transactions/entities/transaction.ts, src/endpoints/transfers/transfer.service.ts
- marked fields that can be `undefined`
- included `originalTxHash` as field in transaction
=> marked fields that can be undefined, included originalTxHash

src/endpoints/transactions/transaction-action/recognizers/esdt/transaction.action.esdt.nft.recognizer.service.ts
- support for recognizing freeze action
=> recognize freeze action

src/crons/cache.warmer/cache.warmer.service.ts
- Refresh assets every 10 minutes
=> refresh assets every 10 minutes

src/endpoints/transactions/transaction-action/recognizers/mex/mex.settings.service.ts
=> fetch legacy value from plugin

src/common/metrics/metrics.service.ts, src/utils/locker.ts
=> metric for cron jobs

src/endpoints/network/network.service.ts
- Do not divide roundDuration by 1000, since it's already done in a higher layer
=> APR year fix

src/endpoints/providers/entities/provider.filter.ts, src/endpoints/providers/provider.controller.ts
- Pagination does not have any effect for /providers endpoint
- 
- 
- Remove pagination parameters from providers endpoint
=> remove pagination from providers endpoint

src/test/integration/nodes.e2e-spec.ts, src/test/integration/providers.e2e-spec.ts, src/test/integration/rounds.e2e-spec.ts, src/test/integration/tokens.e2e-spec.ts
=> refactoring integration test and added new test scenarios

src/endpoints/transactions/transaction.get.service.ts
- corrected query for transaction receipts
=> fixed transaction receipt query

src/endpoints/nodes/node.service.ts
- support for node versions that contain "rc"
=> Node version fix

config/dapp.config.mainnet.json
- updated egld label in dapp config
=> adjusted egld label

src/endpoints/transfers/transfer.service.ts
- when fetching transfers, include sender as well
=> when fetching transfers, include sender as well

src/endpoints/transfers/transfer.service.ts
- improved heuristic for transfers filtering
=> improved heuristic for transfers filtering

src/endpoints/nfts/nft.service.ts, src/utils/token.utils.ts
- fixed logic with which to select default media
- `/nfts/NFTP-ba3ed7-08` should have default media set
=> NFT media fix

LICENSE
=> added GPL license

src/endpoints/tokens/token.transfer.service.ts, src/endpoints/transactions/entities/transaction.operation.action.ts, src/utils/transaction.utils.ts
- treat MultiESDTNFTTransfer operation action as normal transfer
- `/transactions/52208fc67fa5782af570cf9d1d10f4b36e9b4f9472e1f140c56c9b92c485f997` should have 2 operations instead of 4
=> Trim Operations MultiTransfer

src/common/elastic/elastic.service.ts
- implement correct pagination when fetching nft owners
- `/nfts?from=1&size=1&withOwner=true&type=NonFungibleESDT` should return owner
=> Fix nft owners issue

src/test/integration/nft.e2e-spec.ts, src/test/integration/transactions.e2e-spec.ts
-  Fix nft owners issue #531 
-  Transaction operations improvements #527
=> integration tests update

src/endpoints/transactions/transaction-action/recognizers/mex/mex.pair.action.recognizer.service.ts, src/endpoints/transactions/transaction-action/recognizers/mex/mex.settings.service.ts, src/endpoints/transactions/transaction-action/recognizers/mex/mex.wrap.action.recognizer.service.ts
- wrapEgld to have transfers
- swap to have 2nd token info
- swapTokensFixedOutput special case handling
- `wrapEgld`: `18406ec91c6948c84f13cd99ba9aba28c9aabedd8ad69a9dbdc638e6bbc4ce02`
- `swap`: `f6f64688962947571b87fac1a026ecd2dff547be0a1a7ea64e45ee36da4b723f`
- `swapTokensFixedOutput`: `817eacb79893ef27dd08ac837f2404b39694b2b92c09507ae01108773fc50d72`
=> Transaction action fixes

src/common/caching/caching.service.ts, src/crons/transaction.processor/transaction.processor.service.ts
=> remove unused invalidations

src/endpoints/proxy/proxy.controller.ts, src/endpoints/transactions/transaction.get.service.ts, src/interceptors/access.interceptor.ts, src/utils/guards/jwt.authenticate.guard.ts
- handle various expected errors so that no unnecessary logging is created
=> Fix proxy unhandled errors

src/common/metrics/metrics.service.ts, src/interceptors/logging.interceptor.ts
- Log request origin
- api request metrics should also contain origin info
=> log request origin

config/dapp.config.devnet.json, config/dapp.config.mainnet.json, config/dapp.config.testnet.json
- No chainId present in dapp configuration endpoint
- Show chainId
=> show chain id in dapp configuration

src/test/integration/tokens.e2e-spec.ts
=> Mocking Integration tests

src/endpoints/blocks/block.service.ts, src/endpoints/blocks/entities/block.ts
=> Fix maxGasLimit

src/common/caching/entities/cache.info.ts, src/endpoints/accounts/account.service.ts, src/endpoints/accounts/entities/account.key.ts, src/endpoints/stake/stake.service.ts
- Get top up amount for an account key
=> get top up for an account key

src/endpoints/sc-results/entities/smart.contract.result.filter.ts, src/endpoints/sc-results/scresult.controller.ts, src/endpoints/sc-results/scresult.service.ts
- Filter SC Results by `originalTxHash`
=> filter sc-results by originalTxHash

src/endpoints/nodes/node.service.ts, src/endpoints/stake/entities/stake.ts, src/endpoints/stake/stake.service.ts
- No details about which address stake information can't be found
- Log address when an error occurs
=> node stake details for jailed nodes

config/config.devnet.yaml, config/config.mainnet.yaml, config/config.testnet.yaml, package-lock.json, package.json, src/common/api-config/api.config.service.ts, src/common/metrics/metrics.service.ts, src/common/persistence/mongodb/entities/nft.media.db.ts, src/common/persistence/mongodb/entities/nft.metadata.db.ts, src/common/persistence/mongodb/mongo.db.module.ts, src/common/persistence/mongodb/mongo.db.service.ts, src/common/persistence/persistence.module.ts, src/common/persistence/persistence.service.ts, src/endpoints/nfts/nft.service.ts, src/queue.worker/nft.worker/queue/job-services/media/nft.media.module.ts, src/queue.worker/nft.worker/queue/job-services/media/nft.media.service.ts, src/queue.worker/nft.worker/queue/job-services/metadata/nft.metadata.service.ts
- Support for MongoDB instead of Mysql
=> Mongodb support

src/test/integration/nodes.e2e-spec.ts, src/test/integration/shards.e2e-spec.ts
=> Shards Service E2E

src/test/integration/accounts.e2e-spec.ts
-  Update integration test using mocks
=> accounts service e2e

src/common/caching/entities/cache.info.ts, src/endpoints/proxy/proxy.controller.ts
- updated some ttls so that we limit the maximum amount of keys in redis
=> Improved redis ttls

src/test/integration/mini.block.e2e-spec.ts
=> mini block service e2e

.github/PULL_REQUEST_TEMPLATE.md, src/test/integration/tokens.e2e-spec.ts, src/test/integration/waiting.list.e2e-spec.ts
=> waiting-list service e2e

src/endpoints/nfts/nft.controller.ts
- fixed `/c` endpoint type validation
- `/nfts/c?search=fl&type=SemiFungibleESDT,NonFungibleESDT&includeFlagged=true` should not fail
=> NFT /c endpoint fix

src/common/caching/entities/cache.info.ts, src/endpoints/accounts/account.controller.ts, src/endpoints/esdt/esdt.module.ts, src/endpoints/esdt/esdt.service.ts, src/endpoints/mex/entities/mex.pair.state.ts, src/endpoints/mex/entities/mex.pair.ts, src/endpoints/mex/entities/mex.token.ts, src/endpoints/mex/mex.pairs.service.ts, src/endpoints/mex/mex.token.service.ts, src/endpoints/tokens/entities/token.detailed.with.balance.ts, src/endpoints/tokens/entities/token.sort.ts, src/endpoints/tokens/entities/token.ts, src/endpoints/tokens/entities/token.with.balance.ts, src/endpoints/tokens/token.service.ts, src/endpoints/transactions/transaction-action/recognizers/esdt/transaction.action.esdt.nft.recognizer.service.ts, src/endpoints/transactions/transaction-action/recognizers/mex/mex.pair.action.recognizer.service.ts, src/endpoints/transactions/transaction-action/transaction.action.service.ts, src/endpoints/transactions/transaction.get.service.ts, src/endpoints/transactions/transaction.service.ts
- return price & market cap for DEX listed tokens
- return token value for DEX listed tokens inside accounts
- `/tokens`: price & marketCap for MEX, WEGLD, USDC, etc
- `/accounts/erd1sg7p5jpfyhyj76dk8uezwnaxers78h348ffe7puredepck25df8slfq0ju/tokens` should also return `valueUsd` attribute
=> Token price & Market Cap

src/crons/transaction.processor/transaction.processor.service.ts, src/endpoints/transactions/transaction-action/recognizers/sc-calls/transaction.action.sc-calls.recognizer.service.ts
- small code improvements & fixes
=> Code improvements

src/common/api-config/api.config.service.ts, src/common/github/entities/github.user.info.ts, src/common/github/github.module.ts, src/common/github/github.service.ts, src/common/keybase/keybase.module.ts, src/common/keybase/keybase.service.ts, src/common/network/api.service.ts, src/common/network/entities/api.settings.ts, src/common/persistence/mongodb/mongo.db.service.ts, src/endpoints/proxy/proxy.controller.ts, src/endpoints/tokens/token.service.ts, src/endpoints/transactions/transaction-action/transaction.action.service.ts, src/endpoints/transactions/transaction.service.ts
- do not log unnecessary errors
- `/accounts/erd1hqsljk0mecw8jjuc4rk8vm5q9sms3m27rac4ttk46r05ygm6ufmqxdvwpl/transfers?size=100` should not log error `Unhandled error when interpreting MultiESDTNFTTransfer / ESDTNFTTransfer for a smart contract result` and transfer with hash `5b92146cdbd595609b8ea86d0aae854e4651246693e117510f79f84acd1ec978` should contain action
- `/accounts/erd1myyrp9cse68eqqe3pk4yc6y7pzdz5xg49sp8ktsysdnv6q0580fqxda67n/transfers?size=100` should not log error `Unhandled error when interpreting MultiESDTNFTTransfer / ESDTNFTTransfer for a smart contract result` and transfer with hash `6bb6e3467bd645b44822d34e602f0a2bda8b3a6c639837b4c652d2c374dc3d38` should contain action
=> Fix logging errors

src/endpoints/mex/mex.settings.service.ts
- Fix mex contracts error
- `/transactions` should also return action
=> Mex contracts fix

config/config.e2e-mocked.mainnet.yaml, config/config.e2e.mainnet.yaml, src/test/integration/nft.e2e-spec.ts
- Price and valueUsd properties is missing from integration tests
-  add missing properties in mockNftAccount object
- run nft.e2e-spec.ts integration test
=> nft integration test fix

package-lock.json, package.json, src/decorators/native.auth.ts, src/utils/guards/native.auth.guard.ts
- Endpoints marked with `NativeAuthGuard` should be able to validate tokens generated with the help of `@elrondnetwork/native-auth` client-side package
=> Integrate native authentication

src/interceptors/logging.interceptor.ts
- Use the `clientIp` attribute injected by the request-ip npm library
-
=> Request ip

src/common/elastic/entities/elastic.query.ts, src/endpoints/nfttags/tag.controller.ts, src/endpoints/nfttags/tag.service.ts
- Offer support for partial searches of tags
- `/tags?search=test` should return 0 tags (`tag` field not yet available in ES but will be in the future)
=> Searchable tags

.github/PULL_REQUEST_TEMPLATE.md, src/endpoints/nfttags/tag.controller.ts, src/endpoints/nfttags/tag.service.ts
- Tag count endpoint
- `/tags/count` should return a number
=> tags count endpoint

src/interceptors/query.check.interceptor.ts
- Remove logging statement when a parameter is unsupported
=> Unsupported parameter do not log

src/test/integration/accounts.e2e-spec.ts, src/test/integration/api.config.e2e-spec.ts, src/test/integration/controllers/accounts.controller.e2e-spec.ts, src/test/integration/controllers/health.check.controller.e2e-spec.ts, src/test/integration/controllers/waiting-list.controller.e2e-spec.ts, src/test/integration/identities.e2e-spec.ts, src/test/integration/nft.e2e-spec.ts, src/test/integration/nft.tag.e2e-spec.ts, src/test/integration/nft.worker.e2e-spec.ts, src/test/integration/tokens.e2e-spec.ts
- Add new integration tests
- run script : npm run test:e2e and all tests must pass
=> Update integration tests

src/common/elastic/elastic.service.ts, src/endpoints/nfttags/tag.controller.ts, src/endpoints/nfttags/tag.service.ts
- Fix tag display
- `/tags` should have human readable names
=> fixed tag display

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml
=> issues template indentation

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml
- Some improvements regarding bug/issue template
=> Issue template improvements

src/endpoints/tokens/token.transfer.service.ts, src/endpoints/transactions/entities/transaction.log.event.identifier.ts, src/endpoints/transactions/entities/transaction.operation.action.ts
- interpret transferValueOnly logs as value transfer operation
=> basic support for transferValueOnly

package-lock.json, package.json, src/crons/elastic.updater/elastic.updater.service.ts
- Update transaction processor library version
- whenever a block arrives with type `ReceiptBlock` (and contains no `transactions` attribiute), the tp should not return any  error
=> Transaction processor improved error logging

src/crons/cache.warmer/cache.warmer.service.ts
- do not run node auction invalidations in cache warmer
=> Disable default node auction invalidations

src/endpoints/mex/entities/mex.pair.type.ts, src/endpoints/mex/mex.pair.service.ts
- add support for other known and unknown pairs
- `/mex/pairs` should return an array with values
=> mex pairs fix

src/common/rabbitmq/rabbitmq.consumers.ts, src/common/rabbitmq/rabbitmq.nft.consumer.ts
- Add support for dlq in events notifier
=> Events notifier dlq

package-lock.json, package.json, src/common/api-config/api.config.service.ts, src/crons/cache.warmer/cache.warmer.service.ts, src/endpoints/network/entities/about.ts, src/endpoints/network/network.controller.ts, src/endpoints/network/network.service.ts, src/test/integration/api.config.e2e-spec.ts, src/test/integration/network.e2e-spec.ts, src/utils/cache.info.ts
- Provide an endpoint with general information about the API
- `/about` should return `appVersion`, `pluginsVersion` (if plugins are source controlled), `network` & `cluster` (if provided in config)
=> About endpoint

src/endpoints/collections/collection.service.ts
- Fixed collections endpoint returning fungible tokens
- `/collections/WEB-5d08be` should return 404 instead of token details
=> Collections endpoint fungible token fix

package-lock.json, package.json
- updated erdnest to latest version
=> Erdnest update

src/endpoints/nfts/nft.service.ts
- use nft_nsfw_mark field instead of nft_nfsw
=> NFT NSFW mark field

.github/release.yml
- Template for automatically creating release notes based on categories
=> Release notes template

.github/release.yml
- include ignorable for release support in release.yml
=> Release notes ignore for release

src/endpoints/caching/local.cache.controller.ts, src/endpoints/caching/remote.cache.controller.ts, src/private.app.module.ts, src/public.app.module.ts
- Difficult to debug / find out about local caching issues
- Add local cache interactions as API endpoints, protected with jwt
- GET `/debug/cache/local/<cacheKey>` should return value for local cache key
=> Local cache endpoints

package-lock.json, package.json, src/endpoints/esdt/esdt.service.ts, src/endpoints/mex/mex.token.service.ts, src/endpoints/network/entities/economics.ts, src/endpoints/network/network.module.ts, src/endpoints/network/network.service.ts, src/endpoints/nfts/nft.service.ts, src/endpoints/tokens/entities/token.ts, src/endpoints/tokens/token.controller.ts, src/test/unit/utils/array.extensions.spec.ts, src/utils/cache.info.ts
- Provide some more useful KPIs regarding ecosystem tokens
- Provide supply info for all verified tokens
- Provide total market cap for all tokens
- `/tokens` should return `supply` & `circulatingSupply` for verified tokens
- `/economics` should return attribute `tokenMarketCap`
=> Token economics improvements

src/endpoints/blocks/block.controller.ts, src/endpoints/blocks/block.module.ts, src/endpoints/blocks/block.service.ts, src/endpoints/blocks/entities/block.ts, src/endpoints/identities/identities.module.ts, src/endpoints/network/network.module.ts, src/endpoints/network/network.service.ts, src/endpoints/nodes/node.module.ts, src/endpoints/nodes/node.service.ts, src/endpoints/transactions/transaction.module.ts
- Provide proposer identity in block list & details
- `/blocks?withProposerIdentity` should return `proposerIdentity` attribute in list
- `/blocks/:blockHash` should return `proposerIdentity` attribute
=> Block proposer identity information

src/endpoints/nodes/entities/node.sort.ts, src/endpoints/nodes/node.service.ts
- Possibility to sort node by locked stake
- `/nodes?sort=locked&order=desc` should return nodes with highest locked stake first
=> Sort nodes by locked stake

src/common/websockets/web-socket-publisher-service.ts
- add the possibility to join multiple websocket rooms
- `{{WS_URL}}?address=erd17j9y0hgswqcs9cxcufx259rxnfl8vf9zqlv9990s02g8fy0ht55q43wg8k,erd1jd2g479fz8s0rc3pqnw3df8f406auyaf2r48z69ecwlc32ftg72sczxdcy` you can pass multiple addresses as query parameter
=> Websocket multiple addresses initializer

src/test/integration/controllers/nfts.controller.e2e-spec.ts, src/test/integration/controllers/tokens.controller.e2e-spec.ts
- Add new e2e tests for graphql
- Update tokens.controller.e2e-spec.ts test
- npm run test:e2e controllers -> all tests should pass
=> GraphQL api integration tests

nest-cli.json, package-lock.json, package.json, src/assets/templates/subscribe.html
- Users can't subscribe to elrond newsletter
- Add subscribe email template
=> subscribe email template

src/endpoints/dapp-config/entities/dapp-config.ts, src/endpoints/usernames/entities/account.username.ts, src/endpoints/waiting-list/entities/waiting.list.ts, src/graphql/entities/dapp.config/dap.config.resolver.ts, src/graphql/entities/dapp.config/dapp.config.module.ts, src/graphql/entities/dapp.config/dapp.config.query.ts, src/graphql/entities/username/username.input.ts, src/graphql/entities/username/username.module.ts, src/graphql/entities/username/username.query.ts, src/graphql/entities/username/username.resolver.ts, src/graphql/entities/waiting.list/waiting.list.module.ts, src/graphql/entities/waiting.list/waiting.list.query.ts, src/graphql/entities/waiting.list/waiting.list.resolver.ts, src/graphql/graphql.module.ts, src/graphql/schema/schema.gql, src/test/integration/graphql/dapp.config.graph-spec.ts, src/test/integration/graphql/username.graph-spec.ts
- Implement GraphQL querry for remaining endpoints
- run local API instance localhost:3001/graphql
- create endpoints query and should return specific details
=> implement GraphQL endpoints

src/endpoints/tokens/token.service.ts, src/test/integration/services/tokens.e2e-spec.ts
=> Sort locked accounts by balance descending

src/endpoints/waiting-list/waiting.list.controller.ts, src/endpoints/waiting-list/waiting.list.service.ts, src/graphql/entities/waiting.list/waiting.list.input.ts, src/graphql/entities/waiting.list/waiting.list.query.ts, src/graphql/schema/schema.gql, src/test/integration/services/waiting.list.e2e-spec.ts
-  Query pagination missing 
-  Add Query pagination
-  waiting-list?size=5 should return 5 address (if exist)
=> Add pagination to waiting-list endpoint

src/endpoints/providers/entities/provider.filter.ts, src/endpoints/providers/provider.controller.ts, src/endpoints/providers/provider.service.ts, src/test/integration/services/providers.e2e-spec.ts
-  Add new provider filter ( providers )
- providers?providers=erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc0llllsayxegu,erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqq8hlllls7a6h85 -> should return details for the given providers addresses
=> Add providers filter 

src/endpoints/accounts/account.service.ts, src/endpoints/blocks/block.service.ts, src/endpoints/delegation/delegation.service.ts, src/endpoints/network/network.service.ts, src/endpoints/nfts/nft.service.ts, src/endpoints/nfttags/tag.service.ts, src/endpoints/nodes/node.service.ts, src/endpoints/providers/provider.service.ts, src/endpoints/stake/stake.service.ts, src/endpoints/waiting-list/waiting.list.service.ts, src/test/integration/controllers/nfts.controller.e2e-spec.ts, src/utils/cache.info.ts
-  Create multiple cache info static methods for api services
=>  add cache info methods for api services

src/endpoints/transactions/transaction-action/transaction.action.service.ts
- latest node version passes marshalized NFT data in SmartContractResult data field in the case of MultiESDTNFTTransfer (and possibly other implementations as well)
- implement heuristic that reads the real value from protobuf-marshalized data
- `/results/bfbfaa128d77e31e8edaf9e6a05470af6f2ece8faf6979cdb2f53e65b26feb19` should return in the action field transfer values between `1` and `3` and not very big numbers
=> MultiESDTNFTTransfer marshalized NFT handler

src/test/integration/services/scresults.e2e-spec.ts
- Add new testcase based on https://github.com/ElrondNetwork/api.elrond.com/pull/823
-  npm run test:e2e scresults.e2e-spec.ts
=>  Add scresults unit test (MultiESDTNFTTransfer)

src/test/data/esdt/nft/nft.example.ts, src/test/integration/graphql/nfts.graph-spec.ts, src/test/integration/services/nft.e2e-spec.ts, src/test/integration/services/process.nfts.e2e-spec.ts
- New property was added in nft entity
-  Refactor nft.e2e-spec.ts & process.nft.e2e-spec.ts & nfts.graph-e2e.spec.ts after new property added in NFT entity (isTransferAffected)
-  run : nft.e2e-spec.ts & process.nft.e2e-spec.ts & nfts.graph-e2e.spec.ts  tests
=>  add istransferAffected spec test

package-lock.json, package.json, src/common/indexer/elastic/elastic.indexer.helper.ts, src/endpoints/nfts/entities/nft.filter.ts, src/endpoints/nfts/nft.controller.ts
- Allow filtering NFTs by traits
- `/nfts?traits=Eye%20Color:Yellow;Iris:Large` should return NFT with identifier `TSTSND3-86eb57-03 `
=> Searchable nft traits

src/test/integration/services/transactions.e2e-spec.ts
- refactor and add mocks functions to transactions service tests
-   npm run test:e2e transaction.e2e-spec.ts
=> refactor transaction service unit tests

src/endpoints/providers/provider.service.ts
- When assigning identity to a provider, fetch it from the provider metadata and make sure it is confirmed in keybase as opposed to doing it vice-versa, which would mean that some other identity could be falsely associated with a provider if there is a keybase validation for the given contract
- Make sure the provider identity is fetched in the correct order
=> Two way matching between provider and keybase

src/common/indexer/entities/collection.ts, src/common/persistence/database/database.service.ts, src/common/persistence/mongodb/entities/nft.trait.summary.db.ts, src/common/persistence/mongodb/mongo.db.module.ts, src/common/persistence/mongodb/mongo.db.service.ts, src/common/persistence/passthrough/pass.through.service.ts, src/common/persistence/persistence.interface.ts, src/common/persistence/persistence.service.ts, src/endpoints/collections/collection.service.ts, src/endpoints/network/network.service.ts
- Read collection traits from mongodb
- check whether collection traits stem from mongodb and not elasticsearch
=> Read collection traits from persistence service

src/common/assets/assets.service.ts, src/common/assets/entities/nft.rank.algorithm.ts, src/common/assets/entities/nft.rank.ts, src/common/assets/entities/token.assets.ts, src/endpoints/collections/collection.controller.ts, src/endpoints/collections/collection.service.ts, src/graphql/entities/nft.collection/nft.collection.query.ts, src/graphql/schema/schema.gql, src/utils/cache.info.ts
- Add support for `preferredRankAlgorithm` in collection assets
- Added `/collections/:collection/ranks` for loading manual ranks
- `/collections/TEST-b0fe13/ranks` should return custom ranks
=> NFT collection custom ranks in assets

src/common/indexer/entities/sc.deploy.ts, src/endpoints/accounts/account.service.ts, src/endpoints/accounts/entities/deployed.contract.ts
-  Account smart contracts assets was not returned
-  Add contract assets details
-  `accounts/erd1ss6u80ruas2phpmr82r42xnkd6rxy40g9jl69frppl4qez9w2jpsqj8x97/contracts` -> assets property should be defined
=> label account contracts endpoint

src/crons/cache.warmer/cache.warmer.service.ts, src/endpoints/collections/collection.controller.ts
- Refresh collection ranks in cache warmer
- `/collections/TEST-b0fe13/ranks` should return data
=> Refresh collection ranks in cache warmer

src/test/integration/controllers/collections.controller.e2e-spec.ts, src/test/integration/graphql/collections,graph-spec.ts, src/test/integration/services/collections.e2e-spec.ts
- change collection expected attributes for collections.e2e-spec.ts
- REST API : npm run test:e2e collections.*.e2e-spec.ts
-  Graphql: npm run test:graphql collection.e2e-spec.ts
=> fix API/Graphql collection spec test

package.json, src/common/gateway/gateway.module.ts, src/common/gateway/gateway.service.ts, src/common/indexer/elastic/elastic.indexer.module.ts, src/common/indexer/indexer.module.ts, src/common/indexer/indexer.service.ts, src/common/metrics/api.metrics.service.ts, src/common/metrics/events/log-metrics.event.ts, src/common/persistence/persistence.module.ts, src/common/persistence/persistence.service.ts, src/crons/transaction.processor/transaction.processor.service.ts, src/decorators/log.performance.decorators.ts, src/endpoints/vm.query/vm.query.module.ts, src/endpoints/vm.query/vm.query.service.ts, src/graphql/interceptors/graphql.metrics.interceptor.ts, src/main.ts, src/private.app.module.ts, src/utils/metrics-events.constants.ts
- decouple api-metrics-service from the rest of the app
- remove some circular dependencies
- add event based metrics trigger
=> decouple ApiMetricsService from application

src/endpoints/tokens/token.transfer.service.ts, src/endpoints/transactions/entities/transaction.operation.ts
-  Ticker transaction operation was missing from transaction response 
- Add Token Ticker to transaction operations
- transactions?withOperations=true -> all operations should contain ticker attribute 
- transactions/694e0455469c6a20af18f02b85261c9405123b0d68f8e0f627072696fe73089c -> operations should contain ticker attribute
=> include token ticker in transaction operations

src/test/unit/utils/transaction.utils.spec.ts
-  Expect transaction to return ticker attribute
- npm run test transaction
=> fix transaction ticker spec tests

src/test/integration/controllers/tokens.controller.e2e-spec.ts, src/test/integration/services/dapp.config.e2e-spec.ts, src/test/integration/services/nft.e2e-spec.ts, src/test/unit/graphql/entities/account.detailed/account.detailed.resolver.spec.ts, src/test/unit/utils/transaction.utils.spec.ts
-   Spec tests are failing during new modifications files from NFT service
-  Fix spec tests
- npm run test transaction.utils.spec.ts
- npm run test:e2e nft.e2e-spec.ts
=> fix accounts unit tests from development branch

.github/release.yml
- Adjusted release.yml to reference the correct label for bugfix
=> Fixed release labels

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, src/test/integration/services/tokens.e2e-spec.ts
-  New contract address was created
- Update Code Of Conduct contact address with new contact@multiversx.com
=>  change code of conduct contact address

src/endpoints/transactions/transaction.price.service.ts, src/test/integration/services/transactions.e2e-spec.ts
=> fix undefined price redis error

config/config.devnet.yaml, config/config.e2e-mocked.mainnet.yaml, config/config.e2e.mainnet.yaml, config/config.mainnet.yaml, config/config.testnet.yaml, src/common/api-config/api.config.service.ts, src/endpoints/accounts/account.controller.ts, src/endpoints/accounts/account.service.ts, src/endpoints/accounts/entities/account.detailed.ts, src/endpoints/accounts/entities/account.verification.source.ts, src/endpoints/accounts/entities/account.verification.status.ts, src/endpoints/accounts/entities/account.verification.ts, src/test/integration/services/api.config.e2e-spec.ts, src/test/integration/services/nft.thumbnail.e2e-spec.ts, src/test/integration/services/transactions.e2e-spec.ts
- endpoint which returns contract source code if verified needed
- add endpoint returning verified contract source code
- add isVerified attribute for account entity
- https://api.elrond.com/account/{accountAddress}/verification - should return contract source code if is validated
- https://api.elrond.com/account/{accountAddress} - should have 'isVerified' attribute if smart contract
=> Add verification endpoint and isVerified attribute for smart contracts

src/endpoints/transfers/transfer.controller.ts, src/test/integration/services/transfers.e2e-spec.ts
- The transfer route could not be filtered by function
- Add function filter
- transfers?function=issueNonFungible -> should return all tranfers that include issueNonFungible function
=> add function filter to transfers endpoint

src/endpoints/tokens/token.service.ts
- gateway allows extracting the supply for any non-fungible ESDTs
- Apply supply also for NFTs and SFTs
=> apply supply also to NFTs and SFTs

package-lock.json, package.json
- Update SDK NestJS to latest version
- it should contain the latest improvements for sdk nestjs, including the latest performance optimizations in native auth server
=> Update sdk nestjs

package-lock.json, package.json
- Change mx-nestjs-sdk version to take in account of recents fixes
- Pump mx-nestjs-sdk's version to 0.4.23
=> updated nestjs sdk package

src/common/indexer/elastic/elastic.indexer.service.ts
This PR reverts PR https://github.com/multiversx/mx-api-service/pull/1016
=> Revert Keyword mapping PR

src/endpoints/caching/local.cache.controller.ts, src/endpoints/caching/remote.cache.controller.ts, src/endpoints/process-nfts/process.nfts.public.controller.ts, src/endpoints/transactions.batch/transactions.batch.controller.ts
- Drop support for jwt authentication in all endpoints that require it explicitly
- test auth with jwt, should not work any more
=> Native auth guards only

package-lock.json, package.json, src/utils/cache.info.ts
- Contains fixes for the batchProcess function in the ElrondCachingService
=> Updated sdk-nestjs version to 0.5.1

src/test/integration/services/tokens.e2e-spec.ts, src/test/mocks/token.accounts.mock.json, src/test/unit/utils/typeorm.spec.ts
-  Update tokens.e2e-spec.ts
-  Add new unit test for TypeormUtils.ts
-  run command: npm run test:e2e tokens.e2e-spec.ts
-  run command: npm run test
=> update token service tests

.github/workflows/chatgpt.yml, src/queue.worker/nft.worker/queue/job-services/thumbnails/nft.thumbnail.service.ts
- If attempting to generate waveform thumbnail from an audio file fails, handle error and do not let the instance crash
- trigger process for NFT `TESTMULT-5b41a2-02` which should not fail
=> ffmpeg generate waveform from audio file handle error

src/endpoints/identities/identities.service.ts
=> SERVICES-1619 when topUp is 0, topUpReturn = 0

src/common/data-api/data-api.service.ts, src/common/data-api/entities/data-api.token.ts, src/test/integration/services/data-api.e2e-spec.ts
- For Hatom tokens, tokens price was missing 
- Fetch Hatom tokens price from data-api
- tokens?identifiers=HEGLD-d61095
=> include price for Hatom tokens

src/endpoints/mex/mex.token.service.ts, src/endpoints/tokens/entities/token.detailed.ts, src/endpoints/tokens/entities/token.supply.options.ts, src/endpoints/tokens/entities/token.ts, src/endpoints/tokens/token.controller.ts, src/endpoints/tokens/token.service.ts
=> add denominated supply

src/endpoints/network/network.service.ts, src/endpoints/transactions/transaction-action/recognizers/esdt/transaction.action.esdt.nft.recognizer.service.ts, src/test/integration/services/transactions.e2e-spec.ts
- `getEconomicsRaw` function when failing was not giving too many details in logs
- make the code more readable and the errors more visible
- `/economics` should work the same way, with better error handling
=> Economics refactoring

src/endpoints/network/entities/about.ts, src/endpoints/network/entities/feature.configs.ts, src/endpoints/network/network.service.ts, src/test/unit/services/network.spec.ts
- Add more information regarding network configuration into `/about` endpoint
- Create `FeatureConfigs` entity
- `npm run test network.spec.ts`
- `/about` -> should return features key
=> add features flag

src/endpoints/proxy/proxy.controller.ts
=> fix generic forward proxy

package-lock.json, package.json
- On the OS of the MultiversX api machines, the current sharp dependency could not be installed
- update sharp dependency
- Deploy API, should work
=> Fix sharp dependency

src/endpoints/usernames/username.utils.ts
=> add support for undefined for extract username raw base 64

src/endpoints/transactions/transaction.get.service.ts
- Apply processing of logs before processing operations
- `/transactions/9577b1e88608495a5dc259dc2e313730f44871b859f575bc6e14f380df04ac15` should have only one transfer of 0.001608316309691452 EGLD from `erd1qqqqqqqqqqqqqpgqqkwzsxkjc83vlfex9dmznwm7tjvxlqqkpauqx0n782` to `erd1qqqqqqqqqqqqqpgqnn0yhqdl6fd5dxhwxmf2dgturkpd4yuf8nvqr0h8tl`
=> Remove value from async callback event follow-up

config/config.devnet.yaml, config/config.mainnet.yaml, config/config.testnet.yaml, src/common/api-config/api.config.service.ts, src/crons/transaction.processor/transaction.completed.service.ts
- In case of errors, was hard to debug why transactions were not reported as completed
- Log more details with possibility of controlling log level
- Add support for features section for transactionProcessor, transactionBatch and transactionCompleted crons
- Ensure transactionCompleted cron job reports internal logs
=> Transaction completed logging and feature integration

src/test/unit/controllers/services.mock/shard.service.mock.ts, src/test/unit/controllers/shard.controller.spec.ts, src/test/unit/controllers/tags.controller.spec.ts
- Add new tests for `shard.controller.ts`
- Add new expects to `tags.controller.spec.ts`
- `npm run test` -> all tests should pass
=> add shard controller spec

src/test/unit/controllers/mex.controller.spec.ts, src/test/unit/controllers/services.mock/mex.services.mock.ts
- Adding new tests for `mex.controller.ts`  
- `npm run test` -> all tests should pass
=> add mex controller specs

src/endpoints/stake/entities/global.stake.ts, src/endpoints/stake/stake.service.ts
- Implement backwards compatibility fixes for the stakingv4 changes
- `/stake` should correctly return the data as before, with the same keys as before
=> Staking v4 follow up

src/common/assets/assets.service.ts
- newly added gitkeep files were not ignored by the assets service, resulting in errors
- skip these files
- 
- 
-
=> ignore gitkeep files

src/endpoints/delegation/delegation.service.ts
- Ensuring the /delegation can function without a mandatory delegation manager address allows flexibility, especially in environments where a delegation manager might not be set up or necessary.
-  Implement a conditional check for the presence of a delegation manager address before attempting to query delegation configuration data. This prevents errors related to undefined addresses.
- Introduce a default value for the minimum delegation amount to be used in case the delegation manager address is not available, ensuring that the function can return a consistent structure without failing.
- `/delegation` -> ensure that even if delegationManagerContract is not defined, `/delegation` is working
=> check if delegationManagerAddress is defined

src/endpoints/tokens/token.service.ts
- Add more logs to more easily find out whether the cache warming for tokens is stuck somewhere
=> Extra logging for token cache warming

src/common/indexer/elastic/elastic.indexer.helper.ts, src/crons/tps/tps-warmer.service.ts, src/endpoints/blocks/entities/block.filter.ts, src/endpoints/tps/tps.controller.ts, src/endpoints/tps/tps.service.ts, src/utils/cache.info.ts
- Offer a max tps endpoint
- Also, have a real-time tx counter that does not put high pressure on ES
- `/tps/max` should return max tps
- `/tps/count` should cound transactions in real-time
=> TPS max and total tx count

src/endpoints/identities/identities.service.ts, src/test/unit/services/stake.spec.ts
- include nodeService getValidatorAuctions.jest.fn()
- `npm run test` -> all tests should pass
=> fix missing stake test mock

src/crons/tps/tps-warmer.service.ts, src/endpoints/tps/entities/tps.frequency.ts, src/endpoints/tps/entities/tps.interval.ts, src/graphql/schema/schema.gql, src/utils/tps.utils.ts
- Added support for smaller granularity tps
- `/tps/latest/5s`
- `/tps/history/10m`
=> Smaller granularity tps

src/endpoints/tokens/token.transfer.service.ts
=> Fix imports

package-lock.json, package.json
- update `sdk-core` to latest version: `13.2.2`
=>  update sdk core to latest version

src/endpoints/nodes/node.service.ts
- Include `patch` as naming when parsing "special" node versions
- node versions that contain `patch` should be represented correctly
- <api>nodes/versions
=> Support for patch versions for nodes

k6/script.js
=> Test integration of k6 into API GitHub Workflow

k6/preload.js
=> Test integration of k6 in API GitHub Workflow

config/config.devnet.yaml, config/config.mainnet.yaml, config/config.testnet.yaml
- Certain features should be disabled by default
=> Default features disabled

src/common/indexer/elastic/elastic.indexer.helper.ts, src/test/unit/services/mex.token.charts.spec.ts
- nfts and sfts were filtered incorectly
- fix filters
- fix unit tests
- 
- 
-
=> fix nft filters

.github/workflows/build-docker-image.yaml, Dockerfile, entrypoint.sh
we need a public docker image that contains api-service to use in other projects too.
added dockerfile, docker entrypoint script
=> add entrypoint

package-lock.json, package.json
- rename package `elrond` -> `multiversx`
=> update package name

src/common/gateway/entities/gateway.component.request.ts, src/endpoints/proxy/gateway.proxy.controller.ts
- extract all storage keys for a specific address
- `<api>/address/erd1qqqqqqqqqqqqqpgq076flgeualrdu5jyyj60snvrh7zu4qrg05vqez5jen/keys`
=> add address keys proxy

src/endpoints/esdt/esdt.address.service.ts
- return `balance` field for every NonFungibleESDT
- `<api>/accounts/erd1gtu0hzemrva60ns0euxafkuvphwyf7pgc0dl95u6ha8p6qwwe72qqgttmm/nfts?withSupply=false&type=NonFungibleESDT`
- `<api>/accounts/erd13g9mh46qewalxp5eus307uc0ceqr3ycasg2pc9kkjck329dmqpvqdsygw5/nfts?size=10000`
=> add NFT balance

src/common/gateway/entities/tx.in.pool.fields.ts, src/common/gateway/gateway.service.ts, src/endpoints/pool/entities/pool.filter.ts, src/endpoints/pool/entities/transaction.in.pool.dto.ts, src/endpoints/pool/pool.controller.ts, src/endpoints/pool/pool.module.ts, src/endpoints/pool/pool.service.ts, src/test/mocks/pool.mock.json, src/test/unit/services/pool.spec.ts
- The new node versions expose more fields on the transaction pool
- Update the API endpoint to contain all the new fields
- <api>/pool should contain the correct fields
=> API-70: improve tx pool endpoint

src/common/assets/assets.service.ts, src/common/keybase/keybase.service.ts
- added async & resolve promises
=> fix get profile

src/common/assets/assets.service.ts, src/common/keybase/keybase.service.ts, src/endpoints/accounts/account.controller.ts, src/endpoints/nfts/entities/nft.sub.type.ts, src/endpoints/tokens/entities/token.filter.ts, src/endpoints/tokens/entities/token.ts, src/endpoints/tokens/token.service.ts, src/test/unit/services/tokens.spec.ts
=> Merge dev into feat sovereign nov22

config/config.placeholder.yaml, config/dapp.config.placeholder.json, entrypoint.sh
=> Ft/multiple entry/docker file2

src/common/gateway/gateway.service.ts
- Added validatorAuction to GatewayComponentRequest enum in GatewayService, enhancing the request capabilities for transaction processing
=> add validator auction to snapshotless

config/config.placeholder.yaml, entrypoint.sh
=> updated placeholder config

src/endpoints/tokens/token.service.ts, src/test/unit/services/tokens.spec.ts
- adjust tokens sorting and tokens market cap
=> adjust tokens endpoints

config/config.mainnet.yaml
- The template configuration for Mainnet andromeda was not updated
- Use proper configuration
- 
- 
-
=> update andromeda config template enable epoch

src/endpoints/mex/mex.token.service.ts
- token price was taken from the first pool found on xExchange. instead of selecting the pool with the highest liquidity
- only update token data when a pool with higher total value (liquidity) is found compared to the currently stored pool
- changed from collecting all tokens in an array to using a map that tracks the best liquidity pool for each token
=> ferch token price from highest liquidity pool

src/common/indexer/elastic/elastic.indexer.service.ts, src/common/rabbitmq/rabbitmq.nft.handler.service.ts, src/endpoints/nfts/nft.service.ts, src/queue.worker/nft.worker/nft.worker.service.ts, src/queue.worker/nft.worker/queue/job-services/media/nft.media.service.ts, src/queue.worker/nft.worker/queue/job-services/metadata/nft.metadata.service.ts
=> update MetaESDT tokens
