multiversx/mx-api-service

docs/swagger.md

Fixed spelling in the first h2 element that appears in API URLs (E.g.: https://api.elrond.com/ ).
@tanghel

fix spelling in swagger documentation file

---

.github/PULL_REQUEST_TEMPLATE.md
src/common/elastic/elastic.service.ts
src/common/metrics/entities/elastic.metric.type.ts
src/common/metrics/metrics.service.ts

- Elastic search metrics are not reported when individual items are requested
- Add metric for item request
- Remove took metric since it's not used any more
- Added elastic metric type to distinguish between list/item/count requests
- perform various requests on endpoints that fetch data from elastic, such as /transactions or /blocks as list, item and count
- request metrics using http://localhost:4001/metrics and watch the correct buckets go up

Elastic profile get item

---

src/common/keybase/keybase.service.ts

- Keybase.pub gives error when too many requests are performed against it
- reduce degree of parallelizing to 1, since it will be handled in ~2m30s anyway, and is executed every 30 minutes in the cache warmer

Keybase pub less parallel requests

---

src/endpoints/accounts/account.controller.ts
src/endpoints/transactions/transaction.controller.ts

- when fetching transaction list and withScResults / withOperations parameter is set and a large size is requested, the underlying elasticsearch instance can receive up to 1000 queries, thus potentially bringing the API / Elasticsearch instance down
- if withScResults / withOperations parameter is set, limit size to max 50

Transactions withScResults / withOperations limit

---

src/queue.worker/nft.worker/queue/job-services/thumbnails/nft.thumbnail.service.ts

- NFT Thumbnails could not be generated since when checking for existence of file was returning 403 Forbidden, and only 404 Not Found was handled
- handle also 403 Forbidden in list of returned http statuses

NFT Thumbnail fix

---

src/endpoints/collections/collection.controller.ts

- There is no possible way to search collections by identifiers on list
- Add 'identifiers' query param and apply filter to ES

filter collections by identifiers

---

src/common/caching/caching.service.ts
src/endpoints/esdt/esdt.service.ts
src/endpoints/tokens/token.controller.ts
src/endpoints/tokens/token.service.ts
src/test/unit/utils/array.extensions.spec.ts
src/utils/batch.utils.ts
src/utils/extensions/array.extensions.ts

- Currently branded tokens are displayed in random order.
- Sort branded tokens by number of holders

sort branded tokens by holders

---

src/endpoints/tokens/token.service.ts

- token supply & circulatingSupply not returned when fetching details
- use await to wait for supply to be attached to token

use await to fetch token supply

---

src/common/elastic/elastic.service.ts

- balances for at most 25 locked accounts were fetched
- adjust length of result to number of requested addresses

adjust page size to number of addresses

---

src/endpoints/identities/identities.service.ts
src/endpoints/providers/provider.service.ts

- Identities and providers were not shown if they had valid nodes that are leaving
- change filter from `lockedAmount > 0` to `nodesCount > 0`
- `/identities/nethus` should return http 200
- `/providers/erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqslllllsq4a3pq` should return http 200

Identity filter improvement

---

src/test/integration/identities.e2e-spec.ts

- identities test was failing because distribution object was empty
- check sum equals 1 only if distribution contains at least one key

verify distribution only if at least one value inside

---

src/endpoints/tokens/token.service.ts

- Pending balances shows in ESDT token accounts
-  remove pending balances from ESDT token accounts
-  Make requests to '/tokens/:identifier/accounts', it should not show any `pending-` in front of addresses

remove ESDT pending balances

---

src/endpoints/tokens/entities/token.transfer.properties.ts
src/endpoints/tokens/token.transfer.service.ts

- There are no informations about token logo in transfers
- Extend token transfer properties to use svgUrl for token
- Find transactions that are related to mex or esdt interactions
- in trasfer properties should appear token logo url

extend token transfer properties

---

src/common/caching/entities/cache.info.ts
src/endpoints/tokens/token.transfer.service.ts

- Token transfer properties were refreshed only after one day
- Refresh token transfer properties every hour
- in /transactions endpoint, make sure the token assets are updated accordingly

refresh token transfer properties every hour

---

src/endpoints/transactions/transaction.get.service.ts

- Scresults are recognized as transactions
- Check if transaction returned from gateway is a sc result
- /transactions/c39f65da9751bce38b28290dd19cbd8193584d06ed9927d382366fe64b62f1bc should return 'Transaction not found'

check if transaction is scresult before returning

---

src/endpoints/tokens/entities/token.detailed.ts
src/endpoints/tokens/token.service.ts

- token circulating supply available as string, although usually it is a numeric amount
- change `supply` and `circulatingSupply` for token to denominated numeric value
- `tokens/RIDE-7d18e9?fields=supply,circulatingSupply` should return two numeric values

Token numeric circulating supply

---

src/endpoints/stake/stake.service.ts

- UnhandledPromiseRejection in getAllStakesForNodes function
- implemented await in function
- FLUSHDB, then fetch 1000 transactions with plugin activated. without the fix, it should crash the whole process

fixed UnhandledPromiseRejection in getAllStakesForNodes function

---

src/endpoints/accounts/account.service.ts

- Make sure account details works with legacy indexers even if `useLegacyElastic` flag is set to `false`
- set indexer url to `http://104.248.103.160`
- set `useLegacyElastic` flag to `false`
- try `accounts/:account` route and make sure it does not crash

Legacy elastic support

---

src/endpoints/tokens/entities/token.detailed.ts
src/endpoints/tokens/token.controller.ts
src/endpoints/tokens/token.service.ts
src/test/integration/tokens.e2e-spec.ts
src/utils/number.utils.ts

- supply as numeric both in token details and token supply details
- `/tokens/RIDE-7d18e9?fields=supply,circulatingSupply` should have both fields `supply` and `circulatingSupply` of type numeric, denominated
- `/tokens/RIDE-7d18e9/supply` should have both fields `supply` and `circulatingSupply` of type numeric, denominated

support for numeric supply in token endpoint

---

src/endpoints/nfts/nft.service.ts

- endpoint `/accounts/:account/nfts` very slow when many NFTs inside the account
- use optimized sort function when sorting NFTs by identifier
- do not sort when called from `/accounts/:account/nfts/count`
- `accounts/erd1qqqqqqqqqqqqqpgqd9rvv2n378e27jcts8vfwynpx0gfl5ufz6hqhfy0u0/nfts?search=ECYBORGX-f0a8cf` should return data faster

Account NFTs performance improvement

---

src/endpoints/network/network.service.ts

- update locked tokens from 2.660.000 to 1.330.000

Economics locked tokens update

---

src/endpoints/network/network.service.ts

- Market cap invalid from data.elrond.com, which in turn fetches data from coinmarketcap
- calculate market cap as price * circulatingSupply
- /economics should return market cap of 4.2 billion instead of 4.0 billion

Calculate market cap instead of fetching it from data.elrond.com

---

src/test/unit/utils/address.utils.spec.ts
src/utils/address.utils.ts

- Every byte of value is responsible for one attribute
- Use binary value and check every byte
- Find smart contracts that are (readable and upgradable/payable and payable by sc)

decode smart contract attributes using binary values

---

config/config.devnet.yaml
config/config.mainnet.yaml
config/config.testnet.yaml
src/common/persistence/persistence.module.ts

- database.enabled flag in config instead of flag in .env file
- PassThroughService should be used if database.enable = true, else DatabaseService

database enabled flag

---

src/endpoints/esdt/esdt.address.service.ts

- fetch correctly timestamp field
- `accounts/erd1smke9ndlng4t60qqf5descwyjneffasx0zm99n6m7vxvzhuz06rqywql34/nfts?source=elastic` should have timestamp in the result set

fixed timestamp field for account nft

---

src/common/elastic/elastic.service.ts
src/common/gateway/entities/gateway.component.request.ts
src/endpoints/tokens/token.service.ts

- Incoherency in esdt balance details for address
- Always get esdt token balance from gateway
- Take this request on devnet accounts/erd1spyavw0956vq68xj8y4tenjpq2wd5a9p2c6j8gsz7ztyrnpxrruqzu66jx/tokens/CHIP-cecd4c
- Make sure that the balance shown on list is the same with balance shown on details

Token balance incoherency fix

---

src/endpoints/tokens/token.transfer.service.ts
src/endpoints/transactions/entities/transaction.log.ts
src/endpoints/transactions/entities/transaction.operation.ts
src/endpoints/transactions/transaction.get.service.ts
src/endpoints/transactions/transaction.service.ts
src/test/unit/utils/transaction.utils.spec.ts
src/utils/transaction.utils.ts

- Operations from multiple scrs were wrongly removed as duplicates
- Remove only the transfer operations from the parent transaction if an identical transfer operation exists in a scr
- `transactions/53a46a1aa246709aae2d66dc8481547dfb13709dd566f913c39c2fce10aacc24` should have as many transfers as there are localMints

trim only duplicate operations

---

src/endpoints/nodes/node.service.ts

When sorting by validatorIgnoredSignatures the array was not sorting the nodes array.
In case of sorting, ignore the nodes that not have the wanted filtered property.
https://api.elrond.com/nodes?from=0&size=25&sort=validatorIgnoredSignatures&order=desc 
The fix will be also pushed on ElrondScan.

Add query filter on sort only if node has property

---

src/endpoints/esdt/esdt.address.service.ts

- Huge performance issue when fetching smart contract nfts
- automatically fetch nfts from elastic if smart contract
- `accounts/erd1qqqqqqqqqqqqqpgqrc4pg2xarca9z34njcxeur622qmfjp8w2jps89fxnl/nfts` should not time out

if address is smart contract, fetch nfts from elastic

---

src/endpoints/esdt/esdt.address.service.ts

- Account NFT count filtered by type returns always 0
- if account nft count uses `type` filter and address is not smart contract, count gateway nfts instead of fetching count from elastic search
- `accounts/erd1kcx0ha7j206tu4lke6vudq3h4dk88dz06pwugjf3q2rp2jd6rp8swmzjzu/nfts/count` should return 7

fetch count from gateway nfts if filtered by type

---

src/endpoints/esdt/esdt.address.service.ts

- proper use of pagination logic
- `/accounts/erd109avvnrttdpm3m2ua59tnz4y8zjqfcqzxdkr74q8qcgm8vxfplzqg24vux/nfts?size=1000&from=0` should return 3 items
- `/accounts/erd109avvnrttdpm3m2ua59tnz4y8zjqfcqzxdkr74q8qcgm8vxfplzqg24vux/nfts?size=1000&from=2` should return 1 item

fixed account nft pagination

---

src/endpoints/esdt/esdt.address.service.ts

- extended support for filtering account nfts by multiple types
- `accounts/erd1qqqqqqqqqqqqqpgqr8z5hkwek0pmytcvla86qjusn4hkufjlrp8s7hhkjk/nfts?type=SemiFungibleESDT,MetaESDT` should return some values

Account nfts type filter

---

src/endpoints/esdt/esdt.address.service.ts

- do not sort account nfts when coming from elastic

No account nft sorting if elastic

---

src/endpoints/transactions/entities/dtos/transaction.decode.dto.ts
src/endpoints/transactions/transaction.controller.ts
src/endpoints/transactions/transaction.service.ts

- No possibility to decode transaction actions before sending.
- Create an endpoint to decode transaction and retrieve action before sending to protocol
- Create a valid JSON transaction and before applying signature send a POST request to /transactions/decode

Decode transaction action berfore sending

---

src/common/persistence/database/database.service.ts
src/endpoints/nfts/nft.service.ts

- A problem for one nft will return an empty array result
- Get nft metadata and media one by one to log unexpected error for each nft

get nfts details one by one from db to log unexpected errors

---

src/crons/transaction.processor/transaction.processor.service.ts

- instead of search nft create operation by position, find it by action & type
- Transaction `6579e143ec1e177b27c9193aac1733685f027ce6d01f2646c44768a00b1bc57c` should be properly recognized as a nft create transaction

NFT buy fix

---

src/common/elastic/entities/must.query.ts
src/common/elastic/entities/query.type.ts
src/endpoints/transfers/transfer.service.ts

- use `canBeIgnored` flag when fetching scrs from operations
- `/accounts/erd17pupr269rd980g0pu7f7xhdmswyr7hxhds8yt8dm7pg903pyy69strr5up/transfers` should contain scr with hash `90205fe40e8390dad2eb105df7c143e56e9421f374c009a63640455772140f7c`

use canBeIgnored flag to exclude gas refunds / double scrs

---

src/endpoints/network/network.service.ts

- APR was wrongly calculated because it subtracted protocol sustainability twice
- remove subtract of protocol sustainability values
- calculate network total stake by subtracting queue values
- `/economics` should return baseApr 16.89%, topUpApr 11.44%, apr 15.02%

fixed apr value

---

src/endpoints/collections/collection.service.ts
src/endpoints/esdt/esdt.address.service.ts
src/endpoints/nfts/nft.service.ts
src/test/integration/esdt.address.e2e-spec.ts
src/test/integration/esdt.e2e-spec.ts

- Since account balances should be always taken from the gateway, we try to fetch data from it as much as possible
- Because the `/address/:address/esdt/` endpoint is not optimal in the case of smart contracts, we fetch the list of nfts for a smart contract from the elasticsearch
- Because the `/address/:address/nft/:collection/nonce/:nonce` endpoint does not have performance issues, we prefer this one regardless of whether the address is a smart contract or not
- Use gateway endpoint if fetching single nft for an address
- `/accounts/erd1qqqqqqqqqqqqqpgqrc4pg2xarca9z34njcxeur622qmfjp8w2jps89fxnl/nfts/EGLDMEXFL-ef2065-027157` endpoint should fetch data from gateway, not elastic

return single nft for an account from gateway

---

src/common/elastic/entities/elastic.query.ts
src/endpoints/tokens/token.service.ts
src/test/integration/accounts.e2e-spec.ts
src/test/integration/tokens.e2e-spec.ts

- /esdt endpoint very heavy for smart contracts and was called in `/accounts/:account/tokens` & `/accounts/:account/tokens/count` endpoint
- if smart contract, fetch token list information from elasticsearch
- `/accounts/erd1qqqqqqqqqqqqqpgqrc4pg2xarca9z34njcxeur622qmfjp8w2jps89fxnl/tokens` should not time out
- `/accounts/erd1qqqqqqqqqqqqqpgqrc4pg2xarca9z34njcxeur622qmfjp8w2jps89fxnl/tokens/count` should not time out

Account tokens from Elasticsearch if Smart Contract

---

src/endpoints/esdt/esdt.address.service.ts

- Account NFT was not returning 404 error
- add balance check when fetching nft from gateway
- `/accounts/erd1qqqqqqqqqqqqqpgq7epdy2nss28tr3966gr9pcxr0w5xvgjpu00s3xhh7y/nfts/NATIONAL-91e064-08` should return data
- `/accounts/erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqplllst77y4l/nfts/NATIONAL-91e064-08` should return 404 not found

Proper throw Account NFT not found 

---

src/endpoints/tokens/token.service.ts

- Proper throw Account NFT not found
- `/accounts/erd1qqqqqqqqqqqqqpgqa0fsfshnff4n76jhcye6k7uvd7qacsq42jpsp6shh2/tokens/WEGLD-bd4d79` should return token info
- `/accounts/erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqplllst77y4l/tokens/WEGLD-bd4d79` should return 404 not found

Account Token not found error

---

src/utils/token.utils.ts

- add https://gateway.ipfs.io/ipfs as whitelisted gateway
- `/nfts/BEAK-739294-04` should return `"isWhitelistedStorage": true`

Add IPFS whitelisted gateway

---

src/endpoints/collections/collection.service.ts

- early exit if account is not creator for any collection
- `collections?creator=erd1qqqqqqqqqqqqqpgqmqq78c5htmdnws8hm5u4suvags36eq092jpsaxv3e7` should return empty array

early exit if account is not creator for any collection

---

src/endpoints/accounts/account.controller.ts
src/endpoints/accounts/account.module.ts
src/endpoints/accounts/account.service.ts
src/endpoints/tokens/token.service.ts
src/test/integration/accounts.e2e-spec.ts

- validate whether token exists in account history endpoint
- `https://api.elrond.com/accounts/erd1qqqqqqqqqqqqqpgqmqq78c5htmdnws8hm5u4suvags36eq092jpsaxv3e7/history/RIDE-7d18e9` should return values
- `https://api.elrond.com/accounts/erd1qqqqqqqqqqqqqpgqmqq78c5htmdnws8hm5u4suvags36eq092jpsaxv3e7/history/RIDE-7d18e9TEST` should return 404 not found

Validate token in account history

---

src/endpoints/nfts/nft.controller.ts

- propagate isWhitelistedStorage parameter for nft count as well
- `/nfts/count?isWhitelistedStorage=true&collection=LKMEX-f4d898` should return 0

Is whitelisted storage nft count

---

src/endpoints/collections/collection.service.ts

- Return correct collections by creator count
- `/collections/count?creator=erd1qqqqqqqqqqqqqpgqmqq78c5htmdnws8hm5u4suvags36eq092jpsaxv3e7` should return 1 (not ~4800)

Fixed collections by creator count

---

src/common/elastic/elastic.service.ts
src/endpoints/collections/collection.controller.ts
src/endpoints/esdt/esdt.service.ts
src/endpoints/nfts/nft.controller.ts
src/endpoints/nfts/nft.service.ts
src/endpoints/tokens/token.controller.ts
src/endpoints/tokens/token.service.ts
src/test/integration/controllers/nfts.controller.e2e-spec.ts
src/test/integration/esdt.e2e-spec.ts
src/test/integration/tokens.e2e-spec.ts

- Added Nft accounts endpoint 
- Deprecated Nft owners endpoint
- Collection nfts endpoint
- Fix pagination for nft accounts endpoint
- Validate whether nft exists in nft accounts endpoint
- Validate whether token exists in token accounts endpoint
- `/nfts/LKMEX-aab910-04/accounts?from=0` and `/nfts/LKMEX-aab910-04/accounts?from=1` should return results from different offsets
- `/nfts/LKMEX-aab910-04/owners?from=0` and `/nfts/LKMEX-aab910-04/owners?from=1` should return results from different offsets
- NFT owners endpoint should be marked as deprecated in swaggerdoc
- `/collections/KROGAN-54c361/nfts` should return array of nfts of collection KROGAN-54c361
- `/nfts/KROGAN-54c361/owners` should return 404
- `/tokens/blabla/accounts` should return 404

Token accounts fixes

---

src/common/caching/entities/cache.info.ts
src/crons/cache.warmer/cache.warmer.module.ts
src/crons/cache.warmer/cache.warmer.service.ts
src/endpoints/transactions/transaction-action/recognizers/mex/mex.settings.module.ts
src/endpoints/transactions/transaction-action/recognizers/mex/mex.settings.service.ts
src/endpoints/transactions/transaction-action/recognizers/mex/transaction.action.mex.recognizer.module.ts

- cache warm mex settings, to refresh farms more often
- provide mex settings endpoint for debugging purposes
- `/mex-pairs` should only return active pairs

Mex settings cache warm

---

src/endpoints/sc-results/scresult.controller.ts
src/utils/pipes/parse.array.pipe.ts

- Limit array size for `ParseArrayPipe` and filter distinct values

limit array size for ParseArrayPipe

---

src/endpoints/transactions/transaction.service.ts

- keep transaction in pending status while it has pending results
- with `transactionProcessor` and `transactionCompleted` flags activated, transactions that have `pendingResults: true` should have status `pending` instead of `success`

Transaction pending while pendingResults true

---

src/endpoints/blocks/block.service.ts

- `/blocks` does not display `shard` fields
- Send an API request to `/blocks` and check if you have the `shard` field

rename shard field for block

---

src/endpoints/accounts/account.controller.ts
src/endpoints/accounts/account.module.ts
src/endpoints/accounts/account.service.ts
src/endpoints/sc-results/scresult.service.ts
src/endpoints/transactions/entities/transaction.filter.ts
src/endpoints/transfers/transfer.service.ts

- Instead of fetching from multiple data sources, use the unified transfers collection to fetch both transfers count and scr count
- `/accounts/erd1qqqqqqqqqqqqqpgqq70j7ldp55mq9gzzaxt354lsv2h0j8qxpr9s9tcg9d` should have `txCount` + `scrCount` equal to `/accounts/erd1qqqqqqqqqqqqqpgqq70j7ldp55mq9gzzaxt354lsv2h0j8qxpr9s9tcg9d/transfers/count`

extract tx count / scr count from transfers

---

src/endpoints/collections/collection.service.ts
src/endpoints/collections/entities/nft.collection.ts
src/endpoints/esdt/esdt.address.service.ts
src/endpoints/esdt/esdt.service.ts
src/endpoints/tokens/entities/collection.role.for.address.ts
src/endpoints/tokens/entities/collection.roles.ts
src/endpoints/tokens/entities/token.detailed.ts
src/endpoints/tokens/entities/token.roles.ts
src/endpoints/tokens/token.controller.ts
src/endpoints/tokens/token.service.ts
src/test/integration/esdt.e2e-spec.ts
src/test/integration/tokens.e2e-spec.ts
src/utils/token.utils.ts

- Fix token roles to use the correct boolean attributes `canMint` & `canBurn`
- Added string array of roles for collection & token, to maintain backwards compatibility
- `/collections/PASS-3df7bf` should contain roles attribute exposing roles both as boolean and also as string array
- `/tokens/WEGLD-bd4d79` should contain roles attribute exposing roles both as boolean and also as string array
- `/tokens/WEGLD-bd4d79/roles` should return roles both as boolean and also as string array

Token roles fix

---

src/endpoints/collections/collection.service.ts
src/endpoints/nfts/nft.service.ts

- Allow branding for individual NFTs. This will be used for branding price discovery tokens, which have predictable nonces
- `/nfts/LKMEX-3b7d9a-01` should return in description field `Locked MEX. Equal in value to MEX. Not tradeable. Testing asset of a specific NFT`

Nft by identifier branding

---

src/endpoints/esdt/esdt.address.service.ts
src/endpoints/nfts/nft.service.ts

- NFTs minted in the same block appear random instead of ordered
- both in global nfts and account nfts, sort by nonce as a secondary criteria
- `/nfts?collection=PIGGYMAX-f0432f` should return nonces in descending order
- `/accounts/erd1qqqqqqqqqqqqqpgq2j35zktgvhazpvzrr9m8649gnqz53uydu00sflu9rz/nfts?collection=PIGGYMAX-f0432f` should return nonces in descending order

Sort nfts by timestamp, then by nonce

---

config/config.devnet.yaml
config/config.mainnet.yaml
config/config.testnet.yaml
src/endpoints/esdt/esdt.address.service.ts
src/main.ts

- When targeting non-update ES, account nfts are returned in no particular order, thus causing pagination issues
- Is it a bug or or is it a feature? Who knows...
- When indexer v3 is not activated, sort by accountesdt `_id`
- `/accounts/erd1qqqqqqqqqqqqqpgqd9rvv2n378e27jcts8vfwynpx0gfl5ufz6hqhfy0u0/nfts` should always be returned in the same order

Account nft sorting fix

---

src/endpoints/accounts/account.controller.ts

- Provide Account contracts count alternative endpoint
- `/accounts/erd1ss6u80ruas2phpmr82r42xnkd6rxy40g9jl69frppl4qez9w2jpsqj8x97/contracts/c` should return `29`

/c endpoint for account contracts

---

src/endpoints/mex/mex.controller.ts

-  mex/:address route is no longer available
- Deprecate /mex/:address route

deprecate mex/:address route

---

src/common/rabbitmq/rabbitmq.nft.consumer.ts
src/test/integration/controllers/accounts.controller.e2e-spec.ts

- Because events are processed in a serialized way, many NFT Creates can cause ack timeout (30 min)
- process all events in parallel
- Pretty difficult to test locally
- Block with hash `1b3cdc19710ded3f7a72b2c90498a6fe798f3472bd2c95ff0f45ef9dc3be3787` was processed with the parallel fix on mainnet in 8s instead of at least 2100s (350 NFTs * 5 seconds wait time)

process events in parallel

---

src/endpoints/nfts/nft.service.ts

- do not reprocess attributes for metadata
- `/nfts/OSHIRO-cb3446-4a` attributes should return `dGFnczpKYXBhbixFbHJvbmQsS2l0c3VuZSxZb2thaTttZXRhZGF0YTpRbVRUVVl3VnhmZ0JRaUJLYjlOdHJQamJrNktzamZFU29WN1p5ZmpTNUNNWHJOLzQwMC5qc29u`

NFT metadata fix

---

src/endpoints/endpoints.services.module.ts
src/endpoints/nfts/nft.controller.ts
src/endpoints/nfts/nft.service.ts
src/queue.worker/nft.worker/nft.worker.service.ts
src/queue.worker/nft.worker/queue/job-services/media/nft.media.service.ts
src/queue.worker/nft.worker/queue/nft.queue.controller.ts
src/test/integration/nft.media.e2e-spec.ts

- NFT Thumbnail resolve endpoint
- `/nfts/W3C-bcc335-076e/thumbnail` should redirect to `https://media.elrond.com/nfts/thumbnail/W3C-bcc335-325a9501 `

Nft thumbnail resolver

---

src/common/caching/caching.service.ts
src/common/caching/entities/cache.info.ts
src/common/elastic/elastic.service.ts
src/crons/cache.warmer/cache.warmer.service.ts
src/endpoints/esdt/entities/esdt.locked.account.ts
src/endpoints/esdt/entities/esdt.supply.ts
src/endpoints/esdt/esdt.module.ts
src/endpoints/esdt/esdt.service.ts
src/endpoints/nfts/nft.service.ts
src/endpoints/tokens/entities/token.assets.ts
src/endpoints/tokens/entities/token.filter.ts
src/endpoints/tokens/entities/token.sort.ts
src/endpoints/tokens/entities/token.supply.result.ts
src/endpoints/tokens/token.controller.ts
src/endpoints/tokens/token.service.ts
src/endpoints/tokens/token.transfer.service.ts
src/endpoints/transactions/entities/transaction.filter.ts
src/endpoints/transactions/transaction.service.ts

- Support for declaring `extraTokens` in token assets, with the effect of calculating total number of token accounts / transactions taking into consideration other similar tokens (LP tokens, Farm tokens, Metastaking, etc.)
- `/tokens/RIDE-7d18e9` should contain > 70k accounts, > 1mil transactions
- `/tokens/RIDE-7d18e9/supply` should also contain locked accounts information

Token multiple assets

---

src/endpoints/nfts/nft.service.ts
src/endpoints/transactions/transaction-action/recognizers/esdt/transaction.action.esdt.nft.recognizer.service.ts
src/endpoints/transactions/transaction-action/recognizers/mex/mex.pair.action.recognizer.service.ts
src/endpoints/transactions/transaction-action/transaction.action.service.ts
src/endpoints/transactions/transaction.get.service.ts
src/endpoints/transactions/transaction.service.ts

- Update NFT attributes from gateway to mitigate the issue where the indexer does not reflect attribute changes
- `/nfts/EREX-80e5a4-44` base64 decoded attributes should contain `metadata:Qmd5SS16SD7DDPZ3RzSsxdt6Dg3Lkaw9AVbhJMQNojYJdE/468.json`

in single nft endpoint, apply attributes from gateway

---

src/endpoints/transactions/transaction-action/recognizers/mex/mex.locked.asset.action.recognizer.service.ts

- Unlock assets description misleading
- Simplified unlock assets message
- `/transactions/9b3f058a376907b52aeaf20f24c6e0bc0fb380ff4d77b3c50b6d7743f97e1ec4` should have action.description = 'Unlock assets'

unlock lkmex description fix

---

src/endpoints/nfttags/tag.service.ts

-  Tags endpoint returned by default only two elements
-  Fix query pagination
-  /tags -> 25 tags
- /tags?from=0&size=100 -> 100 tags

fix query pagination

---

src/endpoints/esdt/esdt.service.ts

- Calculate token accounts & transactions for all tokens, not only those that have assets
- After waiting a few minutes so that Esdt tokens invalidations cache warmer is finished: `/tokens/UPARK-982dd6` should contain > 1000 accounts & transactions

Calculate token accounts and transactions for all tokens

---

src/endpoints/esdt/entities/esdt.locked.account.ts
src/endpoints/esdt/esdt.service.ts
src/endpoints/mex/mex.pairs.service.ts
src/endpoints/tokens/token.service.ts

- re-establish token price
- locked accounts without name
- denominate locked account balance
- list only active pairs
- `/tokens/RIDE-7d18e9` should have price & marketCap
- `/tokens/RIDE-7d18e9/supply` lockedAccount should not contain name attribute at all
- `/tokens/RIDE-7d18e9/supply?denominated=true` lockedAccounts balances should be denominated numbers
- `/mex/pairs` should all have status `active`

Small fixes

---

src/public.app.module.ts
src/test/unit/utils/string.extensions.spec.ts
src/test/unit/utils/token.utils.spec.ts
src/utils/extensions/string.extensions.ts
src/utils/token.utils.ts

- support for ipfs urls ending with '.ipfs.dweb.link'
- `/nfts/BOB-6b96b4-17a4` should have url [https://media.elrond.com/nfts/asset/bafybeialabty37gvrk4l5cmvayg5lji7oskm2bhulphnf374aaq3kixch4](https://media.elrond.com/nfts/asset/bafybeialabty37gvrk4l5cmvayg5lji7oskm2bhulphnf374aaq3kixch4)

Ipfs dweb link url support

---

src/test/integration/nft.e2e-spec.ts

-  getNftForAddress() test failed
-  Refactor getNftForAddress() test case and add one test that returns undefined if account does not contain any NFTs
-  Run nft.e2e-spec.ts and all test must be passed

fix nft service failed test

---

src/endpoints/nfts/nft.service.ts

- Since the last index update, MetaESDTs are not stored in the `tokens` index
- If fetching NFT details fails, try to fetch it also from the `accountsesdt` index
- `/nfts/LKMEX-aab910-39a090` should return data

fetch nft details from accountsesdt if not found

---

src/common/elastic/elastic.service.ts

- in case of indexer having issues indexing owners, the wrong one is returned in the API
- when fetching accountsesdt by identifiers, sort by timestamp descending to fetch correct owners first
- `/nfts/SRB-61daf7-1e11` should return owner `erd1qafz8ljqr8mksmjkdvxvcms0qcqe4nqzj6lw2pv5vjxr2xjsnxcqfcg85r`
- `/nfts/PASS-1c7c6a-51` should return owner `erd1adz0ud7q3edwv5de9suu6lcdz4lf4svje50vpplngkslhadvjmxqa0qwcr`

NFT owners sort fix

---

src/common/elastic/entities/elastic.query.ts
src/endpoints/collections/collection.service.ts

- searching by `SHARK` in [api.elrond.com](http://api.elrond.com/) will return multiple resuts, whereas in [internal-api.elrond.com](http://internal-api.elrond.com/) will return 0 results
- always perform lowercase search
- search also by name field
- `collections?search=SHARK` should return multiple results
- `collections?search=ElrondSharks` should return one result

search by collection case insensitive

---

config/config.e2e.mainnet.yaml
src/endpoints/nfts/nft.service.ts
src/test/integration/api.config.e2e-spec.ts
src/test/integration/controllers/accounts.controller.e2e-spec.ts
src/test/integration/controllers/tags.controller.e2e-spec.ts
src/test/integration/nft.tag.e2e-spec.ts
src/test/integration/scresults.e2e-spec.ts
src/test/integration/tokens.e2e-spec.ts
src/test/integration/transactions.e2e-spec.ts

-  search filter did not search by name + identifier
-  Change elastic search condition to find NFT by name+identifier
-  /nfts?search=EGLDSMKS-8cb0f2 - return all nfts from collections
- /nfts?search=ROC - returnsall nfts from collection ROCKET-2e6fba and F8ROCK-aa7828

nft-search - fix tests

---

src/endpoints/accounts/account.controller.ts
src/endpoints/accounts/account.module.ts
src/endpoints/sc-results/entities/smart.contract.result.ts
src/endpoints/sc-results/scresult.controller.ts
src/endpoints/sc-results/scresult.module.ts
src/endpoints/sc-results/scresult.service.ts
src/endpoints/transactions/entities/transaction.ts
src/endpoints/transactions/transaction-action/transaction.action.service.ts

- use the same interpreter used for transaction action to also interpret scresult actions
- alternative "results" endpoint
- deprecate "sc-results" endpoints
- `/results`
- `/results/b2a82dbd563f6f597de4e45e1a4c09e93c93e6011a0f9a565f32bdbef27fb03e`
- `/accounts/erd1qqqqqqqqqqqqqpgqvc7gdl0p4s97guh498wgz75k8sav6sjfjlwqh679jy/results`
- `/accounts/erd1qqqqqqqqqqqqqpgqvc7gdl0p4s97guh498wgz75k8sav6sjfjlwqh679jy/results/b2a82dbd563f6f597de4e45e1a4c09e93c93e6011a0f9a565f32bdbef27fb03e`
- ... should also contain `action` attribute

Transaction action on smart contract results

---

src/endpoints/collections/collection.service.ts

- requesting /collections?size=1000&type=MetaESDT returns some collections as NonFungibleESDT
- fetch collection type from elasticsearch
- `/collections/PANDAS-2c4369` should return type `MetaESDT`

Collection type bugfix

---

src/endpoints/transactions/transaction.price.service.ts
src/utils/extensions/date.extensions.ts

- Transactions older than 9 sept 2020 will not be able to fetch price from [data.elrond.com](http://data.elrond.com/), thus logging an error internally
- do not fetch price for transaction older than 10 sept 2020
- `/transactions/63efdb5e1ccea744fe3bfe7746b56e641e0dee9e0171fa62bc5d91a205051011` should not log internal error regarding price fetcher

Old transaction price error

---

src/endpoints/collections/collection.service.ts

- Type is incorrectly fetched for collection details
- Fetch collection type from ES for collection details
- `/collections/PANDAS-2c4369` should have type `MetaESDT`

Fetch collection type from ES

---

config/config.e2e-mocked.mainnet.yaml
src/test/integration/controllers/accounts.controller.e2e-spec.ts

-  accounts.controller.e2e-spec.ts file contains certain tests whose endpoints have changed especially for /accounts/:address/sc-result ->  /accounts/:address/results
-  update integration tests for /results endpoint
- run integration test accounts.controller.e2e-spec.ts and all test cases must pass

fix /results endpoint e2e

---

src/endpoints/esdt/esdt.service.ts

- If dex service is down, tokens page on explorer will not show tokens
- Show tokens without dex service infos, like price and market cap
- Check if /tokens retrieves same tokens (without price and marketCap) if dex service is unavailable

Surround mex tokens prices fetching

---

src/endpoints/mex/mex.pair.service.ts
src/endpoints/mex/mex.token.service.ts
src/endpoints/nfts/nft.service.ts

- If somehow the query of getting the prices from maiar.exchange fails, the API should continue to operate normally
- perform various checks when fetching mex prices
- `/accounts/erd194m3jf6tzg4kwq2u46h7qd207jyh5r4vd6pw2r4f9qdvguzzytfspw7xst/nfts?withOwner=true&withSupply=true&from=0&size=10&hasUris=true&isWhitelistedStorage=true&source=elastic&withMetadata=true&includeFlagged=true` should return 1 element

Nft price fix

---

src/common/elastic/entities/elastic.query.ts
src/endpoints/accounts/account.controller.ts
src/endpoints/collections/collection.controller.ts
src/endpoints/collections/collection.service.ts
src/endpoints/collections/entities/collection.filter.ts
src/test/integration/collections.e2e-spec.ts
src/utils/pipes/parse.optional.enum.array.pipe.ts

- Possibility to filter by multiple types in global collections & account collections
- `/collections?type=SemiFungibleESDT,MetaESDT` should return multiple results
- `/accounts/erd1gkn5eppdkrkpyaq852vkgkqudg62qmsfy4nvdyj9w07eed2nmkdq9rgrk5/collections?type=SemiFungibleESDT,MetaESDT` should return multiple values
- `/accounts/erd1gkn5eppdkrkpyaq852vkgkqudg62qmsfy4nvdyj9w07eed2nmkdq9rgrk5/roles/collections?type=SemiFungibleESDT,MetaESDT` should return multiple values

Filter collections by multiple types

---

src/endpoints/nfttags/entities/tag.ts
src/endpoints/nfttags/tag.service.ts
src/test/integration/nft.tag.e2e-spec.ts

- Tag names appear as base64
- encode / decode tag so that it appears human readable in the request / response
- `/tags` should return human readable `tag` attributes
- `/tags/elrond` should return tag `elrond`

Fix tags representation

---

src/endpoints/nfts/nft.controller.ts

- Use identifier stored in ES when fetching thumbnail from persistence service 
- `/nfts/ogv-eca1e9-0160/thumbnail` should return its thumbnail and not default

Apply casing fix when fetching thumbnail

---

package-lock.json
src/common/elastic/elastic.service.ts
src/common/elastic/entities/elastic.query.ts
src/endpoints/nfts/nft.service.ts
src/endpoints/transactions/transaction.controller.ts
src/endpoints/transactions/transaction.service.ts
src/endpoints/transfers/transfer.service.ts
src/test/integration/controllers/accounts.controller.e2e-spec.ts
src/test/unit/utils/elastic.query.spec.ts

- When filtering in account transactions by receiver, we get a larger number than the count of all account transactions
- Do not add to should conditions supplemental receiver filter
- Refactor transaction query logic
- `/accounts/erd14cl7qlkeyktlqy0hqk3jmk5xw0584grrmh93z5gecr8l6lu6f7dsva0pr8/transactions/count?receiver=erd14cl7qlkeyktlqy0hqk3jmk5xw0584grrmh93z5gecr8l6lu6f7dsva0pr8` should return ~239
- `/transactions/count?receiver=erd14cl7qlkeyktlqy0hqk3jmk5xw0584grrmh93z5gecr8l6lu6f7dsva0pr8` should return 239

Fix transactions condition & ElasticQuery refactoring

---

src/endpoints/esdt/esdt.address.service.ts

- Remove legacy code
- filter account NFTs by type by querying ES
- make sure account nfts filtered by type goes to ES and not gateway

Remove NFT type filter from gateway

---

src/endpoints/collections/collection.service.ts
src/test/integration/collections.e2e-spec.ts

- Search address collection was not working correctly
- Add wildcard search condition
Before changes:
- accounts/erd126y66ear20cdskrdky0kpzr9agjul7pcut7ktlr6p0eu8syxhvrq0gsqdj/collections?search=MEDAL-ae074f  -> returned [ ]
After changes:
- accounts/erd126y66ear20cdskrdky0kpzr9agjul7pcut7ktlr6p0eu8syxhvrq0gsqdj/collections?search=MEDAL-ae074f -> should return collection details

Wildcard collection search

---

src/endpoints/collections/collection.controller.ts
src/endpoints/collections/collection.service.ts

- There was no collection not found condition for endpoints:
- /collections/:collection/nfts/count
- /collections/:collection/nfts  
- Add condition to verify if collection exist
-  /collections/Test/nfts -> should return 404 instead of []
- /collections/Test/nfts/count -> should return 404 instead of 0

Add 404 status code for collections endpoint

---

src/decorators/no.auth.ts
src/endpoints/health-check/health.check.controller.ts
src/utils/guards/jwt.authenticate.global.guard.ts
src/utils/guards/jwt.authenticate.guard.ts
src/utils/guards/native.auth.guard.ts

- support for NoAuth decorator
- activate auth flag in config (`api.auth: true`), then make sure the `/hello` route works, while all other endpoints (e.g. `/accounts` throw ForbiddenException)

NoAuth decorator

---

src/common/caching/entities/cache.info.ts
src/crons/cache.warmer/cache.warmer.service.ts
src/endpoints/delegation.legacy/delegation.legacy.service.ts

- Use caching for `/delegation-legacy` endpoint
- `/delegation-legacy` must always return from cache
- `delegationLegacy` cache key must be refreshed every minute

delegation legacy endpoint caching

---

src/common/rabbitmq/rabbitmq.nft.consumer.ts

- Breaking change occurred on the go-notifier node to also notify blocks with no events
- handle null events
- No `An unhandled error occurred when consuming events` error message should not appear when the notifier sends blocks with null events attribute

Fix rabbitmq logs and events handler

---

src/endpoints/transactions/transaction.controller.ts

- support for filtering by function in transaction count
- `/transactions/count?function=unDelegate` should return ~400.000

Filter by function in transaction count

---

package-lock.json
package.json
src/common/api-config/api.config.service.ts
src/endpoints/accounts/account.controller.ts
src/endpoints/esdt/esdt.service.ts
src/endpoints/nfts/entities/nft.filter.ts
src/endpoints/nfts/entities/nft.ts
src/endpoints/nfts/nft.controller.ts
src/endpoints/nfts/nft.service.ts
src/endpoints/transfers/transfer.service.ts
src/test/data/esdt/nft/nft.example.ts
src/test/integration/accounts.e2e-spec.ts
src/test/integration/nft.e2e-spec.ts
src/test/integration/process.nfts.e2e-spec.ts
src/test/jest-e2e.json
src/test/unit/utils/elastic.query.spec.ts

- added `score`, `rank`, `isNsfw` attributes to nft list & details
- calculate `isNsfw` attribute based on the nsfw score and a threshold set in the config
- extract extra NFT attributes based on a config flag to avoid unnecessary round-trips where this is not used
- `/nfts` should return `score`, `rank`, `isNsfw` where appropriate
- `/nfts/:identifier` should return `score`, `rank`, `isNsfw` where appropriate
- `/accounts/:account/nfts` should return `score`, `rank`, `isNsfw` where appropriate
- `/accounts/:account/nfts/:identifier` should return `score`, `rank`, `isNsfw` where appropriate
- `/nfts?isNsfw=true/false` should return correctly interpreted results
- `/nfts/count?isNsfw=true/false` should return correctly according to what was indexed

Add support for nft service managed fields

---

src/endpoints/mex/entities/mex.pair.type.ts
src/endpoints/mex/mex.pair.service.ts

- Support for unlisted mex pair type
- When refreshing mex pairs, do not log error `Unsupported pair type 'Unlisted'`

Support for unlisted mex pairs

---

src/endpoints/nfts/nft.service.ts

- 500 Internal server error occurs when fetching > 1024 account NFTs
- fetch by identifiers split into 1024 size chunks
- `/accounts/erd1qqqqqqqqqqqqqpgqh438d42h9ltlqgpmjxc3srxafnx383n5kagq6hynlu/nfts?from=0&size=1025&hasUris=true&collection=REALM-579543` should return 200 success
Thanks to @SkullElf (Telegram) for reporting this

Fix account nfts 1024 size limitation

---

src/endpoints/network/entities/about.ts
src/endpoints/network/network.service.ts

- Provide version information in about endpoint
- `/about` should include `version` field in the following way:
- `<tag>` if current commit hash matches exactly a tag
- `<tag>-next` if current commit hash doesn't match a tag. Tag should be the last one

Version in about endpoint

---

src/common/keybase/keybase.module.ts
src/common/keybase/keybase.service.ts

- Identities not shown in explorer for testnet & devnet providers
- Extend keybase regex to match devnet & testnet identities
- Start a testnet or devnet instance and check if identities appear for providers and nodes
- Start a mainnet instance and check if identities are the same

Network regex for keybase identities

---

src/endpoints/nfts/nft.service.ts

- adjust attribute names for rank & score to the new ones
- `/nfts/ULTRAS-3875ff-025d` should contain `score` & `rank`

Adjust rarity field names

---

config/config.devnet.yaml
config/config.mainnet.yaml
config/config.testnet.yaml
package-lock.json
package.json
src/common/api-config/api.config.service.ts
src/common/api-config/erdnest.config.service.impl.ts
src/test/integration/api.config.e2e-spec.ts

- Validate any correctly emitted jwt, not only from a specified `accessAddress`, meaning that when the global authentication flag is activated, a jwt emitted from i.e. web wallet can be used without any issues
- when setting `api.auth: true`, any emitted jwt using the given secret is allowed

Removed support for accessAddress in jwt global authenticator

---

src/endpoints/tokens/token.transfer.service.ts

- Token properties were fetched incorrectly in case of non-esdt events
- do not fetch token properties for `transferValueOnly`, `writeLog` or `signalError`
- `/transactions?withOperations=true` should not attempt to load token properties for events `transferValueOnly`, `writeLog` or `signalError`
- when running command `KEYS esdt:*` in redis, keys containing tokens only should be returned, and not something like `esdt:\x00\x00\x00\x00\x00\x00\x00\x00\x05\x00\xc3\x93\xc2\xb2\xc2\x88(\xc3\x96 R\x12O\a\xc3\x9c\xc3\x95\x0e\xc3\x93\x1b\b%\xc3\xb6\x0e\xc3\xae\x15&`

Fix token properties fetching for non-ESDT events

---

src/interceptors/transaction.logging.interceptor.ts
src/main.ts

- Restore logging of transactions as before
- Transactions sent on the `POST /transaction/send` or `POST /transactions` endpoints should log tx details

Restore transaction logging

---

src/common/assets/assets.service.ts
src/common/assets/entities/account.assets.ts
src/crons/cache.warmer/cache.warmer.service.ts
src/endpoints/sc-results/entities/smart.contract.result.ts
src/endpoints/sc-results/scresult.controller.ts
src/endpoints/sc-results/scresult.module.ts
src/endpoints/sc-results/scresult.service.ts
src/endpoints/tokens/token.transfer.service.ts
src/endpoints/transactions/entities/transaction.log.event.ts
src/endpoints/transactions/entities/transaction.log.ts
src/endpoints/transactions/entities/transaction.operation.ts
src/endpoints/transactions/entities/transaction.ts
src/endpoints/transactions/transaction.module.ts
src/endpoints/transactions/transaction.service.ts
src/endpoints/transfers/transfer.module.ts
src/endpoints/transfers/transfer.service.ts
src/test/unit/utils/transaction.utils.spec.ts

- Provide assets wherever an address is returned in the transaction list & details
- `/transactions` should return `senderAssets` & `receiverAssets`
- `/transactions/f09434ed2c399fd2d0ca76b2674ff88f8e55626c8052a3b6beca92235736e8fb` should return assets for receiver, results, operations, logs

Account assets for transaction

---

src/endpoints/nfts/entities/media.mime.type.ts

- The API can't process NFT thumbnails with webp file type because it isn't supported.
- Add image/webp file type in in supported mime types enum
- Create an NFT and upload a webp image as NFT asset
- Check if thumbnail is generated for your NFT

add support for webp image type for NFTs

---

src/endpoints/collections/collection.service.ts
src/endpoints/nfts/nft.service.ts
src/endpoints/tokens/token.service.ts
src/test/data/transactions/transactions.with.logs.ts
src/test/integration/controllers/accounts.controller.e2e-spec.ts
src/test/integration/controllers/blocks.controller.e2e-spec.ts
src/test/integration/controllers/collections.controller.e2e-spec.ts
src/test/integration/controllers/dappconfig.controller.e2e-spec.ts
src/test/integration/controllers/delegation.controller.e2e-spec.ts
src/test/integration/controllers/health.check.controller.e2e-spec.ts
src/test/integration/controllers/identities.controller.e2e-spec.ts
src/test/integration/controllers/miniblocks.controller.e2e-spec.ts
src/test/integration/controllers/nfts.controller.e2e-spec.ts
src/test/integration/controllers/nodes.controller.e2e-spec.ts
src/test/integration/controllers/providers.controller.e2e-spec.ts
src/test/integration/controllers/rounds.controller.e2e-spec.ts
src/test/integration/controllers/sc-results.controller.e2e-spec.ts
src/test/integration/controllers/shards.controller.e2e-spec.ts
src/test/integration/controllers/stake.controller.e2e-spec.ts
src/test/integration/controllers/tags.controller.e2e-spec.ts
src/test/integration/controllers/tokens.controller.e2e-spec.ts
src/test/integration/controllers/transactions.controller.e2e-spec.ts
src/test/integration/controllers/username.controller.e2e-spec.ts
src/test/integration/controllers/waiting-list.controller.e2e-spec.ts
src/utils/token.utils.ts

- NFT validation for route accounts/:account/nfts/:nft was missing
- accounts/erd1qqqqqqqqqqqqqpgq6wegs2xkypfpync8mn2sa5cmpqjlvrhwz5nqgepyg8/nfts/ALIEN-a499ab03e8  -> returned 500 Internal Server
- Add isNft method to verify if identifier is in right format
-  accounts/erd1qqqqqqqqqqqqqpgq6wegs2xkypfpync8mn2sa5cmpqjlvrhwz5nqgepyg8/nfts/ALIEN-a499ab03e8 -> should return 404 Bad Request with message `Token for given account not found`

Account nft validation

---

src/endpoints/mex/mex.pair.service.ts

- Add support for experimental jungle pairs
- `/mex/pairs` should return `PROTEO-WEGLD` and `PROTEO-USDC` pairs
- `/mex/tokens` should return `PROTEO`

Support for experimental jungle pairs

---

src/interceptors/transaction.logging.interceptor.ts

- Extract `X-Forwarded-For` and `X-Real-Ip` headers from request first, in order to extract the real ip
- Perform swap, look at transaction logs and find the actual ip where the request was performed from

Log real ip for transactions

---

src/endpoints/tokens/token.service.ts

- Token roles and address roles cause caching issue since address specific roles delete the address from the payload
- Perform a clone before returning address-specific roles
- make sure `indexer-v3` flag is set to false
- `/tokens/MEX-455c57/roles` should return all roles with address
- `/tokens/MEX-455c57/roles/erd1qqqqqqqqqqqqqpgqjpt0qqgsrdhp2xqygpjtfrpwf76f9nvg2jpsg4q7th` should return address-specific roles without address in payload
- `/tokens/MEX-455c57/roles` should return again all roles with address. The bug was manifesting itself that the address was missing in the case of the roles for the address `erd1qqqqqqqqqqqqqpgqjpt0qqgsrdhp2xqygpjtfrpwf76f9nvg2jpsg4q7th`

Fix token roles caching issue

---

src/common/assets/assets.service.ts

- Removed "Shard" from DNS contract label
- `/accounts/erd1qqqqqqqqqqqqqpgqez3jrxx3krhncmzhmzf8ksnjvmt0x6vrqreqvees8p` should return label `Elrond DNS: Contract Shard 242`

Removed "Shard" from DNS contract label

---

src/common/api-config/api.config.service.ts
src/common/gateway/gateway.service.ts

- Support for alternative gateway that contains only state, not historical information
- Possibility to define light gateway url, backwards compatible
- Target lighter gateway for some gateway-related requests
- vm queries & address details should target light gatway

support for light gateway urls

---

package-lock.json
package.json
src/common/locked-asset/locked-asset.service.ts
src/endpoints/accounts/account.controller.ts
src/endpoints/collections/collection.controller.ts
src/endpoints/collections/collection.service.ts
src/endpoints/esdt/esdt.address.service.ts
src/endpoints/esdt/esdt.service.ts
src/endpoints/nfts/nft.controller.ts
src/endpoints/nfts/nft.extendedattributes.service.ts
src/endpoints/nfts/nft.service.ts
src/endpoints/tokens/token.controller.ts
src/endpoints/tokens/token.service.ts
src/queue.worker/nft.worker/queue/job-services/assets/nft.asset.service.ts
src/queue.worker/nft.worker/queue/job-services/media/nft.media.service.ts
src/queue.worker/nft.worker/queue/job-services/thumbnails/nft.thumbnail.service.ts
src/test/unit/utils/token.utils.spec.ts
src/test/unit/utils/tokens.utils.spec.ts
src/utils/token.helpers.ts

- Improved validation for token, nft, collection endpoints
- Implemented token, nft, collection pipes
- Renamed TokenUtils to TokenHelpers
- Use TokenUtils from erdnest
- all endpoints using token, collection or nft identifier should be validated using pipes

Integrate Token Validator pipes from erdnest

---

src/endpoints/nfts/nft.controller.ts
src/endpoints/tokens/token.controller.ts

- NFT collection filter validation missing
- Token identifier filter validation missing
-  Add validation pipes
- tokens/MEX-455c57/accounts/count -> should return all token accounts count
- tokens/MEX455c57/accounts/count -> should return bad request `Invalid token identifier`

add nft collection/tokens validation identifier

---

src/endpoints/transactions/transaction.service.ts

- Provide assets information also in the case of actual NFTTransfer / MultiESDTNFTTransfer receiver
- `/transactions/8cf191a259cbd29775aa85055e6c33241c9a7a5cc25872ab60aacf1aa936338f` should provide `action.arguments.receiverAssets`

Receiver assets in transaction action receiver

---

package-lock.json
package.json
src/queue.worker/nft.worker/nft.worker.module.ts
src/queue.worker/nft.worker/queue/job-services/media/nft.media.module.ts
src/queue.worker/nft.worker/queue/job-services/media/nft.media.service.ts
src/queue.worker/nft.worker/queue/job-services/metadata/nft.metadata.module.ts
src/queue.worker/nft.worker/queue/job-services/metadata/nft.metadata.service.ts

- It took up to 10 minutes for media & metadata to appear, although they were processed in a few seconds
- After saving media / metadata, also trigger a cache invalidation to refresh the value in the local cache of the instances
- While minting a new NFT, for a few seconds default media should be returned, then the actual media should appear

Proactively refresh nft media & metadata after processing

---

src/queue.worker/nft.worker/queue/job-services/metadata/nft.metadata.service.ts
src/queue.worker/nft.worker/queue/nft.queue.controller.ts

- No need to delete metadata from database since on set the value is updated
- Just set metadata on refresh
- Create a new NFT, check if metadata is returned
- Trigger a force refresh on metadata

Update NFT metadata on refresh

---

src/queue.worker/nft.worker/nft.worker.module.ts
src/queue.worker/nft.worker/nft.worker.service.ts
src/utils/token.helpers.ts

- Nft worker will never considerate that NFT needs processing if it doesn't have media
- Check if NFT has default media, if it has then needs processing
- Create an NFT and do not trigger process on NFT create
- Tigger NFT process manually or check using cron if processing is triggered

Nft media needs processing

---

config/config.e2e-mocked.mainnet.yaml
config/config.e2e.mainnet.yaml
config/config.mainnet.yaml
src/common/api-config/api.config.service.ts
src/common/indexer/elastic/elastic.indexer.service.ts
src/endpoints/accounts/account.service.ts
src/endpoints/transactions/transaction.get.service.ts
src/test/integration/accounts.e2e-spec.ts
src/test/integration/api.config.e2e-spec.ts

- It's been a long time since we had the `useLegacyElastic` flag and we have to make it deprecated
- Removed `useLegacyElastic` flag

Drop support for legacy elastic

---

src/endpoints/transactions/transaction.service.ts

- errors were not displayed when malformed transactions were sent
- return actual errors when sending transactions
- call `POST /transactions` with a malformed transaction. It should return an error message

Transaction send return actual errors

---

src/endpoints/transactions/transaction.controller.ts
src/endpoints/transactions/transaction.get.service.ts
src/test/integration/transaction.get.e2e-spec.ts

- If Elastic is down the load is redirected to gateway
- Fallback to gateway only if transaction is not found in elastic 
- Check fallback if elastic is down
- Check if a transaction is returned if exists only on gateway

get transaction from gateway only if not found in elastic

---

src/endpoints/accounts/account.controller.ts
src/endpoints/collections/collection.controller.ts
src/endpoints/nfts/entities/nft.query.options.ts
src/endpoints/nfts/nft.controller.ts
src/endpoints/nfts/nft.service.ts

- NFTs scam info processing is CPU intensive
- add a flag that triggers NFTs scam info processing
- `/nfts` - does not return any scam info
- `/nfts?computeScamInfo=true` - scam info should appear for NFTs that are scam

Add `computeScamInfo` flag for NFT list

---

src/common/plugins/plugin.service.ts
src/endpoints/accounts/account.controller.ts
src/endpoints/nfts/entities/nft.query.options.ts
src/endpoints/tokens/token.controller.ts
src/endpoints/transactions/entities/transactions.query.options.ts
src/endpoints/transactions/transaction.controller.ts
src/endpoints/transactions/transaction.service.ts
src/endpoints/transfers/transfer.service.ts
src/test/integration/controllers/nfts.controller.e2e-spec.ts

- Transaction list uses a lot of CPU to determine whether scam or not
- scamInfo appears automatically for <= 100 entries and not permitted over 100 entries
- `/transactions?size=100` should compute scam info
- `/transactions?size=101` should not compute scam info
- `/transactions?withScamInfo=true&size=101` should throw error

withScamInfo support for transactions

---

src/common/metrics/api.metrics.service.ts
src/interceptors/request.cpu.time.interceptor.ts
src/interceptors/transaction.logging.interceptor.ts
src/main.ts
src/test/integration/controllers/nfts.controller.e2e-spec.ts

- CPU usage is difficult to correlate to api calls
- Created an interceptor to track cpu usage per api call
- Metrics for api call cpu usage
- metrics should export api_cpu_time

API call cpu usage metrics

---

src/queue.worker/nft.worker/queue/job-services/media/nft.media.service.ts
src/test/integration/controllers/nfts.controller.e2e-spec.ts
src/test/integration/services/nft.media.e2e-spec.ts

- No content size limit for NFT media
- Risk to restart processor instance when processing large media files
- Add a limit of 64MB for accepted media files
- Mint one NFT and add a large media file (> 64MB), media should not be processed
- Mint another NFT with a smaller media file, check if is processed

implement content size limit for NFT media

---

src/common/keybase/keybase.service.ts
src/endpoints/nfts/nft.service.ts
src/graphql/schema/schema.gql
src/test/integration/api/collections.api-spec.ts
src/test/integration/controllers/nfts.controller.e2e-spec.ts

- If LKMEX attributes are undefined, the server returns 500 internal server error
- try/catch around lkmex attribute decoding
- `/nfts/LKMEX-aab910-22e4de` should return details, although it doesn't have attributes

LKMEX unlock schedule error handling

---

src/utils/token.helpers.ts

- Support *.mypinata.cloud as supported whitelisted storage
- `/nfts?collection=SRB-61daf7` should all have `whitelistedStorage: true`

Support any mypinata.cloud url as whitelisted storage

---

src/queue.worker/nft.worker/queue/job-services/thumbnails/nft.thumbnail.service.ts

- Generated thumbnail don't include input image metadata
- Use same metadata flags for input & output images

include metadata from the input image in the output when generating thumbnail

---

src/endpoints/accounts/account.controller.ts
src/endpoints/collections/collection.controller.ts
src/endpoints/nfts/nft.controller.ts
src/endpoints/tokens/token.controller.ts
src/endpoints/transactions/transaction.controller.ts

-  https://github.com/ElrondNetwork/api.elrond.com/issues/804
- Make withScamInfo and computeScamInfo required:false
- start local api instance and go to localhost://3001 swagger and verify if withScamInfo and computeScamInfo parameters are not required

remove required parameters from swagger api

---

src/endpoints/tokens/token.service.ts
src/test/integration/services/tokens.e2e-spec.ts

- 
- 
- 
Sort locked accounts by balance descending
GET /tokens/RIDE-7d18e9/supply

Sort locked accounts by balance descending

---

src/common/keybase/keybase.service.ts
src/endpoints/mex/mex.token.service.ts

- Fix keybase regex
- Fix mex token fields issue
- Provider `erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqpqhllllsqdxn4p` should be fetched from keybase (regex should match)
- After calling `/mex/tokens?fields=id`, `/mex/tokens` should return all fields and not the filtered ones

Fix keybase & mex token fields issue

---

src/endpoints/tokens/token.transfer.service.ts

- Check event for null when decoding transaction
- `/transactions?withScResults=true&withOperations=true&withLogs=true&size=50&hashes=d4e42a1f3378b01189926c2220e644d3f457299fe886f51b6ac04890f048ee2c` should not throw 500 Internal Server Error

Transaction log decoder fix

---

src/endpoints/rounds/round.controller.ts

-  remove query pagination from rounds/count and rounds/c
-  rounds/count endpoint should return rounds count even without from and size filters
- rounds/c endpoint should return rounds count even without from and size filters

remove query pagination from rounds count endpoint

---

src/endpoints/nodes/node.service.ts

-  nodes?fullHistory=true&sort=validatorIgnoredSignatures&order=desc returns empty array
- remove sort condition from getFilteredNodes method
-  nodes?fullHistory=true&sort=validatorIgnoredSignatures&order=desc should return 25 nodes

Do not filter nodes when sorting

---

src/endpoints/accounts/account.controller.ts
src/test/integration/services/transactions.e2e-spec.ts

-  add function filter for accounts/:address/transactions and accounts/:address/transfers
-  accounts/erd1c9lcvjs0qhdhfk7jn8hsshrcfxmq0ulk2ea3mxu9xh79l8n646gscchq6x/transfers?function=sendOffer -> all account transactions should contain function: "sendOffer" 
-  accounts/erd1c9lcvjs0qhdhfk7jn8hsshrcfxmq0ulk2ea3mxu9xh79l8n646gscchq6x/transfers/count?function=sendOffer -> should return ~9

 function filter in account transactions transfers endpoint

---

package-lock.json
package.json
src/common/keybase/keybase.service.ts

- keybase.pub slow & unreliable; cache warmer failing often, most recent providers were not updated
- randomize providers to be fetched from keybase.pub
- apply retry strategy with backoff
- Start with `fastWarm` setting activated, then make sure all providers are properly loaded from keybase.pub

Randomized & resilient keybase.pub fetching

---

config/config.devnet.yaml
config/config.mainnet.yaml
config/config.testnet.yaml
package-lock.json
package.json
src/common/api-config/api.config.service.ts
src/main.ts

- The underlying elasticsearch instance can be configured to have a maximum window size greater than 10000 (e.g. 50000) and our interceptors do not allow larger windows
- Allow a configurable value for max window size in the pagination interceptor
- set the `indexer.maxPagination` value to 5000
- GET `/accounts?size=5001` should throw error
- GET `/accounts?from=1000&size=5000` should also throw error

Customizable ES max window size

---

src/endpoints/transfers/transfer.service.ts

- Operation might not have `type` defined at all for certain SmartContractResults
- invert logic for verifying `type` in operation from ES result
-`/tokens/WEGLD-bd4d79/transfers?size=1000&receiver=erd1tsuu9jf4pn8rsus9knrw4ju39ukyp247gug8gahsfdjzdzewd0eqcwgl30&before=1642373550&after=1642373550` should have type `SmartContractResult`

invert type verification for operation

---

src/endpoints/accounts/account.controller.ts
src/endpoints/esdt/esdt.address.service.ts

- When you search NFTs or SFTs by identifiers on an account than has never been used, the API respond error 500.
It should respond an empty array as when you make a search by collections or when you make this search on an used account but whithout the NFT searched.
- Handle gateway error from controller accounts  level 
- Add try/catch block
accounts/erd1fex4n4qus76efz8cpjm734dfdyuw28m8ry3al6xyd7cmfml9259qq8l2y5/nfts?identifiers=AERMES-ac9886-0ad9 -> should return [] because this wallet does not contains AERMES-ac9886-0ad9  -> should return 500 Internal Server Error
-  accounts/erd1fex4n4qus76efz8cpjm734dfdyuw28m8ry3al6xyd7cmfml9259qq8l2y5/nfts?identifiers=AERMES-ac9886-0ad9 -> should return [] because this wallet does not contains AERMES-ac9886-0ad9 
- …

 add try/catch block to handle gateway "account was not found at block"

---

src/endpoints/accounts/account.service.ts
src/endpoints/network/network.service.ts

- Locked tokens had to be manually updated every time the team vesting account had outgoing transactions
- Decrease circulating supply with a dynamically read value from the team vesting account
- `/economics` should return ~23.6 mil. as circulating supply

Updated locked tokens amount to be read dynamically

---

src/endpoints/nodes/node.service.ts

- Some nodes do not have the online attribute at all
- Absence of online attribute should set it to `false`
- `/nodes/count` should be `/nodes/count?online=true` + `/nodes/count?online=false`

Set node offline if no online property set

---

src/endpoints/collections/collection.controller.ts
src/endpoints/nfts/nft.controller.ts

- Add nfts/:identifier/transactions endpoint to receive transactions details for a specific NFT .
NFT Transactions: 
-  nfts/MKU-b945e6-14/transactions -> should return 2 transactions details for NFT with identifier  MKU-b945e6-14.
-  nfts/MKU-b945e6-14/transactions/count -> should return transaction count =  2
Collection Transactions:
- collections/MKU-b945e6/transactions -> should return 25 transactions details for collection MKU-b945e6
- collections/MKU-b945e6/transactions/count -> should return collection transactions count = 74
- collections/MKU-b145e6/transactions/count -> should return 404 "Collection not found"

 transactions searchable by collection/nft

---

src/common/gateway/entities/gateway.component.request.ts
src/endpoints/nfts/entities/nft.ts
src/endpoints/nfts/nft.service.ts
src/graphql/schema/schema.gql

- Set `isTransferAffected` boolean attribute on some NFT-related endpoints so that front-ends can temporarily react to it
- `/nfts/CATSFAM-46c28f-0211` should return `isTransferAffected: true`

NFT apply transfer affected attribute

---

src/endpoints/nfts/nft.service.ts
src/test/integration/services/nft.e2e-spec.ts

- Do not apply transfer affected on multiple nfts endpoint
- `/accounts/:account/nfts` should not apply `isTransferAffected` attribute

Do not apply transfer affected on multiple nfts endpoint

---

package-lock.json
package.json
src/endpoints/transactions/transaction.controller.ts
src/test/integration/controllers/transactions.controller.e2e-spec.ts

- Transactions sender filter wasn't able to retrieve transactions from metachain 
- Add new validation pipe to sender filter
-  transactions/count?sender=4294967295 -> should return all transactions where sender is 4294967295 ( metachain )
-  transactions?sender=erd1a5q433u4a55qdfjkkslw9fa7h4pyvgn0t5zquws59t82tww2gnrsk5dern -> should return all transactions where sender is erd1a5q433u4a55qdfjkkslw9fa7h4pyvgn0t5zquws59t82tww2gnrsk5dern
- transactions/count?sender=4294967295 -> should return total transactions count for sender 4294967295 (metachain)
- transactions/c?sender=4294967295 -> should return total transactions count for sender 4294967295 (metachain)
- transactions?from=0&size=10000&receiver=erd1uuqwdgg66phtutjzfktcy0muhcaqselvnl4fpgtg6429t8d6hh5quzmjus&sender=4294967295

transaction filter allow sender receiver to be metachain

---

src/common/indexer/elastic/elastic.indexer.helper.ts
src/common/indexer/entities/collection.trait.summary.attribute.ts
src/common/indexer/entities/collection.trait.summary.ts
src/common/indexer/entities/collection.ts
src/endpoints/collections/collection.controller.ts
src/endpoints/collections/collection.service.ts
src/endpoints/collections/entities/collection.trait.attribute.ts
src/endpoints/collections/entities/collection.trait.ts
src/endpoints/collections/entities/nft.collection.ts
src/graphql/schema/schema.gql
src/test/integration/controllers/collections.controller.e2e-spec.ts

- Filter collection NFTs by trait as well
- use base64 encoding for values to be searched
- `/collections/MAFIA-7c0abf/nfts?traits=Backgrounds:Green%20Bills;Clothes:Prisoneer%20Shirt` should return 2 NFTs
- `/collections/MAFIA-7c0abf/nfts/count?traits=Backgrounds:Green%20Bills;Clothes:Prisoneer%20Shirt` should return `2`

Collection NFTs trait filter

---

src/endpoints/nfts/entities/media.mime.type.ts
src/endpoints/nfts/nft.service.ts
src/queue.worker/nft.worker/queue/job-services/media/entities/is.content.accepted.result.ts
src/queue.worker/nft.worker/queue/job-services/media/nft.media.service.ts
src/queue.worker/nft.worker/queue/nft.queue.controller.ts
src/test/integration/services/nft.media.e2e-spec.ts

- if content size exceeded, still generate media entries
- add support for `image/svg` & `image/svg+xml` content types
- triggering nft media refresh for `TOERMALIJN-b9b9bc-01` should create media entries & default thumbnail
- triggering nft media refresh for `SFTFAN-0e36bc-01` should create media entries because it should now support content type `image/svg+xml`

Nft media processing improvements

---

src/test/integration/services/nft.e2e-spec.ts

-  New filters was added to NftFilter entity that enable nonce filtering  by nonce before and after a value
-  add in nft.e2e-spec.ts new spec test 
- command: npm run test:e2e nft.e2e-spec.ts

 add nonce after nonce before spec tests

---

src/test/integration/controllers/proxy.controller.e2e-spec.ts
src/test/integration/services/collections.e2e-spec.ts

-  Collection service spec test was disabled and several tests were missing + add more mocks
-  Refactor all collections.e2e-spec.ts tests
- Add new proxy controller spec test
- command : collections.e2e-spec.ts
- command: proxy.controller.e2e-spec.ts

 add collections service / proxy controller spec tests

---

src/endpoints/tokens/token.controller.ts

- The information from token roles endpoints is already contained in token details
- Mark token roles endpoints as deprecated
- `/token/:identifier/roles` should be marked as deprecated in swaggerdoc
- `/token/:identifier/roles/:address` should be marked as deprecated in swaggerdoc

Mark token roles endpoints as deprecated

---

src/endpoints/transactions/entities/transaction.ts
src/endpoints/transactions/entities/transaction.type.ts
src/graphql/entities/graphql.services.module.ts
src/graphql/entities/transfers/transfers.input.ts
src/graphql/entities/transfers/transfers.module.ts
src/graphql/entities/transfers/transfers.query.ts
src/graphql/entities/transfers/transfers.resolver.ts
src/graphql/schema/schema.gql

-  Add Transfers Query Graphql
- Create transfers graphql query - transfers & transfersCount
-  `graphql: true`
-  `indexer-v3: true`
Run query:
```
query{
transfers(input:{
}){
txHash
gasLimit
gasPrice
gasUsed
miniBlockHash
nonce
receiverAddress
receiverShard
round
senderAddress
senderShard
signature
status
value
fee
timestamp
data
type
originalTxHash
}
}
```

add transfers query

---

src/graphql/entities/smart.contract.result/smart.contract.result.query.ts
src/graphql/schema/schema.gql
src/test/integration/graphql/smart.contract.result.graph-spec.ts

- Rename smart contract queries (scResults => results)
-  run smart.contract.graph-e2e-spec.ts tests

SERVICES-795 rename scResults queries

---

src/endpoints/nfts/entities/nft.ts
src/endpoints/nfts/nft.service.ts
src/graphql/schema/schema.gql
src/test/data/esdt/nft/nft.example.ts
src/test/integration/graphql/nfts.graph-spec.ts
src/test/integration/services/nft.e2e-spec.ts
src/test/integration/services/process.nfts.e2e-spec.ts

- Remove isTransferAffected flag for nfts
- `/nfts/EGIRL-443b95-0647` should not have `isTransferAffected` flag set

Remove isTransferAffected flag for nfts

---

src/common/assets/entities/nft.rank.algorithm.ts
src/common/assets/entities/token.assets.ts
src/common/indexer/elastic/elastic.indexer.service.ts
src/endpoints/collections/collection.controller.ts
src/endpoints/collections/entities/sort.collection.nfts.ts
src/endpoints/nfts/entities/nft.filter.ts
src/endpoints/nfts/entities/nft.rarities.ts
src/endpoints/nfts/entities/nft.rarity.ts
src/endpoints/nfts/entities/nft.ts
src/endpoints/nfts/nft.service.ts
src/graphql/schema/schema.gql
src/test/data/esdt/nft/nft.example.ts
src/test/integration/services/nft.e2e-spec.ts
src/test/integration/services/process.nfts.e2e-spec.ts

- Read rarities according to all supported algorithms from ES
- Support for sorting nfts by rank, timestamp, nonce
- `/collections/TEST-b0fe13/nfts` should return `rank`, `score` but also `rarites` with all ranks & scores from other algorithms
- `/collections/TEST-b0fe13/nfts?sort=rank` should display the records sorted by rank ascending
- `/collections/TEST-b0fe13/nfts?sort=rank&order=desc` should display the records sorted by rank descending
- `/collections/TEST-b0fe13/nfts?sort=nonce` should display the records sorted by rank ascending
- `/collections/TEST-b0fe13/nfts?sort=nonce&order=desc` should display the records sorted by rank descending
- `/collections/TEST-b0fe13/nfts?sort=timestamp` should display the records sorted by rank ascending
- …

Nft rarities ES mappings

---

src/common/indexer/elastic/elastic.indexer.helper.ts
src/endpoints/transactions/entities/transaction.filter.ts
src/endpoints/transfers/transfer.controller.ts

- Add multiple sender addresses 
Senders filter with one address
- `transfers?sender=erd1vtlpm6sxxvmgt43ldsrpswjrfcsudmradylpxn9jkp66ra3rkz4qruzvfw` -> should return a list of 25 transfers and all senders should be `erd1vtlpm6sxxvmgt43ldsrpswjrfcsudmradylpxn9jkp66ra3rkz4qruzvfw`
Senders filter with multiple addresses
- `transfers?sender=erd1vtlpm6sxxvmgt43ldsrpswjrfcsudmradylpxn9jkp66ra3rkz4qruzvfw,erd1v4ms58e22zjcp08suzqgm9ajmumwxcy4hfkdc23gvynnegjdflmsj6gmaq` -> should return a list of 25 transfers and all senders should contains `erd1vtlpm6sxxvmgt43ldsrpswjrfcsudmradylpxn9jkp66ra3rkz4qruzvfw` and `erd1v4ms58e22zjcp08suzqgm9ajmumwxcy4hfkdc23gvynnegjdflmsj6gmaq`

 add senders filter to tranfers

---

src/endpoints/identities/entities/stake.info.ts
src/endpoints/identities/identities.service.ts

- Decrease APR with a value proportional to the non-queued validators vs all validators
- `/identities/aurentum` should have APR closer to 10%, rather than the existing 11.x%

Identity apr take queued nodes into account

---

src/endpoints/accounts/account.controller.ts

- Add support for multiple senders in account transfers endpoint
- `accounts/erd1l453hd0gt5gzdp7czpuall8ggt2dcv5zwmfdf3sd3lguxseux2fsmsgldz/transfers?sender=erd16h8vnd2x89cll66ezeclpvdf7kfzy44unr9x90gt6535u0rmr78svakp9r,erd1ttm5tlrvm7s6used9audyxwpwt6p55ef5h0wcakx7vew9fn207aqetn7u7` should return transfers associated with both accounts as sender

Add support for multiple senders in account transfers endpoint

---

src/crons/cache.warmer/cache.warmer.module.ts
src/queue.worker/nft.worker/queue/nft.queue.module.ts

- NFT cron was running with the `queue worker` condition, meaning there could have been multiple nft crons running at the same time, which is undesirable
- Run nft cron in the cache warmer module
- when setting cache warmer feature active, nft cron should work, otherwise it should not

Run nft cron in cache warmer

---

src/endpoints/tokens/token.service.ts
src/test/integration/controllers/tokens.controller.e2e-spec.ts
src/test/integration/services/tokens.e2e-spec.ts

- holoride roles endpoint was returning 404 not found
- When token has no accounts with roles, return empty array instead of returning 404
- `/tokens/RIDE-7d18e9/roles` should return `[]` (empty array)

Fix result when no token roles

---

src/endpoints/nfts/nft.service.ts

- Get nft supply only if SFT or MetaESDT
- the `/nfts/:identifier` endpoint should only call the internal get supply function if type is SFT / MetaESDT

Get nft supply only if SFT or MetaESDT

---

src/endpoints/collections/collection.service.ts
src/endpoints/collections/entities/nft.collection.ts
src/endpoints/tokens/entities/collection.roles.ts
src/graphql/schema/schema.gql
src/utils/token.helpers.ts

- Token canTransfer flag
- `/collections/LKASH-10bd00` should have `canTransfer: false`, while in the `roles` section for the addresses `erd1qqqqqqqqqqqqqpgqawujux7w60sjhm8xdx3n0ed8v9h7kpqu2jpsecw6ek` and `erd18mnsygujdglgj2xmnshqcegc7d0ye0gt8cyltq3xsle97ft0wnhsva0dhv` should have `canTransfer: true`

Token can transfer flag

---

src/endpoints/nfts/nft.extendedattributes.service.ts
src/test/integration/services/nft.extendedattributes.e2e-spec.ts

- When metadata failed to fetch, there was no indication for API consumers of what the underlying problem was
- When fetching NFT metadata fails, store inside the metadata directly the reason of failure
- reindex metadata for `CRSK-07ca98-252f`, `BLOKICOR01-3f4e24-028d`, `PLANT2EARN-981e2f-99` should fail and store error

Save metadata errors

---

src/endpoints/nfts/nft.service.ts
src/test/integration/controllers/nfts.controller.e2e-spec.ts
src/test/integration/services/nft.e2e-spec.ts

- when `withSupply` option was applied, account NonFungibleESDTs had the supply attribute applied
- Apply supply attribute only for SemiFungibleESDT and MetaESDT when `withSupply` option is enabled
`accounts/erd1yl6f7cq9gpuprwthxf0c2gsvmnuezwqkqmzf8e40u87t7592af7qpl05cv/nfts?withSupply=true&type=SemiFungibleESDT` -> all SFT tokens should have supply attribute applied
`accounts/erd1yl6f7cq9gpuprwthxf0c2gsvmnuezwqkqmzf8e40u87t7592af7qpl05cv/nfts?withSupply=true&type=NonFungibleESDT`-> all NFT tokens does not contain supply attribute
`accounts/erd1yl6f7cq9gpuprwthxf0c2gsvmnuezwqkqmzf8e40u87t7592af7qpl05cv/nfts?withSupply=true&type=MetaESDT` -> all MetaESDT tokens should have supply attribute applied
`accounts/erd1yl6f7cq9gpuprwthxf0c2gsvmnuezwqkqmzf8e40u87t7592af7qpl05cv/nfts?size=100` -> …

apply supply attribute to account/:account/nfts only for SemiFungibleEsdt and MetaEsdt

---

src/common/plugins/plugin.service.ts
src/endpoints/network/entities/about.ts
src/endpoints/network/network.module.ts
src/endpoints/network/network.service.ts
src/graphql/schema/schema.gql

- Return scam engine version in about endpoint
- handle `processAbout` function in plugin by setting `scamEngineVersion`, then see that information returned in the `/about` endpoint

Scam engine version in about endpoint

---

src/endpoints/dapp-config/dapp.config.controller.ts
src/endpoints/dapp-config/dapp.config.service.ts
src/graphql/entities/dapp.config/dapp.config.query.ts
src/test/integration/services/api.config.e2e-spec.ts
src/test/integration/services/dapp.config.e2e-spec.ts
src/test/integration/services/network.e2e-spec.ts

- use DappConfig type instead of any type
-  /dapp/config should return all dapp configuration 
-  npm run test:e2e dapp.*
-  npm run test:graphql dapp.*

use DappConfig type instead of any

---

package-lock.json
package.json
src/crons/cache.warmer/cache.warmer.service.ts

- Token assets extra info was refreshed too often, reaching the upper bound for number of active scrolls in ElasticSearch
- Run Token assets extra info invalidations every 10 minutes instead of 1 minute
- Update erdnest to latest version, which clears ES scrolls after they have been fully utilized
- Run Token assets extra info invalidations as often as possible, check whether ES scroll limit is reached (should not reach limit any more)

Token assets extra info cron fix

---

src/endpoints/collections/collection.controller.ts
src/endpoints/collections/collection.service.ts
src/endpoints/collections/entities/collection.logo.ts

- No collection endpoint was available to return PNG or SVG logo 
- Create endpoint that return from assets collection PNG or SVG logo
- collections/ASHEGLDD-ca7c13/logo/png -> should return collection PNG logo
- collections/ASHEGLDD-ca7c13/logo/svg -> should return collection SVG logo
- collections/ASHEGLDD-ca7c/logo/svg -> should throw error with `status code 400 ` and error `Bad Request`
- collections/PRIMO-8473d0/logo/svg -> should return `Assets Not Found `
- collections/PRIMO-8173d0/logo/svg -> should return `Collection not found`

thumbnail resolver for collection

---

src/common/gateway/gateway.service.ts
src/endpoints/accounts/account.controller.ts
src/endpoints/nfts/nft.service.ts
src/graphql/entities/account.detailed/account.detailed.resolver.ts
src/graphql/schema/schema.gql

- When fetching account NFT list or single NFT, even if a few fields are requested, the processing was until now still done for all of the fields. This process can be optimized by looking at the required fields and perform only the required extra data fetching
- Perform data fetching only for the fields that are actually requested
- `/accounts/:account/nfts?fields=:fields` should not fetch media, metadata, price, etc. Conversely, when fetching the fields where extra processing is required, the processing will be triggered and the fields will be returned
- `/accounts/:account/nfts/:nft?fields=:fields` should work exactly as above
- `/accounts/:account/nfts/:nft?extract=:field` should work exactly as above

Optimized account NFT fetching based on fields

---

src/endpoints/dapp-config/dapp.config.controller.ts
src/endpoints/dapp-config/dapp.config.service.ts
src/graphql/entities/dapp.config/dapp.config.query.ts

- Dapp config is pretty static and api calls are accessing the disk directly
- Fetch dapp config only once and keep it in memory
- Make sure the dapp config route does not access disk any more

Cached dapp config

---

src/endpoints/nfts/entities/nft.query.options.ts

- Scam info was computed even if `withScamInfo=false` parameter was set
- Improve heuristic for determining whether to load scamInfo or not based on the parameters
- `/nfts?collection=LOTTERY-7cae2f&withScamInfo=false` should not return `scamInfo` field

Do not compute scam info if withScamInfo parameter is false

---

src/endpoints/transactions/transaction.service.ts

- The wrong heuristic is checked when determining whether to fetch logs / scResults for transaction list
- Remove `hasScResults` flag for transactions with logs / scResults / operations
- `/transactions?receiver=erd1qqqqqqqqqqqqqpgq0tajepcazernwt74820t8ef7t28vjfgukp2sw239f3&function=migrateOldTokens&status=fail&size=10&withLogs=true` should return logs

Load operations even if no sc results

---

src/endpoints/transactions/transaction-action/recognizers/sc-calls/transaction.action.sc-calls.recognizer.service.ts

- Take into account `SaveKeyValue` function as self built-in function
- `/transactions/37774f4d5f545bfd95dbdef05d4ceedf8f0ddbb77348f5a99f46958c09936419` should have `action` of type `scCall`

Recognize SaveKeyValue function

---

src/endpoints/nodes/node.service.ts
src/test/integration/controllers/proxy.controller.e2e-spec.ts
src/test/integration/controllers/tokens.controller.e2e-spec.ts
src/test/integration/graphql/tokens.graph-spec.ts
src/test/integration/services/providers.e2e-spec.ts
src/test/integration/services/tokens.e2e-spec.ts

- Inactive observer nodes status was not reflected in node information
- Also, owner was not set for observer nodes
- Explicitly handle inactive status from validator statistics
- Resolve owner also for observer node type
- `/nodes/586c6642e1f5350d790c9b0067a4fd0f8a49e3c929143fb820634fb412a22bc5100a425bfb7ee269fa047466493cde0a048068ce11680b072b1b1463c65ac4e3ba82615a348cd9d490cc28b0c9ca7832f40a48af7fc0f75139d735b694d73298` should have status `inactive` and `owner` attribute set

Handle Inactive node status 

---

src/endpoints/esdt/esdt.address.service.ts

- the account collection roles endpoint did not return the ones where the account was only owner and had no special roles attached to it
- Push into the collectionWithRoles array regardless of whether the roles tag exists or not
- `/accounts/erd1wh9c0sjr2xn8hzf02lwwcr4jk2s84tat9ud2kaq6zr7xzpvl9l5q8awmex/roles/collections` should return, among others, the `NEWSFTCOLL-e8fbe1` collection

Account collection roles endpoint return also where owner

---

src/utils/cache.info.ts

- Token assets refreshed every 24h, meaning every change in assets repo would be reflected after a lot of time
- decrease ttl to one hour
- make sure the assets are refreshed after 1h when changed in redis

Token assets TTL fix

---

src/common/indexer/elastic/elastic.indexer.helper.ts
src/common/indexer/elastic/elastic.indexer.service.ts
src/endpoints/accounts/account.controller.ts
src/endpoints/transactions/entities/transaction.filter.ts
src/test/integration/services/transactions.e2e-spec.ts
src/test/integration/services/transfers.e2e-spec.ts

- Right now, there is no possibility to fetch the interactions between one account and another
- Add senderOrReceiver query parameter for /accounts/:address/transfers & /accounts/:address/transactions endpoints
- Add senderOrReceiver property to transactions/transfers filter
- Check if /accounts/:a1/transfers?senderOrReceiver=a2, return only the transactions between a1 and a2, same thing for accounts/:a1/transactions?senderOrReceiver=a2

account interactions with one address

---

package-lock.json
src/graphql/schema/schema.gql
src/main.ts
src/utils/jwt.or.native.auth.guard.ts

- When activating global auth, only legacy jwts were allowed
- Allow dual validation of tokens, both jwt and also native auth 
- Activate auth flag (`api.auth: true` in config), then perform request e.g. on the `/accounts` route with Authorization header using a native auth token

Auth setting allow native auth tokens

---

src/endpoints/providers/entities/delegation.data.ts
src/endpoints/providers/provider.service.ts
src/test/integration/services/providers.e2e-spec.ts

-  on providers route /providers, owner attributes is missing
-  add "owner" attribute
- /providers -> should return all providers details + owner attribute defined
- /prividers/:address -> should return all provider details + owner attribute defined

 add owner attribute for providers

---

src/endpoints/accounts/account.service.ts

- In order to optimize performance, herotags were not fetched for smart contract, although the protocol allows it
- since the number of smart contracts is relatively finite, we can allow fetching herotags for these as well
- verify whether herotags are loaded for smart contracts

Allow herotags for smart contracts as well

---

src/common/locked-asset/locked-asset.service.ts
src/endpoints/accounts/account.service.ts

- If xmex / lkmex ticker are empty for whatever reason, decoding is always attempted
- Add an extra check whether the ticker really exists before decoding
- Make sure mex settings are not loaded, then any token should not be attempted to be decoded as lkmex

Fix XMEX / LKMEX decoding error

---

config/config.e2e-mocked.mainnet.yaml
config/config.e2e.mainnet.yaml
config/config.mainnet.yaml
config/config.testnet.yaml
src/test/integration/services/transactions.e2e-spec.ts
src/test/integration/services/transfers.e2e-spec.ts
src/test/integration/services/username.e2e-spec.ts
src/test/integration/services/waiting.list.e2e-spec.ts

- with the transition to the new organization, xexchange contains a new url for graph requests 
- change xExchange URL in configs

 change xexchange url in configs

---

src/crons/cache.warmer/cache.warmer.service.ts

- Assets repository has > 125MB total, meaning it takes longer and longer to checkout
- Refresh token & account assets every 10 minutes
- Less network traffic overall should be performed by the cache warmer instance

Refresh token & account assets every 10 minutes

---

src/endpoints/transactions/entities/transaction.create.ts

While debugging the XOXNO API we discovered that the people using Web Wallet and Ledger were not able to send the signed TX to the blockchain via the API endpoint.
The issue we discovered was that the options field required at the protocol level in order to validate the signature of the Ledger was not sent to the Elrond Proxy. 
Add the options field so in case the TX body sent has the options value set this one will be included in the final body.
Try to send a TX made via Web Wallet + Ledger and console log the body before is sent to the Elrond Gateway/Proxy

add options to TransactionCreate

---

src/common/indexer/elastic/elastic.indexer.helper.ts

- Fix account nfts route filter by multiple types if the address is smart contract
- `/accounts/erd1qqqqqqqqqqqqqpgqqt3yvus3er8jd2knhfxcnhfhzpjx7m8w46lqd4cncw/nfts?type=NonFungibleESDT,MetaESDT` should return multiple nfts and not an empty array

Fix account NFTs type filter

---

src/common/api-config/api.config.service.ts
src/common/indexer/elastic/elastic.indexer.service.ts

- Elasticsearch had an update where the mappings were improved, mainly `text` types were converted to `keyword`, which impacted the functioning of the API
- create a config flag to specify whether to target the new and upcoming ES information, starting with the account collections query which did not need to use the `.keyword` specification
- when targeting an updated indexer, such as `devnet-index.multiversx.com`, after setting the activation flag, account collections should start to be returned

Integrate new indexer mappings

---

src/endpoints/tokens/token.transfer.service.ts
src/graphql/schema/schema.gql
src/test/integration/services/nft.thumbnail.e2e-spec.ts

-  Instead of displaying the name of the collection in transaction operations, display the name of the NFT.
- Add NFT name in transaction operation
-  /transactions/9adc5b7e198dd4ce7625f8ad5b3a02615015032c0c30091d3c95059b5bba49cf -> operations.name: "Gnogenverse Land Voucher #7194",
- /nfts/GNOGEN-8e251b-1c1a/transactions?withOperations=true -> operations.name: "Gnogenverse Land Voucher #7194",

add nft name instead of collection name in transaction operation

---

src/endpoints/nfts/nft.service.ts

- The default rarity sort algorithm should be OpenRarity
- Change default nft rarity algorithm to openRarity
- https://api.multiversx.com/collections/ZOIDSTERS-9121a9/nfts?sort=rank

change default nft rarity algorithm to openRarity

---

src/endpoints/network/network.service.ts

- The stats endpoint returns only standard transaction count but excludes smart contract results
- add tx + scr in `transactions` attribute
- `/stats` endpoint should return `transactions` as 291+ mil.

Stats endpoint real transactions

---

package-lock.json
package.json

- Version of simple-git  used in package.json was critical vulnerable
-  Update simple-git to ^3.16.0

update simple-git version

---

src/endpoints/providers/provider.service.ts

-  When getProviders() methods was called, and after getProvider() method was called, extra fields from getProvider() were applied to geProviders() object
- copy the provider object before applying the extra fields
- first call /providers
- second call /providers/erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc0llllsayxegu
- call /providers again and see if the extra fields have not been applied

fix provider extra fields

---

src/common/gateway/gateway.service.ts

- Reinstate `getUrl` function call to select light gateway based on the requested component
- vm queries should go towards the light gateway

Use light gateway for VM queries

---

src/endpoints/tokens/token.service.ts
src/graphql/schema/schema.gql
src/test/integration/controllers/tokens.controller.e2e-spec.ts
src/test/integration/graphql/tokens.graph-spec.ts
src/test/integration/services/tokens.e2e-spec.ts

- gateway allows extracting the supply for any non-fungible esdt
- apply supply for MetaESDTs
- /tokens/XMEX-fda355 -> following fields should be available :point_down: 
- minted
- burnt
- supply
- circulatingSupply

add supply to any non fungible esdt

---

src/common/gateway/gateway.service.ts

- Handle case where the transaction fetch api call from gateway returns undefined
- `/transactions/b02a40735ccacac778333476a514589aca1cfe5dc13f744192935b1f1c5b5917` should not log any error message

Handle transaction not found in gateway

---

src/common/api-config/api.config.service.ts
src/common/locked-asset/locked-asset.module.ts
src/crons/cache.warmer/cache.warmer.module.ts
src/crons/cache.warmer/cache.warmer.service.ts
src/endpoints/endpoints.controllers.module.ts
src/endpoints/endpoints.services.module.ts
src/endpoints/esdt/esdt.module.ts
src/endpoints/mex/mex.farm.service.ts
src/endpoints/mex/mex.module.ts
src/endpoints/mex/mex.pair.service.ts
src/endpoints/mex/mex.settings.service.ts
src/endpoints/mex/mex.warmer.service.ts
src/endpoints/nfts/nft.module.ts
src/endpoints/tokens/token.module.ts
src/endpoints/transactions/transaction-action/recognizers/mex/transaction.action.mex.recognizer.module.ts
src/graphql/entities/graphql.services.module.ts
src/graphql/entities/xexchange/mex.token.module.ts
src/graphql/entities/xexchange/mex.token/mex.token.resolver.ts
src/main.ts

- Work in progress for moving optional functionality inside the `features` element
- Backwards compatible support for both the legacy way and the new way of integrating exchange url
Add the following config value
```yaml
features:
exchange:
enabled: true
serviceUrl: 'https://graph.xexchange.com/graphql'
```
Then verify that the mex-specific endpoints are loaded and the cache warmer processes start. When disabling / omitting this feature, the mex specific endpoints should not appear, and also no mex-specific cache warmer actions should be performed

Feature flag for exchange service

---

src/common/gateway/entities/gateway.component.request.ts
src/endpoints/proxy/proxy.controller.ts

- Include support for account guardian data
- `/address/:address/guardian-data` should return guardian data if supported on gateway

Proxify guardian data endpoint

---

src/common/entities/query.pagination.ts
src/common/gateway/gateway.service.ts
src/endpoints/marketplace/entities/account.auctions.ts
src/endpoints/marketplace/entities/auctions.ts
src/endpoints/marketplace/graphql/account.auctions.query.ts
src/endpoints/marketplace/graphql/auctionId.query.ts
src/endpoints/marketplace/graphql/auctions.count.query.ts
src/endpoints/marketplace/graphql/auctions.query.ts
src/endpoints/marketplace/graphql/collection.auctions.query.ts
src/endpoints/marketplace/nft.marketplace.controller.ts
src/endpoints/marketplace/nft.marketplace.service.ts
src/test/integration/services/marketplace.e2e-spec.ts
src/test/root-test.module.ts

- The query from nft data service returns 10 auctions so that the number of elements cannot be changed. 
- Apply a cursor and pagination in the query that allows the display of several elements depending on the required size. By default will be 25.
- /auctions -> return 25 auctions
- /auctions?size=1 -> return 1 auction
Auction details:
- /auctions/842224 -> return auction details for a specific auction id
Auctions count:
- /auctions/count -> return auctions count ~436631
- /auctions/count?status=running -> return auctions count with status `running` ~122405
Collection auctions:
- /collection/CRTMBT-9b5699/auctions -> return all auctions with status = running for a specific collection   
Account auctions count:
- /accounts/erd14qqefhazlg7j7ea5v58vfzen3y6wycpyzjle7m24mx3nae9vpz9q95atps/auct …

 nft marketplace auctions endpoint refactoring

---

src/endpoints/proxy/proxy.controller.ts

- Replaced address `storage` with `key` for fetching key information
- `/address/erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqplllst77y4l/key/0000000000000000000100000000000000000000000000000000000002ffffff` should return the content of the storage of the given key, just like it does from the gateway

Corrected endpoint for retrieving account key from storage

---

package-lock.json
package.json
src/endpoints/caching/local.cache.controller.ts
src/endpoints/caching/remote.cache.controller.ts

- Allow using both tokens for accessing private cache controllers
- use native auth token on `http://localhost:4001/cache/remote?keys=*historical-price:EGLD* `

JWT or native auth for cache controllers

---

src/endpoints/marketplace/graphql/auctions.query.ts
src/endpoints/marketplace/nft.marketplace.service.ts

-  Auctions endpoint had response time > 1000 ms
- Add currentTimestamp for the live auctions query
- Add Grouping by identifier
- make an request to /auctions and response time should be < 300 ms

fix performance issue for auctions endpoint

---

src/endpoints/nodes/node.service.ts

- when > 99% of the network has upgraded nodes, it is difficult from the `/nodes/versions` route to find out whether there are still some nodes with older versions
- change precision for node versions from 2 decimals to 4 decimals
- `/nodes/versions` route should return 4 decimal precision

More precision for node versions

---

src/endpoints/transactions/entities/transaction.create.ts

- Add support for new fields necessary for the guardian functionality
- route `POST /transactions` should also pass to the proxy the `guardian` and `guardianSignature` fields

Add support for guardian fields

---

src/common/indexer/elastic/elastic.indexer.helper.ts
src/endpoints/accounts/account.controller.ts
src/test/integration/graphql/transactions.graph-spec.ts
src/test/integration/services/transactions.e2e-spec.ts

-  When filter.token was applied in transactions endpoint, we did not have the possibility to filter by EGLD.
-  Add query condition when filter.token = "EGLD", retrieve all transactions where value field is <> 0
- /transactions?token=EGLD -> should return an array of transactions where value field is <> 0

add filter by EGLD

---

src/common/indexer/elastic/elastic.indexer.helper.ts
src/common/indexer/elastic/elastic.indexer.service.ts
src/common/indexer/entities/account.ts
src/common/indexer/indexer.interface.ts
src/common/indexer/indexer.service.ts
src/common/indexer/postgres/entities/account.db.ts
src/common/indexer/postgres/postgres.indexer.service.ts
src/crons/cache.warmer/cache.warmer.service.ts
src/crons/status.checker/status.checker.service.ts
src/endpoints/accounts/account.controller.ts
src/endpoints/accounts/account.service.ts
src/endpoints/accounts/entities/account.filter.ts
src/endpoints/accounts/entities/account.sort.ts
src/endpoints/accounts/entities/account.ts
src/endpoints/network/network.service.ts
src/graphql/entities/account/account.input.ts
src/graphql/entities/account/account.query.ts
src/graphql/schema/schema.gql
src/test/integration/graphql/accounts.graph-spec.ts
src/test/integration/services/accounts.e2e-spec.ts
src/test/integration/services/delegation.legacy.e2e-spec.ts
src/test/integration/services/nodes.e2e-spec.ts
src/test/unit/graphql/entities/account/account.query.spec.ts
src/utils/cache.info.ts

- the `/accounts/:address/contracts` endpoint returns the smart contract deployments, and doesn't actually return the smart contracts where the account is owner (since the owner can call the `ChangeOwner` function to change ownership to a different address)
- in order to solve this problem, we needed a new field `currentOwner` to be added in the ES index and use that field to filter the accounts
- add possibility of filtering by `ownerAddress` in the account list
- `/accounts?ownerAddress=erd1ss6u80ruas2phpmr82r42xnkd6rxy40g9jl69frppl4qez9w2jpsqj8x97` should return all accounts where the given address is owner
- `accounts?ownerAddress=erd1ss6u80ruas2phpmr82r42xnkd6rxy40g9jl69frppl4qez9w2jpsqj8x97&sort=timestamp&order=asc` should return all accounts sorted by timestamp in ascending
- …

 Filter accounts by ownerAddress

---

package-lock.json
package.json
src/main.ts

- Update SDK Nestjs to latest version, which contains a very important bugfix for the fields interceptor
- to be discussed

Update SDK Nestjs to latest version

---

src/endpoints/proxy/proxy.controller.ts

- Error logs contained a lot of errors due to bad user input
- Filter out errors for certain failures inside the proxy controller
- `/vm-values/hex` with the body
```json
{
"Args": [
"fbe99a95a6925693679933db8eb7cb19ef4d187ac63db1b0204ad978e1263112"
],
"FuncName": "getPublicKey",
"ScAddress": "erd1qqqqqqqqqqqqqpgqjq0h2hy6ppj5yze2t3gr6kadvaahkljch77qynjfg8"
}
```
should not log any error
- `/address/:address/key/:key` should not return error for a key that doesn't exist

Remove unnecessary logs

---

src/common/indexer/elastic/elastic.indexer.helper.ts
src/common/indexer/elastic/elastic.indexer.service.ts
src/common/indexer/indexer.interface.ts
src/common/indexer/indexer.service.ts
src/endpoints/accounts/account.controller.ts
src/endpoints/accounts/account.service.ts
src/endpoints/accounts/entities/account.history.filter.ts
src/graphql/entities/account.detailed/account.detailed.input.ts
src/graphql/entities/account.detailed/account.detailed.resolver.ts
src/graphql/schema/schema.gql
src/test/integration/services/accounts.e2e-spec.ts
src/test/integration/services/tokens.e2e-spec.ts

- Account history endpoint  did not allow searching by a timestamp
- Add in elastic query before and after filters condition
- accounts/erd103a544heqlz0hh63x8637nhtkuy99j2dn4t5dnf2u4u28gezr7xqrxn3cc/history?after=1677618270
- accounts/erd103a544heqlz0hh63x8637nhtkuy99j2dn4t5dnf2u4u28gezr7xqrxn3cc/history?before=1677618270&after=1677618216
- accounts/erd103a544heqlz0hh63x8637nhtkuy99j2dn4t5dnf2u4u28gezr7xqrxn3cc/history/WEGLD-bd4d79?after=1677618216

add before and after query params for accounts history

---

src/endpoints/blocks/block.service.ts
src/endpoints/blocks/entities/block.ts
src/graphql/schema/schema.gql
src/test/integration/services/blocks.e2e-spec.ts
src/test/integration/services/tokens.e2e-spec.ts

-  scheduledData .rootHash is not defined in block response body
- Add scheduledRootHash field
-  /blocks -> scheduledRootHash field should be defined
- /blocks/ed57df70de13292f22202dbbd8f64c805489fffc32b787851563df7cba8f4e5d -> scheduledRootHash should be defined
`"scheduledRootHash": "2edb1f5ee77edfa818b4d56b1c19b3aadd6d43c9d1bdb1d4357dde115d6681a1"`

 add scheduledRootHash block field

---

src/common/indexer/elastic/elastic.indexer.helper.ts
src/common/indexer/elastic/elastic.indexer.service.ts
src/common/indexer/entities/miniblock.ts
src/common/indexer/indexer.interface.ts
src/common/indexer/indexer.service.ts
src/common/indexer/postgres/entities/miniblock.db.ts
src/common/indexer/postgres/postgres.indexer.service.ts
src/endpoints/accounts/account.controller.ts
src/endpoints/blocks/block.controller.ts
src/endpoints/blocks/block.service.ts
src/endpoints/blocks/entities/block.filter.ts
src/endpoints/blocks/entities/block.ts
src/endpoints/miniblocks/entities/mini.block.filter.ts
src/endpoints/miniblocks/mini.block.controller.ts
src/endpoints/miniblocks/mini.block.service.ts
src/endpoints/tokens/token.controller.ts
src/endpoints/transactions/entities/transaction.detailed.ts
src/endpoints/transactions/entities/transaction.ts
src/endpoints/transactions/entities/transactions.query.options.ts
src/endpoints/transfers/transfer.controller.ts
src/endpoints/transfers/transfer.service.ts
src/graphql/schema/schema.gql
src/test/integration/services/blocks.e2e-spec.ts

-  To extend miniblocks endpoint functionality, we need to add possibility to retrieve all miniblocks details and filter by multiple miniblocks hashes
-  Add the following functionalities
- /miniblocks -> retrieve by default 25 miniblocks, sorted descending by timestamp
- /miniblocks/?hashes = [hash1, hash2,...] -> retrieve specific miniblocks details
- `/miniblocks?hashes=26be327a240e0ec88e6c06dda117e1235a656523849260bed35751906f44c29d,7f233a09e3ed3636efd2f8edb2755aa1faa528e7375549c2eec39cc0adf435db` -> return 2 miniblocks details
-  `/miniblocks` -> returns an array of 25 miniblocks
-  /transfers?withBlockInfo=true -> 
- `extra fields` 
senderBlockHash
senderBlockNonce
receiverBlockHash
receiverBlockNonce
- /transfers?withBlockInfo=false -> extra fields should not be defined
- max size …

support for multiple miniblocks hashes

---

src/endpoints/tokens/entities/token.ts
src/endpoints/tokens/token.service.ts
src/graphql/schema/schema.gql
src/test/integration/services/tokens.e2e-spec.ts

- Provide token collection in account tokens endpoints if MetaESDT
- `/accounts/erd1ut8kxtrkx8llshtcvsr42yu4ajgqrttvlg9ejacjn7xgs5g7werqwj8jxn/tokens?includeMetaESDT=true&type=MetaESDT` should all have the `collection` attribute

Provide token collection in account tokens endpoints if MetaESDT

---

src/endpoints/tokens/entities/token.ts
src/endpoints/tokens/token.service.ts
src/graphql/schema/schema.gql
src/test/integration/services/tokens.e2e-spec.ts

- Provide token collection in account tokens endpoints if MetaESDT
- `/accounts/erd1ut8kxtrkx8llshtcvsr42yu4ajgqrttvlg9ejacjn7xgs5g7werqwj8jxn/tokens?includeMetaESDT=true&type=MetaESDT` should all have the `nonce` attribute

Provide token nonce in account tokens endpoints if meta esdt

---

src/crons/cache.warmer/cache.warmer.service.ts
src/endpoints/esdt/esdt.service.ts

- Distinct accounts counter with the help of redis can silently fail if too many arguments are provided at once on redis distributions such as ElastiCache
- Count distinct accounts in chunks of 100
- Attach collection-specific extra fields only on NFT & SFT collections (previously it was also updating MetaESDT & FungibleESDT tokens
- `Token assets extra info invalidations` cache warmer should behave the same as before, but with chunked updates

Count token accounts in chunks

---

src/endpoints/tokens/token.controller.ts
src/endpoints/transactions/transaction.controller.ts
src/endpoints/transactions/transaction.service.ts
src/endpoints/transfers/transfer.service.ts
src/test/integration/api/accounts.api-spec.ts
src/test/integration/api/blocks.api-spec.ts
src/test/integration/api/collections.api-spec.ts
src/test/integration/api/nfts.api-spec.ts
src/test/integration/api/nodes.api-spec.ts
src/test/integration/api/rounds.api-spec.ts
src/test/integration/api/tokens.api-spec.ts
src/test/integration/api/transactions.api-spec.ts
src/test/integration/services/transactions.e2e-spec.ts
src/utils/api.checker.ts

- Similar to /transfer?withBlockInfo = true/false, for consistency, the query option withBlockInfo must be added to return the fields with information from the block in transactions endpoint
-  Add withBlockInfo query option in transaction service, 
- transactions?withBlockInfo=true&size=100 -> should throw 400 `Complexity 20000 exceeded`
- transactions?withBlockInfo=true -> senderBlockHash / senderBlockNonce / receiverBlockHash /receiverBlockNonce should be defined in transaction details
- tokens/BBB-3e120a/transactions?withBlockInfo=true -> senderBlockHash / senderBlockNonce / receiverBlockHash /receiverBlockNonce should be defined in transaction details
- tokens/BBB-3e120a/transactions?withBlockInfo=false -> block extra fields should not be defined
- …

support for extra block info for transactions endpoint

---

package-lock.json
package.json
src/common/protocol/protocol.service.ts
src/endpoints/accounts/account.controller.ts
src/endpoints/accounts/account.service.ts
src/endpoints/nfts/nft.service.ts
src/endpoints/tokens/token.controller.ts
src/endpoints/transactions/transaction.controller.ts
src/endpoints/transactions/transaction.get.service.ts
src/endpoints/transactions/transaction.service.ts
src/endpoints/transfers/transfer.controller.ts
src/endpoints/transfers/transfer.service.ts
src/utils/cache.info.ts

-  When fields 'senderBlockHash', 'receiverBlockHash', 'senderBlockNonce', 'receiverBlockNonce' are requested in transfers endpoint should be returned even if withBlockInfo is false
- Add fields parameter to be able to return 'senderBlockHash', 'receiverBlockHash', 'senderBlockNonce', 'receiverBlockNonce' fields when withBlockInfo is false
-  transfers?fields=txHash,senderBlockHash,receiverBlockHash,senderBlockNonce,receiverBlockNonce&size=50 -> should be returned 'senderBlockHash', 'receiverBlockHash', 'senderBlockNonce', 'receiverBlockNonce' 
- accounts/erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqplllst77y4l/transfers?fields=senderBlockHash,senderBlockNonce,receiverBlockNonce,receiverBlockHash
- tokens/WEGLD-bd4d79/transfers?fields=senderBlockHash,senderBlockNonce,receiverBlockNon …

add block info fields when withBlockInfo = false

---

package-lock.json
package.json

- Updates sdk-nestjs to version 0.1.21, which adds support for graphql in jwt & native auth guards
- activate auth and check whether it works both on REST api endpoints and on graphql endpoints

Updated sdk nestjs to latest version

---

config/config.devnet.yaml
config/config.e2e-mocked.mainnet.yaml
config/config.e2e.mainnet.yaml
config/config.mainnet.yaml
config/config.testnet.yaml
src/common/api-config/api.config.service.ts
src/endpoints/accounts/account.service.ts
src/test/integration/services/api.config.e2e-spec.ts

- Delegation contract shard id can be computed instead of hardcoded in configs files
- Might not work if metachain id is not 4294967295, but it may be smarter to change the way shards are calculated inside mx-nestjs-sdk to take in account custom metachain id as optional parameter?
- Compute the delegation contract shard id

Delegation shard

---

src/crons/cache.warmer/cache.warmer.service.ts
src/endpoints/collections/collection.service.ts
src/endpoints/esdt/esdt.service.ts

- MetaESDTs were returning through the `/collections/:collection` endpoint the holderCount which was linked to an attribute that is not updated any more
- Provide `accounts` attribute in the `tokens` endpoint as the number of distinct accounts if the token type is MetaESDT
- do not return `isVerified`, `holderCount`, `nftCount` in case of MetaESDT type collections
- `/tokens?includeMetaESDT=true&type=MetaESDT` and `/tokens/:token` endpoint should return `accounts` attribute for verified MetaESDTs (the ones that have assets set). The value should represent the number of distinct account holders as opposed to total account holders (even if an address has 2 or more MetaESDTs in the account, count it as 1)
- `/collections?type=MetaESDT` should not return `isVerified`, `holderCount`, …

Update holder count for MetaESDTs

---

src/endpoints/mex/mex.token.service.ts

- add `WEGLD` ticker for the `WEGLDUSDC` pair in the token list
- `/mex/tokens` endpoint should return `WEGLD` as well

Fix WEGLD in mex tokens endpoint

---

src/common/indexer/elastic/elastic.indexer.helper.ts

- Search by `token` if 2 components, search by `identifier` if 3 components separated by `-`
- `/accounts/erd1wp9wdsnck3pu7tmzk2l7q0xnmu9hr550ngrs852yvwa9kzdu9q0spmd7z9/history/XPACHIEVE-5a0519-01` should return data
- `/accounts/erd1wp9wdsnck3pu7tmzk2l7q0xnmu9hr550ngrs852yvwa9kzdu9q0spmd7z9/history/XPACHIEVE-5a0519` should return data
- `/accounts/erd1qqqqqqqqqqqqqpgqa0fsfshnff4n76jhcye6k7uvd7qacsq42jpsp6shh2/history/WEGLD-bd4d79` should return data

Search by proper field in accountsesdthistory index

---

src/common/indexer/elastic/elastic.indexer.service.ts
src/common/indexer/indexer.interface.ts
src/common/indexer/indexer.service.ts
src/common/indexer/postgres/postgres.indexer.service.ts
src/endpoints/accounts/account.controller.ts
src/endpoints/accounts/account.service.ts

- 
- 
- 
- Add support for account token history count
- accounts/erd19wkhfgs2glf97chl926fvwzgaq9eeakz474tzak6d998yu7xxtzqd3tng3/history/count -> should return~1034
- accounts/erd19wkhfgs2glf97chl926fvwzgaq9eeakz474tzak6d998yu7xxtzqd3tng3/history/count?after=1678893372 -> should return 2
- accounts/erd19wkhfgs2glf97chl926fvwzgaq9eeakz474tzak6d998yu7xxtzqd3tng3/history/VSWATCH-805ac3-0a/count -> should return 1
- accounts/erd19wkhfgs2glf97chl926fvwzgaq9eeakz474tzak6d998yu7xxtzqd3tng3/history/VSWATCH-805ac3/count -> return collection history count

 add account token history count

---

src/endpoints/identities/identities.controller.ts
src/endpoints/identities/identities.service.ts
src/endpoints/providers/provider.controller.ts
src/endpoints/providers/provider.module.ts
src/endpoints/providers/provider.service.ts
src/test/integration/services/accounts.e2e-spec.ts

- Adding a GET endpoint to expose the functionality to return the avatar for an specified identity.
-  Add a new method `getIdentityAvatar`  that only returns the avatar URL for a specified identity.
-  Utilize the existing `getIdentity(identifier)`  method to find the identity based on the provided identifier.
-  Implement a new GET endpoint ` /identities/:identifier/avatar ` that returns the avatar for a specified identity.
- Add a new method `getProviderAvatar` that only return the avatar URL for a specific provider else, return undefined
-  Implement a new GET endpoint ` /providers/:address/avatar ` that returns the avatar for a specified provider
-  GET identities/middlestakingfr/avatar
- GET providers/erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrlllllsyprnh6/avatar
- 200 OK: …

support for provider avatar

---

src/utils/cache.info.ts

- changed name for cache key for identity profiles, since some of them were not stored correctly
- check that all identity profiles are correctly re-fetched

Changed cache key for identity profile

---

src/endpoints/accounts/account.controller.ts

- On swagger, `withGuardianInfo` and `fields` was required.
- Add `@ApiQuery` to each field + specific description.
GET accounts/:address?withGuardianInfo=true&fields=isGuarded.
- Check swagger docs on accounts tag and check if `withGuardianInfo` and `fields` params are not longer required.

update swagger account endpoint

---

src/common/gateway/entities/transaction.ts
src/endpoints/transactions/entities/transaction.ts
src/endpoints/transactions/transaction.get.service.ts

- New fields was added in gateway transaction response body.
`guardian`
`guardianSignature`
- in tryGetTransactionFromGateway method return the guardian data extra fields
- /transactions/:txHash
- GET transactions/b8b3ed9f888c75264a0fced5d7531bd737ec7afb903984ce2964092457f20b08 -> `guardianAddress` and `guardianSignature` are defined

support for guardian data in transaction details

---

package-lock.json
package.json
src/common/indexer/elastic/elastic.indexer.helper.ts

- When searching by collections with wildcard, such as xmex, because of the latest elasticsearch index changes, no more results are returned
- use an updated version of sdk-nestjs which supports out-of-the-box case insensitive wildcard searches
- `/collection?search=xmex` should return results
- `accounts/erd1ff377y7qdldtsahvt28ec45zkyu0pepuup33adhr8wr2yuelwv7qpevs9e/collections?search=WEG` -> should return results
-`accounts/erd1ff377y7qdldtsahvt28ec45zkyu0pepuup33adhr8wr2yuelwv7qpevs9e/collections?search=WEG` -> should return [ ]
- `accounts/erd1n5sfjwyqstmvykhcppcsvwx96m9ladwsxsv6h248mpznwd6g590q2837gh/tokens?search=FOO` -> should return results
- `accounts/erd1n5sfjwyqstmvykhcppcsvwx96m9ladwsxsv6h248mpznwd6g590q2837gh/tokens?search=TESTS` -> should return [ ]

Case insensitive search for collections

---

src/endpoints/esdt/esdt.address.service.ts
src/endpoints/esdt/exceptions/trie.operations.timeout.error.ts
src/endpoints/tokens/token.service.ts
src/test/integration/services/tokens.e2e-spec.ts
src/utils/cache.info.ts

- For certain accounts that have a lot of esdts, the address esdt route from the gateway might throw trie timeout error, and thus not allowing data to be returned, although it is available in the Elasticsearch
- Handle the trie timeout error specifically to determine whether to fetch data from Elasticsearch also for user accounts (not just for smart contracts)
- `/accounts/erd1a2g46tj6lxjf0fhy760awqej4g5040kcfcuzjkfqx7g8fydr03as92g0q2/tokens` should return data after 10s the first time, near instant each subsequent time
- `/accounts/erd1a2g46tj6lxjf0fhy760awqej4g5040kcfcuzjkfqx7g8fydr03as92g0q2/nfts` should return data after 10s the first time, near instant each subsequent time

Elasticsearch fallback when trie timeout

---

src/queue.worker/nft.worker/queue/nft.queue.controller.ts

- Take into account that urls can contain spaces at the beginning and/or at the end of the url
- force refresh thumbnail for `TAVERN-e9b9d6-01` then check that it actually works

Trim url when generating thumbnail

---

src/common/indexer/elastic/elastic.indexer.helper.ts

- Adding elastic query support to return details of transfers for EGLD.
- In `buildTransferFilterQuery` for `filter.token` add the possibility to filter by EGLD.
- GET accounts/:address/transfers?token=EGLD
- GET transfers?token=EGLD
- GET transfers/count?token=EGLD
-  `transfers?token=EGLD`
-  `transfers/count?token=EGLD`
- `accounts/erd1qga7ze0l03chfgru0a32wxqf2226nzrxnyhzer9lmudqhjgy7ycqjjyknz/transfers?token=EGLD`

support for egld token filter in transfers endpoint

---

src/crons/transaction.processor/transaction.processor.service.ts
src/utils/cache.info.ts

- Support for `makeNewContractFromValidatorData` for invalidating node owner
- change cache key for owner for instant invalidation
- use `makeNewContractFromValidatorData` function call to change owner, make sure the owner is reflected in the `/nodes` endpoint

Owner invalidation in case of makeNewContractFromValidatorData function

---

src/common/pubsub/pub.sub.listener.controller.ts
src/common/pubsub/pub.sub.listener.module.ts
src/common/websockets/web-socket-publisher-controller.ts
src/common/websockets/web-socket-publisher-module.ts
src/main.ts

- Port 3099 for websockets was initialized for all types of machines: cachewarmer, queueworker, transaction processor, public api but should only have been enabled for the instances that run public api
- Reconfigure import of modules in such as way that the websocket publisher will only activate itself for the public api instances
- Run in parallel an instance with cache warmer, another with transaction processor, another with public api. All should start successfully

Expose Websocket port only on public api instances

---

src/endpoints/transactions/entities/transaction.detailed.ts
src/endpoints/transactions/transaction.get.service.ts

- The current implementation of the getTransaction method does not provide information about whether a transaction is in transit or not.
- In transit transactions are those with a miniBlockHash and a status of "pending".
- Including this information can be helpful for users to better understand the state of their transactions.
- Add a new field inTransit to the TransactionDetailed class as a boolean.
- Modify the tryGetTransactionFromGateway method to set the inTransit field to true if miniBlockHash is not undefined and status is "pending".
- Make a new transaction ( ESDT Transfer ) and within 5 seconds make a request to /transactions/:txHash and see if `inTransit` fields is defined as true, but check if miniblockHash is defined and status: pending

add inTransit transaction field

---

src/endpoints/providers/provider.service.ts

- If one of the provider contracts fails in the getMetadata function, do not break completely the whole process of fetching metadata from staking providers
- All identities from alll staking providers should be fetched from devnet
- `scctutorials` identity should exist as identity on its provider (contract `erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqflllllsnczv3v`)

Handle vm query error for getMetaData function

---

package-lock.json
package.json
src/endpoints/accounts/account.service.ts
src/endpoints/transactions.batch/entities/transaction.details.ts
src/endpoints/transactions.batch/transactions.batch.service.ts
src/graphql/schema/schema.gql

- Add support for `guardian` & `guardianSignature` fields in the transaction batch endpoint
- trigger transaction batch with a guarded transaction, which should be sent with all of its available fields

Support for guardian in transaction batch endpoint

---

src/endpoints/providers/entities/provider.ts
src/endpoints/providers/provider.controller.ts
src/endpoints/providers/provider.service.ts

- To provide more information's about providers , we wanted to fetch provider identity data only when necessary.
- We added an optional boolean parameter `withIdentityInfo` to the `getProviders` endpoint to include or exclude identity data.
- `/providers?withIdentityInfo=boolean`
- `providers?withIdentityInfo=true` -> should return identity data for each providers
- `providers?withIdentityInfo=false` -> should return only provider details without identity data
-`providers?providers=erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc0llllsayxegu,erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqq8hlllls7a6h85&withIdentityInfo=true` -> should return providers identity data even when `providers` filter is applied
- `providers?identity=binance_staking&withIdentityInfo=true` -> should return …

 identity data in provider details

---

src/test/integration/common/persistence.service.e2e-spec.ts
src/test/integration/common/rabbitmq-token.handle.service.e2e-spec.ts
src/test/integration/common/rabbitmq.consumer.e2e-spec.ts
src/test/integration/controllers/vmQuery.controller.e2e-spec.ts
src/test/integration/services/vmQuery.service.e2e-spec.ts

-  add new unit tests for all services from /common directory
To run the persistence.service.e2e-spec.ts you need to enable database from config!
- npm run test:e2e persistence.service.e2e-spec.ts
- npm run test:e2e rabbitmq.consumer.e2e-spec.ts

add persistence unit tests

---

src/endpoints/nodes/entities/node.ts
src/endpoints/nodes/node.module.ts
src/endpoints/nodes/node.service.ts
src/test/integration/services/nodes.e2e-spec.ts

- Not all nodes should have the `remainingUnBondPeriod` attribute, only those with the status `NodeStatus.leaving`. For other nodes, this attribute should be undefined, not 0.
- Added a function `applyNodeUnbondingPeriods` in the NodeService. This function assigns each node's `remainingUnBondPeriod` attribute by calling `keysService.getKeyUnbondPeriod` if the node status is NodeStatus.leaving. If not, `remainingUnBondPeriod` is set to undefined.
- Updated the `getAllNodesRaw()` function in `NodeService` to call the new `applyNodeUnbondingPeriods` function, adding remainingUnBondPeriod to all nodes with the status NodeStatus.leaving in the process.
- Add node -> Stake node -> Unstake node -> all from web wallet
- After this stepts, take the bls key and add it to nodes/:bls
- Response body …

add remainingUnbondPeriod

---

config/config.devnet.yaml
config/config.e2e-mocked.mainnet.yaml
config/config.e2e.mainnet.yaml
config/config.mainnet.yaml
config/config.testnet.yaml
src/common/api-config/api.config.service.ts
src/endpoints/collections/collection.service.ts
src/endpoints/esdt/esdt.service.ts
src/test/integration/controllers/collections.controller.e2e-spec.ts
src/test/integration/services/api.config.e2e-spec.ts
src/utils/cache.info.ts

-  For the GatewayService, we need to retrieve the NFT collection properties roles from Gateway
-  collections/SHIBAX-7baf9d 
- `before changes`:
"canUpgrade": false,
"canAddSpecialRoles": false,
- ` after changes`:
"canUpgrade": true,
"canAddSpecialRoles": true

get collection properties from gateway

---

src/endpoints/accounts/account.module.ts
src/endpoints/accounts/account.service.ts
src/endpoints/accounts/entities/account.key.ts
src/endpoints/nodes/node.service.ts
src/endpoints/providers/entities/provider.filter.ts
src/endpoints/providers/provider.controller.ts
src/endpoints/providers/provider.service.ts
src/test/integration/services/accounts.e2e-spec.ts
src/test/integration/services/delegation.e2e-spec.ts

-  Same as PR ( https://github.com/multiversx/mx-api-service/pull/1078 ), we added the remainingUnbondPeriod field for accounts/:address/keys
- Added a function `applyNodeUnbondingPeriods` in the `AccountService`. This function assigns each node's `remainingUnBondPeriod` attribute by calling `keysService.getKeyUnbondPeriod` if the node status is `NodeStatus.leaving`. If not, `remainingUnBondPeriod` is set to undefined.
- Add new provider filter ( owner ) to be able to search providers via owner address
- Fix delegation.e2e-spec.ts
- On DEVNET -> `accounts/erd14wxx9p9kld06w66n6lcxcchv976n7crzma8w7s3tkaqcme8hr7fqdhhfdg/keys` -> `remainingUnbondPeriod` field
- On MAINNET -> `providers?owner=erd1p3423t9rj5nxnqnyz2hzr43xrddxvzggwhp0amjgyhr4v939vstsmh6vtc&withIdentityInfo=true` -> should return …

add support for remainingUnbondPeriod for account keys

---

src/endpoints/tokens/token.transfer.service.ts

- If NFT does not have a name indexed, nothing is returned in the operation name field, although we have the collection name in memory
- Use collection name as a fallback in transaction operation
- `/transactions/5d09e2bb17fa0ee3a5e8e9d40523cd25f9f449f5eb7aae62e29a4f20a7c395ab` should return collection name in operation

Collection name fallback in transaction operation

---

src/endpoints/tokens/token.service.ts

- FungibleESDT Token identifiers are not returned if they are fetched from elasticsearch for a given account
- fall back to the `token` field if no `identifier` is present
- `/accounts/:smart-contract-account/tokens` should return identifiers for fungible tokens

Account token identifier fix if smart contract

---

src/endpoints/accounts/account.controller.ts
src/endpoints/transactions/transaction.controller.ts
src/endpoints/transfers/transfer.controller.ts

- `fields` api query from `/transactions`, `/transfers`,`/accounts/:address/transactions` was required
- Change api query for `fields` from required = true to false 
- check on swagger docs if `fields` is not required

fix required fields

---

src/endpoints/providers/provider.service.ts
src/test/integration/services/providers.e2e-spec.ts

- For `/providers`, all providers should have `automaticActivation` & `checkCapOnRedelegate` fields
- `/providers` -> `erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqq8hlllls7a6h85` -> should contain both fields
- `/providers?providers=erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqq8hlllls7a6h85` -> should contain both fields 
- `providers?owner=erd1p3423t9rj5nxnqnyz2hzr43xrddxvzggwhp0amjgyhr4v939vstsmh6vtc` -> should contain both fields

 add support for automaticActivation and checkCapOnRedelegate for providers

---

src/endpoints/mex/entities/mex.pair.exchange.ts
src/endpoints/mex/entities/mex.pair.type.ts
src/endpoints/mex/mex.pair.service.ts
src/endpoints/mex/mex.token.service.ts
src/graphql/schema/schema.gql

- Since the jungle dex has been merged into the main dex as `experimental` and experimental tokens were not returned on purpose by the api, all tokens merged from jungle to experimental have no associated price
- Return price for all experimental token types
- Remove support for jungle token types
- make sure `RARE` token is listed in the `mex/tokens` endpoint

Return prices for experimental DEX tokens

---

src/common/indexer/elastic/elastic.indexer.helper.ts
src/common/indexer/elastic/elastic.indexer.service.ts

- To be able to search for SetGuardian, UnGuardAccount and GuardAccount, we need to make search in Elastic with operation
- Modified the existing filter condition in the ElasticSearch query to support dual-field matching. Now, the query can match values against both `function` and `operation` fields.
-  `/transactions?function=SetGuardian` -> Should return an array of SetGuardian transactions
-  `/transactions?function=UnGuardAccount` -> Should return an array of UnGuardAccount transactions
-  `/transactions?function=GuardAccount` -> Should return an array of UnGuardAccount transactions
-  `transactions?function=SetGuardian&size=25&sender=erd1v9g8l0dvqhr8aj6df4s3ln3m396qe8yhuj0du546lx0tp8tckgcq9x08k4&receiver=erd1v9g8l0dvqhr8aj6df4s3ln3m396qe8yhuj0du546lx0tp8tckgcq9x08k4` -> should return …

add support for operation search

---

src/common/indexer/elastic/elastic.indexer.service.ts

- When new transaction was created, and request to /transaction/:txHash was made, 500 internal server was throw
- Add check condition for undefined
- Create new transaction ( e.g Send NFT ) -> copy txHash and request to /transaction/:txHash

add check for undefined transaction

---

src/endpoints/blocks/block.controller.ts
src/test/integration/controllers/nfts.controller.e2e-spec.ts
src/test/integration/graphql/nfts.graph-spec.ts

-  `hashes` filter in swagger was required by default
- add proper description for `hashes` filter and make required = false
- /blocks?[hash1, hash2] -> should return 2 blocks details based on provided hashes

add hashes api query description

---

src/endpoints/blocks/block.controller.ts
src/endpoints/tokens/token.transfer.service.ts
src/test/integration/controllers/nfts.controller.e2e-spec.ts
src/test/integration/graphql/nfts.graph-spec.ts
src/test/integration/services/transactions-batch.e2e-spec.ts

- After the latest node update, take into consideration that topics can be undefined
- `/transactions?hashes=4521514b0cb9f574705837dc8a81e86eb4d3056761e6f3f3f0c89ae0fa7b00ab&withOperations=true` should not return error

Event topics handle undefined

---

src/endpoints/nodes/entities/node.ts
src/endpoints/nodes/node.service.ts
src/graphql/schema/schema.gql

- Inactive nodes are incorrectly marked as leaving
- Mark nodes as leaving only where applicable
- `/nodes/3e79c969102742f86dccd17ee1a34cecc238cd701e507c9ef4ad6f8da2f97a6386ca9d7644a70f3436d4219d2c14af10d3c802a9ca84718165ed7cd8b7bc2e4745ff903ea533433dca6458ee71ba7d056e6a10b4cc0e55bffdf130dcc867a793` should have status `inactive`

Node status leaving fix

---

src/graphql/schema/schema.gql
src/utils/token.helpers.ts

- When calculating url hash for media, trim the url first to account for urls that start or end with whitespace
- for NFT with identifier `TAVERN-e9b9d6-01`, computed url hash should be `fb18a758`

Trim NFT url when hashing

---

src/endpoints/tokens/token.service.ts

- Apply ticker also when retrieving tokens for contracts
- `/accounts/erd1qqqqqqqqqqqqqpgqgulmfcu8prrv2pmx3nqn5stqu3c42fsz4fvsa9rwdl/tokens` should contain the `ticker` attribute

Apply ticker for contract address tokens

---

src/endpoints/mex/entities/mex.pair.state.ts
src/endpoints/mex/mex.pair.service.ts

- New MexPairState was added in DEX API
- Add PartialActive case in `getPairState` method to be able to return mex pairs with status partial active
- `/mex/pairs` -> should return mex pairs

add partial active state case

---

src/endpoints/mex/entities/mex.pair.state.ts
src/endpoints/mex/mex.pair.service.ts

- New MexPairState was added in DEX API
- Add PartialActive case in `getPairState` method to be able to return mex pairs with status partial active
- `/mex/pairs` -> should return mex pairs

Support for partially active mex pairs

---

src/endpoints/tokens/token.service.ts

- For Hatom tokens, marketCap value was not calculated
- Add marketCap value for each Hatom token
- tokens/SEGLD-3ad2d0 - `marketCap` should be defined
- tokens/HEGLD-d61095 -> `marketCap` should be defined

apply marketCap for Hatom tokens

---

src/common/indexer/elastic/elastic.indexer.helper.ts
src/common/indexer/elastic/elastic.indexer.service.ts

- To be able to search for `SetGuardian`, `UnGuardAccount` and `GuardAccount`, we need to make search in `Elastic` with operation for transfers
- Modified the existing filter condition in the `ElasticSearch` query to support dual-field matching. Now, the query can match values against both function and operation fields.
- `accounts/erd19k4alvl0mg2fwhrp8jck3aucj0xmgczy28v4u0gmfunkhyjh7wmq0nmhas/transfers` -> one of the returned transfers results should have `function: SetGuardian` defined ( e7299ea221163784a5dd6499f10183736c7e320302d2199fff5cd6a23b93bdeb )
- `accounts/erd19k4alvl0mg2fwhrp8jck3aucj0xmgczy28v4u0gmfunkhyjh7wmq0nmhas/transfers?function=SetGuardian` -> should return only the transfers where `function: SetGuardian`
- `transfers?function=SetGuardian` -> all transfers results …

add operation search for transfers and add processTransaction

---

src/endpoints/providers/provider.service.ts

-  Same as PR https://github.com/multiversx/mx-api-service/pull/1110 we need to return numNodes value when withLatestInfo = true
- Fetch `numNode` value using vm-query `getNumNodes`
-  create new delegation contract -> numNode value will be 0
-  add node to your staking provider
- `providers?owner=erd1czgky3rcqggezg6zan5k2c9sfnwlh644jc26t6vud256ack9xaaqvhqddm&withLatestInfo=true` ->  numNodes should be 1

fetch numNodes using vmquery

---

src/endpoints/tokens/entities/token.account.ts
src/endpoints/tokens/token.service.ts
src/test/integration/services/tokens.e2e-spec.ts

-  For `tokens/:token/accounts`, for each account, the assets field is missing
- Adding the assets field for each account that owns a specific token
- `/tokens/WEGLD-bd4d79/accounts` -> every account should contain assets field
- `tokens/BHAT-c1fde3/accounts` -> if an account does not have assets defined, the assets field will not be displayed

add support for token accounts assets

---

src/endpoints/providers/entities/provider.query.options.ts
src/endpoints/providers/provider.controller.ts
src/endpoints/providers/provider.service.ts

- 
- 
- 
- `/providers?withLatestInfo=true` -> should throw `BadRequestException` because `owner` filter is not defined
- `providers?owner=erd1fx5t2nwq4fh9jws5xqfl85hr0l8tuqks9sr7ut9wrpkp7dugzxnqyksfyg&withLatestInfo=true` -> should return provider info based on `owner` filter and `withLatestInfo` filter applied

add complexity to withLatestInfo filter

---

src/endpoints/providers/provider.service.ts

- Cannot convert 0x to a BigInt
- Add `numberDecode` that includes a conditional (hex ? '0x' + hex : hex), ensuring that if the hex string is empty, it defaults to an empty string (which will be transformed into BigInt(0))
- `providers?withIdentityInfo=true&owner=erd1vdhv6a4jec7sr2r4vcznthreu3wesul2t0j345ay3cwch7qv4p7qxk5f99&withLatestInfo=true` ->

handle situation when hex string is empty

---

src/endpoints/accounts/account.service.ts
src/endpoints/nodes/entities/node.filter.ts
src/endpoints/nodes/entities/node.status.ts
src/endpoints/nodes/node.controller.ts
src/endpoints/nodes/node.service.ts
src/endpoints/providers/provider.service.ts

- To be able to return the `notStaked` status for staking providers, we need to add a new vmQuery call.
- In the current implementation, `notStaked` status is not defined
- Introduced a conditional check to identify if an address is a `staking provider`. For such addresses, we now fetch all node states using the `getAllNodeStates` vmQuery.
- Implemented a new method getInactiveNodes which extracts nodes in `notStaked` status from the fetched data.
- The `notStaked` nodes are transformed into `AccountKey` objects and appended to the existing `nodes` array which is returned by the getKeys method.
- For non-staking provider addresses, the original logic is maintained to retrieve the `blsKeysStatus` via `getBlsKeysStatusForPublicKey` vmQuery.
- Introduced new nodes filter `keys` to be able to …

add support for notStaked nodes and add support for multiple keys filter

---

src/endpoints/usernames/username.controller.ts
src/endpoints/usernames/username.service.ts
src/graphql/schema/schema.gql
src/test/integration/controllers/username.controller.e2e-spec.ts
src/test/integration/services/username.e2e-spec.ts

- Instead of fetch (redirect) to `accounts/address`, use  `getAccount` from `AccountService` to return `AccountDetailed` with Guardian Info when `withGuardianInfo` filter is set.
- use an account guarded -> `/usernames/:username?withGuardianInfo=true` -> it should return guardian info keys

add support for guardian info in username controller

---

src/common/indexer/elastic/elastic.indexer.service.ts
src/endpoints/sc-results/entities/smart.contract.result.ts

- Add `function` attribute to smart contract results
- `/results?miniBlockHash=de06738bc512eb3995671e07c79149a4888ad5d9d6355457fd210dd081fb975b`
- `/results/898686a2bd64e8da4864c248e56a1a1771ebab052672a2d1e9c9c848d83539e7`
- `/transactions/2d6aa31a10788118148eabf316f40b0339df0002d47cc08c1bfa986071fec1b9`
- `/accounts/erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqx0llllsdx93z0/results/d6657f6eca39a78e6eeb1afdd634e6416bb9e7f5748e4a961693681a199dcb64`
- all of the above, should provide the `function` attribute for smart contract results

Add function attribute to smart contract results

---

src/endpoints/transactions/transaction-action/recognizers/esdt/transaction.action.esdt.nft.recognizer.service.ts
src/test/integration/services/transactions.e2e-spec.ts

-  support for recognizing ESDTNFTBurn action in transaction details
- `/transactions/1a9176f5e3be9b2bff237e9fc6da34589d1cd9a8f3499354df26c5efd7a8a5a8` -> `action` key should be defined for ESDTNFTBurn transaction

add recognizer for ESDTNFTBurn transaction

---

src/common/indexer/elastic/elastic.indexer.service.ts
src/endpoints/esdt/esdt.service.ts
src/endpoints/tokens/entities/token.properties.ts
src/test/integration/services/tokens.e2e-spec.ts

- For all fungible tokens, creation date field was not defined
- Fetch `timestamp` value from ES for every fungible token
- `/tokens` -> all tokens should have `timestamp` field defined
- `/accounts/erd1awuuva7dhnlun9huwx7uefwpkhzjx9d3phenujgkv3zvx9tvsatsw420qt/tokens/UTK-2f80e9` -> returned token should have `timestamp` field defined
-  `/accounts/erd1kc3y0d3jhmv4j42lvyq84t395s7s47tucpw97grwgaj8dqlkzumsw97k34/roles/tokens`  -> returned token should have `timestamp` field defined
-  `/accounts/erd1kc3y0d3jhmv4j42lvyq84t395s7s47tucpw97grwgaj8dqlkzumsw97k34/roles/tokens/UTK-2f80e9` -> returned token should have `timestamp` field defined

add token timestamp

---

src/endpoints/transactions/transaction-action/recognizers/esdt/transaction.action.esdt.nft.recognizer.service.ts
src/test/integration/services/transactions.e2e-spec.ts

- Add token burn value for ESDTNFTBurn transaction
-`/transactions/e3526867c86fa9f31ef174d67578def2716ceb7d144f42fb2756ae9e4d0121d4` -> value should be 1

add token value key for ESDTNFTBurn transaction

---

src/endpoints/network/network.service.ts

- Removed getTotalActiveStake vm query since the resulting variable is not used anywhere
- nothing should be affected by this change

Removed getTotalActiveStake vm query

---

src/common/assets/assets.service.ts

- *-media.elrond.com works only with standard networks, and will not work with newer networks, such as `devnet2`
- if not standard network, return the raw image from `githubusercontent.com`
- if network `devnet2`, token image from github

Raw token image if not standard network

---

config/config.devnet.yaml
config/config.devnet2.yaml
config/config.e2e-mocked.mainnet.yaml
config/config.e2e.mainnet.yaml
config/config.mainnet.yaml
config/config.testnet.yaml
src/common/api-config/api.config.service.ts
src/main.ts
src/test/integration/services/api.config.e2e-spec.ts

-  Remove support for swagger API servers ( testnet / devnet / mainnet )
-  Remove urls.api from configs
-  Remove getApiUrls from apiConfigService.ts
-  Remove e2e-spec.ts for getApiUrls
- `run: npm run start:mainnet` -> access `localhost:3001`  and verify is servers dropdown list are removed

remove api urls servers config

---

src/common/graphql/graphql.service.ts
src/endpoints/mex/mex.pair.service.ts

- pairLimit it was hardcoded when making a request to pairs dex graphql 
- since the limit was set to 100, all the pairs created later did not contain the date such as `marketCap`, `price`, for example `XBID-c7e360`
- Add new query to return total number of available pairs from DEX
- refactoring of the `getData` method to allow the execution of the query without the declared variables
- `mex/pairs?size=200` -> should return 104 pairs
- `tokens/XBID-c7e360` -> `marketCap, price` attributes should be defined

add support for dynamic pairLimit

---

src/common/indexer/entities/sc.deploy.ts
src/endpoints/accounts/account.service.ts
src/endpoints/accounts/entities/contract.upgrades.ts
src/test/integration/services/accounts.e2e-spec.ts

-  scdeploys elastic has been updated with new keys
- add codeHash support for `accounts/:address/upgrades` 
- `accounts/erd1qqqqqqqqqqqqqpgqnnl9nn0kuuckhg24g02hq2745n4jk2hp327qcay4nm/upgrades` -> `codeHash` should be defined

add support for codeHash for each contract upgrade

---

src/endpoints/tokens/token.transfer.service.ts

-  At the topic event level, changes were made to the number of events
-  Handle events topics with length 2 
-  Keep support for event topics with length 3
- `/transactions/68c028cfcecbf4acc625ef5d0591e3bcc8b8d352e761a324f1bec9f1d42e9b40` -> operations attribute should contain 2 transfers events

add support for events topics

---

config/config.devnet.yaml

- Due to the transition to the new `devnet`, the `delegation contract` was changed
- Update delegation contract to the new contract
-` /economics` -> should return economics info

update delegation contract

---

src/common/protocol/protocol.service.ts
src/endpoints/network/network.service.ts
src/test/unit/services/network.spec.ts

- instead of using magic numbers `4294967295` take metaChainShardId from config 
- refactor `getStatus` method from `network.service.ts`
- add new unit tests for `network.spec.ts`
- refactor `getConstantsRaw` method from `network.service.ts`
- remove `apiService.get` and fetch constats data directly from gatewayService using method `getNetworkConfig`
- update `network.spec.ts`
- `/shards` -> should return all shards id
- `/nodes` -> all returned nodes should contains shard details
- run `npm run test newtork.spec.ts`

avoid magic numbers for metaChainShardId

---

src/endpoints/proxy/proxy.controller.ts

- Use `ApiExcludeController` decorator instead of `ApiExcludeEndpoint` to exclude proxy endpoints
- Open docs ( swagger ) and verify if proxy endpoints are not displayed

use general exclude decorator for proxy controller

---

src/endpoints/accounts/account.controller.ts
src/endpoints/accounts/account.service.ts
src/test/unit/services/accounts.spec.ts

- To be able to return total smart contract count, we need to add `isSmartContract` filter to be able to filter
- Added `isSmartContract` for `account/count` & alternative count route `accounts/c`
- `accounts/count?isSmartContract=true` -> should return total smart contracts count
- `accounts/c?isSmartContract=true` -> should return total smart contracts count
- `accounts/count?isSmartContract=false` -> should return total accounts, that's include also the smart contracts
- `accounts/c?isSmartContract=false` -> should return total accounts, that's include also the smart contracts

add isSmartContract count support

---

config/config.mainnet.yaml
src/common/indexer/elastic/elastic.indexer.helper.ts

- When multiple functions were added to the `/transfers`, `/transactions` filter param, it returns empty array
- Modify actual implementation for `buildTransferFilterQuery` , `buildTransactionFilterQuery` methods to be able to search for multiple functions
- `transfers?function=buy,deposit` -> should return only `buy`, `deposit` transfers
- `transfers?function=buy` -> should return only `buy` transfers
- `transfers?function=` -> should return all transfers
- `transfers/count?function=buy,deposit` -> should return total transfers count for transfers with `buy`, `deposit`
- `transfers/c?function=buy,deposit` -> should return total transfers count for transfers with `buy`, `deposit`
- `transfers/count?function=buy` -> should return total transfers count for transfers with `buy`
- …

fix array of functions

---

src/endpoints/mex/mex.controller.ts

- We should avoid using 'any' type.
- Replace 'any' type usages with specific types.
- `mex/farms` -> should return all mex farms
- `mex/pairs` -> should return all mex pairs

update mexFarms / mexPairs with specific return types

---

src/common/gateway/entities/gateway.component.request.ts
src/endpoints/proxy/proxy.controller.ts

-  To facilitate the dynamic forwarding of requests to various endpoints of the `gateway`, we need to implement a generic endpoint. This will allow to handle requests flexibly, enabling it to interact with multiple endpoints of the gateway without the need for hardcoding specific routes in our `ProxyController`.
- Add a `forwardGateway` method to the `ProxyController`. This method will handle incoming requests and forward them to the corresponding gateway endpoint
-  Check any endpoint from gateway that is not hardcoded in Proxy Controller. 
Example:
- `network/ratings` -> should return network ratings

add generic proxy forward endpoint

---

src/endpoints/mex/entities/mex.pair.ts
src/endpoints/mex/entities/mex.token.ts
src/endpoints/mex/mex.pair.service.ts
src/endpoints/mex/mex.token.service.ts

- on exchange graphql for tokens/pairs was added new field `previous24hPrice`
-  Add support for `basePrevious24hPrice` & `quotePrevious24hPrice`
-  Add support for token `previous24hPrice`
- `mex/pairs` -> all pairs should contain `basePrevious24hPrice` and `quotePrevious24hPrice`
- `mex/tokens` -> should contain `previous24hPrice` key

add support for mex tokens previous price

---

src/crons/cache.warmer/cache.warmer.service.ts

- calling `this.myFunction.name` actually does not return the function's name. never worked like this
- instead of extracting the name dynamically for a cron job's name, specify it as a string
- enable both staking v4 and transaction pool and cache warmer should start

fixed cron names

---

src/common/keybase/keybase.service.ts

- node identity should be able to be removed and the identity should still be valid, since the owner should properly prove the ownership over those nodes
- Take into account node owner also if not staking provider address
- MultiversX Community Delegation nodes should have the `multiversx` identity correctly associated to them

Identity owner fix

---

src/endpoints/pool/pool.controller.ts

- tx pool endpoint has an issue in definind the Swagger response type
- fixed swagger
- `http://localhost:3001/#/pool/PoolController_getTransactionPool` - should display an array of transactions as the successful result type

fix tx pool swagger docs

---

src/common/indexer/elastic/elastic.indexer.helper.ts
src/common/indexer/elastic/elastic.indexer.service.ts
src/common/indexer/indexer.interface.ts
src/common/indexer/indexer.service.ts
src/crons/cache.warmer/cache.warmer.service.ts
src/crons/status.checker/status.checker.service.ts
src/endpoints/accounts/account.controller.ts
src/endpoints/accounts/account.service.ts
src/endpoints/accounts/entities/account.detailed.ts
src/endpoints/accounts/entities/account.query.options.ts
src/endpoints/accounts/entities/account.ts
src/endpoints/network/network.service.ts
src/graphql/entities/account/account.input.ts
src/graphql/entities/account/account.query.ts
src/graphql/schema/schema.gql
src/test/unit/services/accounts.spec.ts
src/test/unit/services/transfers.spec.ts

- added possibility of requesting the `txCount` and `scrCount` fields in the account list endpoint
- `/accounts?withTxCount=true&withScrCount=true` should return the `txCount` and `scrCount` fields

withTxCount, withScrCount support in account list endpoint

---

src/endpoints/transactions/transaction.get.service.ts

- with the latest protocol release, misleading duplicated events can be returned in some edge cases
- until a new protocol release, alter the logs to avoid misleading information
- `http://localhost:3001/transactions/9577b1e88608495a5dc259dc2e313730f44871b859f575bc6e14f380df04ac15` when running on devnet should have the first topic of the event "transferValueOnly" with data field "QmFja1RyYW5zZmVy" set to "0"
- other transactions logs / events should not be affected

SERVICES-2122: duplicated transfer value only logs

---

src/endpoints/transactions/transaction.get.service.ts

- Instead of removing the transferred value from `BackTransfer` event, remove it from `AsyncCallback`

Remove value from asyncCallbackEvent

---

src/endpoints/tokens/token.transfer.service.ts

- Since the `MultiESDTNFTTransfer` operation now contains all tokens inside 1 log, the functionality that adds token identifiers needs to also be adjusted to contain all tokens from the same log
- Loop over the remaining topics if the event type is `MultiESDTNFTTransfer` and extract the remaining token identifiers
- `/transactions/5ad17620c9881f084564e15e619e828b0af41804566c12c3657c6c0cdd5051f0` should return `decimals`, `svgUrl`, `valueUSD`, `name`, `ticker` info for all transferred tokens

Add token info in MultiESDTNFTTransfer operations

---

src/common/assets/entities/token.assets.price.source.type.ts
src/endpoints/keys/keys.controller.ts
src/endpoints/nfts/entities/nft.ts
src/endpoints/rounds/entities/round.detailed.ts

- Swagger JSON Documentation throw an error for the way of declaring API Property for each attribute in different entities
- Add to correct `type` for each property
- `<localhost>/-json` -> copy the json and try to validate here https://editor.swagger.io/. No error should be displayed

add correct API Property type

---

src/common/gateway/gateway.service.ts
src/endpoints/proxy/proxy.controller.ts
src/endpoints/vm.query/vm.query.controller.ts
src/endpoints/vm.query/vm.query.service.ts
src/interceptors/deep-history.interceptor.ts
src/test/unit/services/vmQuery.service.spec.ts

- extend deep history gateway support for the `/vm-values/query` endpoint
- perform query to the `/query` or the `/vm-values/query` endpoints with `timestamp` parameter. The response headers should return the block nonce corresponding to the provided timestamp in the shard of the `scAddress` parameter

Deep history for vm query

---

src/interceptors/deep-history.interceptor.ts

- Deep history queries did not work correctly if the address was on shard 0 because of the falsy check which activated also for a number with value 0
- change falsy check with undefined check
- Use a deep history query with timestamp for an address on shard 0, which should work

Deep history shard 0 fix

---

src/test/unit/controllers/pool.controller.spec.ts
src/test/unit/controllers/services.mock/pool.services.mock.ts

- Add new tests for `pool.controller.ts`
- `npm run test` -> all tests should pass

add pool controller specs

---

src/endpoints/accounts/account.controller.ts
src/endpoints/delegation.legacy/delegation.legacy.service.ts

We need to support `timestamp` parameter to the Legacy Staking and Staking endpoints in the Accounts controller.
- Add timestamp query parameter
- Validate legacy staking VMQuery result in case it is null or DeepHistory doesn't work
- 
- Test the /stake and /legacy-delegation endpoints with an address and different timestamps
- 
-

Staking add timestamp parameter to legacy staking

---

src/endpoints/accounts/account.controller.ts
src/endpoints/tokens/entities/token.detailed.ts
src/endpoints/tokens/entities/token.filter.ts
src/endpoints/tokens/entities/token.with.balance.ts
src/endpoints/tokens/token.controller.ts
src/endpoints/tokens/token.service.ts
src/graphql/schema/schema.gql
src/test/unit/services/tokens.spec.ts

- To enhance token data with contextual exchange information, we need to include `mexPairType` indicating the category of each token within the ecosystem (e.g., core, community).
- Implement `applyMexPairType` method that enriches an array of tokens with their respective `MexPairType` by leveraging the `mexPairService.getAllMexPairs` to fetch pair information and match each token with its pair type based on `baseId`.
- Integrate `applyMexPairType` within `getAllTokensRaw` method to apply `MexPairType` information to each token during the token fetching process.
- `/tokens` -> every token should contain `mexPairType` property
- `/tokens/CRT-52decf` -> token details should contain `mexPairType` property
- `/tokens?mexPairType=core` -> should return all core tokens
- …

add mexPairType token property

---

src/endpoints/tokens/entities/token.detailed.ts
src/endpoints/tokens/entities/token.ts
src/endpoints/tokens/token.service.ts
src/graphql/schema/schema.gql

- Tokens could have artificially inflated economics and display a very large market cap by providing a very small liquidity amount
- Provide the total liquidity as a field on the token itself, for better visibility
- if the liquidity divided by the market cap on all pools is less than 1%, then we exclude it from sorting by market cap
- return an `isLowLiquidity` field in the token if the above condition is true
- `/tokens` should not return in the first results tokens with high market cap, but low liquidity
- for the tokens with the criteria above, the `isLowLiquidity` field should be set to true

Exclude market cap from low liquidity tokens when sorting

---

src/endpoints/tokens/entities/token.ts
src/endpoints/tokens/token.service.ts
src/graphql/schema/schema.gql

- To respect the already created convention, instead of the `transfersCount` attribute, we will change it to `transfers` 
- Change `transfersCount` attribute to `transfers`
- `tokens/MEX-455c57` -> check if `transfers` property is defined
- `tokens` -> every token should contain `transfers` property

rename transfersCount to transfers for token details

---

src/endpoints/tokens/token.service.ts

- Lowering the threshold from `1%` to `0.5%` allows for a more precise identification of tokens with genuinely low liquidity, ensuring that our liquidity checks are more aligned
-  Using a constant for the low liquidity threshold instead of a hardcoded numeric value makes the code easier to read and understand.
- Change the liquidity check threshold from `1%` (previously hardcoded as `0.01`) to `0.5%` (now defined as `LOW_LIQUIDITY_THRESHOLD`), to better identify tokens with low liquidity.
- `/tokens` -> verify the sorted tokens

lower the percentage to 0.5% in liquidity requirement

---

src/endpoints/endpoints.controllers.module.ts
src/endpoints/proxy/gateway.proxy.controller.ts
src/endpoints/proxy/index.proxy.controller.ts
src/endpoints/proxy/proxy.controller.ts
src/endpoints/proxy/proxy.module.ts
src/interceptors/transaction.logging.interceptor.ts

- To ease with debugging, offer the possibility to access the ES instance that sits behind the api
- GET `/index/logs/_search` should return logs
- GET `/index/logs/_count` should return logs count
- POST `/index/logs/_search` should return logs with query params set in body
- POST `/index/logs/_count` should return logs count with query params set in body

Forward index endpoints

---

src/endpoints/accounts/account.controller.ts

- Swagger API makes adding timestamp mandatory for accounts/:address/tokens/:token
- Specify the swagger ApiQuery decorator to make it non-mandatory
- check the swagger does not require it mandatory anymore

Accounts token timestamp non mandatory for accounts endpoint swagger

---

src/endpoints/providers/provider.controller.ts

- Swagger API makes adding `withLatestInfo` filter mandatory for `/providers`
- specify the swagger ApiQuery decorator to make it non-mandatory
- check the swagger does not require it mandatory anymore

make non mandatory with latest info field in swagger

---

src/common/indexer/elastic/elastic.indexer.helper.ts
src/common/indexer/elastic/elastic.indexer.service.ts
src/common/indexer/indexer.interface.ts
src/common/indexer/indexer.service.ts
src/common/indexer/postgres/postgres.indexer.service.ts
src/crons/status.checker/status.checker.service.ts
src/endpoints/network/network.service.ts
src/endpoints/sc-results/entities/smart.contract.result.filter.ts
src/endpoints/sc-results/scresult.controller.ts
src/endpoints/sc-results/scresult.service.ts
src/graphql/entities/smart.contract.result/smart.contract.result.query.ts
src/test/unit/services/scresults.spec.ts

- to be able to sort sc-results after sender or receiver we need to add specific filters 
- also, adding support for functions filter to be able to return all sc results for a specific function
- also, adding support for results count filters
- Add `sender` and `receiver` filters 
- Add `functions` filter of type array
- Add `sender`, `receiver`, `functions` count filters
- `/results?sender=erd1qqqqqqqqqqqqqpgqjq0h2hy6ppj5yze2t3gr6kadvaahkljch77qynjfg8` -> should return all scresults where sender is `erd1qqqqqqqqqqqqqpgqjq0h2hy6ppj5yze2t3gr6kadvaahkljch77qynjfg8`
- `/results?receiver= erd132v69stv7kc3t6xpdz6upn5w9v400ekka8hc0cjz06250jcjd8zq9gcjs8 ` -> should return all scresults where receiver is `erd132v69stv7kc3t6xpdz6upn5w9v400ekka8hc0cjz06250jcjd8zq9gcjs8 `
- …

add support for sender receiver scresults

---

src/endpoints/network/entities/about.ts
src/endpoints/network/network.service.ts

- External api providers maybe don't have git installed or start the service from a private repository where the application / plugins commit hash is not relevant, in which case a custom version can be read from the environment variables
- support for returning api version from a custom environment variable
- if the git commands somehow fail, still return the other relevant information
- when starting the service with `API_VERSION` environment variable, it should be reflected in the `/about` endpoint

Support for custom api version for about endpoint

---

package-lock.json
package.json
src/common/graphql/graphql.service.ts
src/endpoints/mex/mex.economics.service.ts
src/endpoints/mex/mex.farm.service.ts
src/endpoints/mex/mex.pair.service.ts
src/endpoints/mex/mex.settings.service.ts
src/test/unit/services/graphql.service.spec.ts

- in some situations, graphql requests can have timeouts and the graphql-request library waits forever for the response to come
- implement a custom fetch function in the graphql service to have a reasonable timeout (60 seconds)
- replace the exchange / nft marketplace url with a bigger timeout than 60 seconds (e.g. https://httpbin.org/delay/90) and make sure the user aborted error occurs after 60 seconds without having to wait for the full 90 seconds

GraphQL requests with timeout

---

src/common/keybase/keybase.service.ts
src/endpoints/identities/identities.service.ts
src/utils/cache.info.ts

- network-specific avatar url
- store all identities under the same cache key to fix the issue of deleted identities still appearing
- devnet or testnet-specific identities should reference in the `/identities` endpoint their corresponding avatars
- deleting a identity from assets should ensure that it's also deleted from the api

Identities improvements

---

src/common/indexer/elastic/elastic.indexer.service.ts
src/common/indexer/entities/provider.delegators.ts
src/common/indexer/indexer.interface.ts
src/common/indexer/indexer.service.ts
src/common/indexer/postgres/postgres.indexer.service.ts
src/endpoints/providers/entities/provider.accounts.ts
src/endpoints/providers/provider.controller.ts
src/endpoints/providers/provider.service.ts
src/test/unit/services/providers.spec.ts

- Created a new query in `elastic search service` to be able to return for a given provider address all delegators ( `address`, `stake`) / delegators count
- Created a new method `getProviderDelegators` in `ProviderService` to be able to retrieve all informations from elastic
- Created a new controller `providers/:contractAddress/accounts` that contains also `query pagination` filter
- Added new unit tests for `getProviderDelegators` method
- `providers/erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc0llllsayxegu/accounts` -> return a list of 25 delegators
- `providers/erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc0llllsayxegu/accounts?size=1` -> return a list of 1 delegator
- `providers/erd1eztdqz4cvs23w65a50d2h2g7xer5kyjy9w33pmkrrwy0usn46u6qcryt7g/accounts` -> should return [ ]
- …

add provider delegators

---

src/endpoints/tokens/entities/token.ts
src/endpoints/tokens/token.service.ts
src/graphql/schema/schema.gql

- Need to ensure fixed display value for liquidity conditions
- Simplify the codebase for easier maintenance and readability
- Improve predictability in UI behavior regarding liquidity thresholds
- Set `lowLiquidityThresholdPercent` to a fixed value of `0.5%` for tokens classified as having low liquidity.
- `tokens/SHARD-99a172` -> `lowLiquidityThresholdPercent` should be defined with value 0.5
- `tokens` -> search for `lowLiquidityThresholdPercent` and check if specific tokens contains `lowLiquidityThresholdPercent`

add lowLiquidityThresholdPercent property

---

src/test/unit/services/providers.spec.ts

- pagination scenario for provider delegators was missing
- add pagination scenario
- run script: `npm run test providers.spec.ts`

update provider delegators unit tests

---

src/common/assets/assets.service.ts

- We need to add these fields for every exchange contract.
- These fields will be used by the frontend (explorer, wallet) to display appropriate icons for the exchange contracts.
- To avoid repetitive code when setting iconSvg and iconPng for AccountAssets created a helper function to set AccountAssets fields
- Add for every exchange contract iconSvg and iconPng
- `accounts/erd1qqqqqqqqqqqqqpgqvc7gdl0p4s97guh498wgz75k8sav6sjfjlwqh679jy` -> check if assets contains also icons

add default icons for exchange contracts

---

src/crons/cache.warmer/cache.warmer.service.ts
src/endpoints/nodes/node.service.ts
src/endpoints/stake/stake.service.ts
src/test/unit/services/stake.spec.ts

- removed code that is not used
- less calls to the `/validator/auction` endpoint on gateway
- in order to limit the number of concurrent calls, apply a small random delay before performing the fetching of node auctions

Staking v4 improvements

---

src/endpoints/identities/entities/stake.info.ts
src/endpoints/identities/identities.module.ts
src/endpoints/identities/identities.service.ts
src/endpoints/nodes/node.service.ts
src/endpoints/stake/stake.service.ts
src/utils/cache.info.ts

- Implemented a fault-tolerant way of fetching validator auctions until a proper fix is deployed on the node / gateway
- Adjusted APR of identities by taking into account auction unqualified nodes
- even if the gateway returns an empty array on the validator auction endpoint, the most recently fetched value should be returned
- identities that have nodes in auction should have their APR correspondingly lowered

Validator auction query fixes

---

src/endpoints/mex/entities/mex.pair.ts
src/endpoints/mex/entities/mex.pairs..filter.ts
src/endpoints/mex/mex.controller.ts
src/endpoints/mex/mex.pair.service.ts
src/graphql/entities/xexchange/mex.pairs/mex.pairs.query.ts
src/test/unit/controllers/mex.controller.spec.ts

- include new extra pair fields: `hasFarms` `hasDualFarms` `tradesCount`
- `/mex/pairs` -> `hasFarms` `hasDualFarms` `tradesCount` -> should be defined

add extra pair fields hasFarms hasDualFarms tradesCount

---

src/endpoints/nodes/node.controller.ts

- Apply a default pagination of 10000 entries for the nodes/auctions endpoint
- The `nodes/auctions` endpoint should return all auctions if no size is specified

Default pagination for auction list

---

src/common/indexer/elastic/elastic.indexer.helper.ts
src/common/indexer/elastic/elastic.indexer.service.ts
src/common/indexer/indexer.interface.ts
src/common/indexer/indexer.service.ts
src/common/indexer/postgres/postgres.indexer.service.ts
src/crons/cache.warmer/cache.warmer.service.ts
src/crons/elastic.updater/elastic.updater.service.ts
src/endpoints/applications/application.controller.ts
src/endpoints/applications/application.module.ts
src/endpoints/applications/application.service.ts
src/endpoints/applications/entities/application.filter.ts
src/endpoints/applications/entities/application.ts
src/endpoints/endpoints.controllers.module.ts
src/endpoints/endpoints.services.module.ts
src/graphql/schema/schema.gql
src/utils/cache.info.ts

- Created a new endpoint called `applications` to be able to return all deployed smart contracts details 
- Created a new endpoint called `applications/count` to be able to return total deployed smart contracts 
- All applications are sorted by timestamp descending
- `/applications` -> should return a list of smart contracts
- `/applications?size=10` -> should return a list of 10 smart contracts
- `/applications?after=1716389130` -> should return only the smart contracts deployd after 1716389130 timestamp
- `/applications/count` -> should return total smart contracts count

add applications endpoints

---

src/endpoints/proxy/gateway.proxy.controller.ts

- new node endpoint is available in gateway.multiversx.com
- Proxy forward node/waiting-epochs-left/:bls endpoint
- `node/waiting-epochs-left/ccea9c6d5bb3833dcb90358d9585d1dddb113523d049ec93762774e620c38dabbf1868fb7b61712c3e573d788203270e0efffc97f33af38e7f46b216d04694b13c49e91f33c1bfda000634fde3557c65390065f0d5a8a211020dfa36f5c72f90` -> should return ` "epochsLeft": 3`

add node waiting epochs left proxy

---

src/endpoints/mex/entities/mex.pair.ts
src/endpoints/mex/entities/mex.pairs..filter.ts
src/endpoints/mex/mex.controller.ts
src/endpoints/mex/mex.pair.service.ts
src/graphql/entities/xexchange/mex.pairs/mex.pairs.query.ts
src/test/unit/controllers/mex.controller.spec.ts

- Since the new xexchange v3 functionality is not yet available, we revert the fetching of additional fields and will re-insert it either with a feature flag or once the new exchange api is available on all environments

Revert additional farm info PR

---

src/common/indexer/elastic/elastic.indexer.service.ts
src/endpoints/nodes/node.service.ts
src/endpoints/proxy/gateway.proxy.controller.ts

- Return from the cache if the remotely fetched validator auctions are less than 80% of what's in the cache
- The proxified endpoint `/validator/auction` returns primarily from the cache in order to alleviate access to the gateway
- if the gateway returns less than 80% of the auctions that are in the cache, still return them from the cache
- make sure that the proxified endpoint validator auction always returns from the cache and does not perform requests to the gateway

Improved caching for validator auctions

---

src/common/indexer/elastic/elastic.indexer.service.ts
src/endpoints/esdt/esdt.service.ts
src/endpoints/sc-results/scresult.service.ts

- Added possibility of loading a transaction even if a smart contract result hash is provided
- if esdt loading fails with hard error, just return it as undefined
- loading of smart contract action with try/catch so it doesn't fail the loading of the whole entry
- test loading of a sovereign chain scr as if it was a transaction and make sure it doesn't fail

Load smart contract result in transaction endpoint, do not fail if esdt loading failed

---

src/common/indexer/elastic/elastic.indexer.service.ts
src/endpoints/transactions/transaction.service.ts

- Fixed elasticsearch queries that were throwing errors when using some more special arguments
- `/transactions?withLogs=true` should not fail
- `/transactions?withOperations=true` should not fail
- `/transactions?withBlockInfo=true` should not fail
- `/accounts/erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqq8hlllls7a6h85/transactions?withOperations=true&withLogs=true&withBlockInfo=true` -> should not fail
- `/accounts/erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqq8hlllls7a6h85/transactions?withBlockInfo=true` -> should not fail
- `/accounts/erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqq8hlllls7a6h85/transfers?withBlockInfo=true` -> should not fail

Fix transactions queries

---

src/endpoints/mex/mex.controller.ts

- coinmarketcap still uses the `mex-pairs` endpoint to fetch exchange pairs, so we have to maintain this for a while
- add back the `/mex-pairs` endpoint
- `/mex-pairs` should return the same data as `mex/pairs`

Add mex-pairs endpoint

---

src/common/indexer/elastic/elastic.indexer.service.ts
src/endpoints/transactions/transaction.get.service.ts

- if in elastic `hasResults` flag is undefined, even if for transaction exist sc results, `results` field in API is not defined
- include also condition for `hasOperations` flag to retrieve the results 
- `transactions/10634f5ad92f54d944a42a65dfe10a2b1d59dfb8f72a713668e299ad24ec3f79` -> `results` field should be defined
- `transactions?hashes=10634f5ad92f54d944a42a65dfe10a2b1d59dfb8f72a713668e299ad24ec3f79&withScResults=true` -> `results` field should be defined

include transaction results if has operation

---

src/common/gateway/entities/transaction.ts
src/endpoints/tokens/token.transfer.service.ts
src/endpoints/transactions/entities/transaction.log.event.ts
src/endpoints/transactions/entities/transaction.operation.ts
src/graphql/schema/schema.gql
src/test/unit/utils/transaction.utils.spec.ts

- gateway introduced a new field called `additionalData` for transactions
- for every transactions include also the `additionalData` field which is and array of base64 strings 
- `transactions/ef9bbb5e7f49c799108c5c49c1298c873f667e0f8bb2d93828c65d74877e3276` -> check if in operations `additionalData` is defined
- `transactions?hashes=ef9bbb5e7f49c799108c5c49c1298c873f667e0f8bb2d93828c65d74877e3276&withOperations=true` -> check as above

include additional data field for operations

---

src/endpoints/identities/entities/identity.sort.criteria.ts
src/endpoints/identities/identities.controller.ts
src/endpoints/identities/identities.service.ts
src/graphql/entities/identities/identities.query.ts

- added support for identities query pagination ( from , size )
- added support for stake sorting criteria
- sort identities by validators instead of locked value
- `/identities?size=2` -> should return 2 identities
- `/identities` -> should return all available identities
- `/identities?sort=stake&order=desc` -> should sort all identities by stake ordered desc

add support for identitites stake sort query pagination

---

src/endpoints/esdt/esdt.address.service.ts

- Override old value for MetaESDT token.name with new value from token assets if exist
- `tokens/XMEX-82f2f4` -> MetaESDT should have name: "xMEX"
- `accounts/erd1x39tc3q3nn72ecjnmcz7x0qp09kp97t080x99dgyhx7zh95j0n4szskhlv/nfts?type=MetaESDT&collections=XMEX-82f2f4` -> every collection should have name: "xMex" retrieve from assets

add MetaESDT collection assets name

---

src/endpoints/mex/mex.controller.ts

- In order to still accomodate coinmarketcap requirements, we added back the `/mex-pairs` endpoint, which was deprecated earlier and removed
- the `/mex-pairs` endpoint should return the same data as `/mex/pairs`

Add mex pairs endpoint

---

src/endpoints/tokens/token.transfer.service.ts
src/endpoints/transactions/transaction.get.service.ts
src/endpoints/transactions/transaction.service.ts

- Too many requests were performed on the ES for fetching NFT names, namely for every transaction that transferred NFTs, a separate ES query was made, thus potentially overloading the ES with a lot of queries on each api call that had the `withOperations=true` parameter activated
- perform the fetching of NFT names as a batch for all transactions, not each individual one, thus optimizing the number of round-trips with ES
- `/accounts/erd1qqqqqqqqqqqqqpgq6wegs2xkypfpync8mn2sa5cmpqjlvrhwz5nqgepyg8/transactions?function=bulkBuy&withOperations=true&withLogs=true&withScResults=true&size=50` should perform only one round-trip to ES to fetch NFT names

Optimize elastic calls when fetching NFT name in transaction operations

---

src/endpoints/providers/entities/delegation.data.ts
src/endpoints/providers/entities/provider.ts
src/endpoints/providers/provider.service.ts

-`ownerBelowRequiredBalanceThreshold` field is available in delegation-api
- fetch and apply `ownerBelowRequiredBalanceThreshold` for all providers if exist
- `/providers` -> some providers should have `ownerBelowRequiredBalanceThreshold` defined
- `/providers/erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqr8llllse9cj2t` -> should have `ownerBelowRequiredBalanceThreshold` defined

fetch ownerBelowRequiredBalanceThreshold from delegation providers

---

src/interceptors/deep-history.interceptor.ts
src/utils/cache.info.ts

- Because requests with block information might be performed with the same information, pressure on the ES could be alleviated by introducing an intermediate caching layer
- use `getOrSetCache` when fetching block info based on timestamp and shard id in deep history interceptor
- Perform multiple requests with deep history information but for the same shardId and timestamp, and verify that the number of requests to ES stays linear

Deep history block info caching

---

src/endpoints/collections/collection.controller.ts
src/test/unit/controllers/collections.controller.spec.ts

- on `/collections/:collection/transfers/count` the `functions` filter is missing
- add `functions` filter to  `/collections/:collection/transfers/count` 
- `collections/COSRTGC-47b18a/transfers/count?function=auctionToken` -> should return only the auctionToken transfers
- `collections/COSRTGC-47b18a/transfers/count?function=auctionToken,ESDTNFTTransfer` -> should return auctionToken and ESDTNFTTransfer transfers

add function filter for collection transfer count

---

src/endpoints/network/network.service.ts

- Circulating supply field was still considering the Team Vesting account balance, even though all the tokens were released
- remove the team vesting account balance consideration
- `<api>/economics` should have the same values for circulating supply and total supply

remove team vesting address balance decrease from total supply

---

src/common/indexer/elastic/elastic.indexer.helper.ts
src/common/indexer/elastic/elastic.indexer.service.ts
src/common/indexer/indexer.interface.ts
src/common/indexer/indexer.service.ts
src/common/indexer/postgres/postgres.indexer.service.ts
src/endpoints/accounts/account.controller.ts
src/endpoints/accounts/account.service.ts
src/endpoints/accounts/entities/account.history.filter.ts
src/test/unit/services/accounts.spec.ts

- Added a new method to extract all the account tokens
- Added a new endpoint: `/accounts/:address/esdthistory`
- Added new specs for `getAccountEsdtHistory`
`<api>/accounts/:address/esdthistory` -> should return account esdt history list
`<api>/accounts/:address/esdthistory?token=:token` -> should return for a specific token a list of esdt history
`<api>/accounts/:address/esdthistory?identifier=[:identifier_1, :identifier_2]` -> should return for a specific list of identifiers, a list of esdt history

add account esdt history endpoint

---

config/config.devnet.yaml
config/config.mainnet.yaml
config/config.testnet.yaml
src/common/api-config/api.config.service.ts
src/main.ts

- Make public api port configurable
- in config, set `api.publicPort` to a value different than 3001 and the public api should start on that port

Configurable public api port

---

config/config.devnet.yaml
config/config.mainnet.yaml
config/config.testnet.yaml
src/common/api-config/api.config.service.ts
src/main.ts

- make websocket api configurable
- `api.websocket: false` should not start the websocket microservice and not use port 3099

Configurable websocket API

---

src/endpoints/mex/entities/mex.pair.ts
src/endpoints/mex/entities/mex.token.ts
src/endpoints/mex/mex.pair.service.ts
src/endpoints/mex/mex.token.service.ts
src/endpoints/tokens/entities/token.ts
src/endpoints/tokens/token.controller.ts
src/endpoints/tokens/token.service.ts

- expose extra information about pairs and tokens in /mex/pairs, /mex/tokens and /tokens routes
- add extra fields to MexPair:  hasFarms, hasDualFarms, tradesCount, deployedAt
- add extra fields to Token: tradesCount
- add extra fields to MexToken: tradesCount, previous24hVolume
<api>/tokens-> tokens should contain  tradesCount  fields
<api>/mex/pairs  -> should contain hasFarms, hasDualFarms, tradesCount, deployedAt fields
<api>/mex/tokens -> should contain tradesCount and previous24hVolume fields

Added additional info for /tokens , /mex/tokens and /mex/pairs routes

---

config/config.devnet-old.yaml
config/config.devnet.yaml
config/config.mainnet.yaml
config/config.testnet.yaml

- The websocket default values in the configuration files were outdated
Use the correct values for each environment. Fetched from here:
- https://devnet-api.multiversx.com/websocket/config
- https://testnet-api.multiversx.com/websocket/config
- https://api.multiversx.com/websocket/config
-

Adjusted socket url defaults in config

---

src/common/metrics/api.metrics.service.ts
src/crons/transaction.processor/batch.transaction.processor.service.ts
src/crons/transaction.processor/transaction.completed.module.ts
src/crons/transaction.processor/transaction.completed.service.ts
src/utils/metrics-events.constants.ts

- we need a method of monitoring transaction processor instances that remain stuck
- added prometheus metrics for each TransactionProcessor instance. These metrics keep the last block nonce on each shard, and if it is left behind, an alert can be triggered
- the `/metrics` endpoint on the private api should contain the `last_processed_batch_processor_nonce` and `last_processed_transaction_completed_processor_nonce` metrics for each shard when the api starts

Add metrics on transaction processor

---

config/config.devnet.yaml
config/config.mainnet.yaml
config/config.testnet.yaml
docker-compose.yml
src/common/api-config/api.config.service.ts
src/endpoints/nodes/node.service.ts
src/endpoints/tokens/token.service.ts
src/test/unit/services/nodes.spec.ts
src/test/unit/services/tokens.spec.ts

- In order to avoid hitting rate limits on ES / gateway, we can specify a set of features to activate fetching of nodes and tokens from an external API, so that we don't perform a lot of requests to the downstream resources and hitting 429 on them
- Add external API fetch for the nodes and token routes
- Add 2 features in the config file for nodesFetch and tokenFetch with the fields enabled and serviceURL
- when tokenFetch is enabled, calling getAllTokens() should make 2 GET calls through apiService at the serviceURL parameter and not call any other function
- when nodesFetch is enabled, calling getAllNodes() should make 2 GET calls through apiService at the serviceURL parameter and not call any other function

Nodes and tokens fetch from external api

---

src/graphql/schema/schema.gql
src/test/unit/services/applications.spec.ts

-  add new unit test for applications service
- run: npm run test applications.spec.ts

add applications unit tests

---

docker-compose.yml

-  rabbitmq:3.5 docker image is deprecated
- change rabbitmq docker image version from 3.5 -> 3.9

Change rabbitmq docker image version from 3.5 to 3.9

---

src/test/unit/services/nodes.spec.ts

- no testcase implemented for the case when `isNodesFetchFeatureEnabled` is false
- create new unit test for the `getAllNodes` when `isNodesFetchFeatureEnabled` is false
- adjust also the unit test for the `getAllNodes` when `isNodesFetchFeatureEnabled` is true
- `npm run test nodes.spec.ts`

nodes fetch from external api unit tests

---

src/test/unit/services/tokens.spec.ts

- no testcase implemented for the case when `isTokensFetchFeatureEnabled` is false
- create new unit test for the `getAllTokens` when `isTokensFetchFeatureEnabled` is false
- adjust also the unit test for the `getAllTokens` when `isTokensFetchFeatureEnabled` is true
- `npm run test tokens.spec.ts`

tokens fetch from external api unit tests

---

src/common/indexer/elastic/elastic.indexer.helper.ts

- In some api calls, filtering NFTs by a tag containing separators would return nfts that contain either part of the separated string, such as `nft-ticket` will return the NFTs containing the tags `nft-ticket`, `nft` and `ticket`
- apply the `AND` query operator when filtering NFTs by tags
- `/accounts/erd129e7mywmqke3ggf9ga922mw8jm49qu9zn3ryupm9602ruksxluvstvsnmq/nfts?tags=nft-ticket&withSupply=true&from=0&size=10&hasUris=true&type=NonFungibleESDT,SemiFungibleESDT&includeFlagged=true&source=elastic` should only return NFTs containing tag `nft-ticket`

Filter NFTs by full tag

---

src/crons/cache.warmer/cache.warmer.service.ts
src/endpoints/network/network.service.ts
src/endpoints/nodes/node.service.ts
src/test/unit/services/nodes.spec.ts

- In some places in the code, only the `stakingv4` flag was checked, not taking into account the activation epoch, and causing errors in cases where the staking v4 is enabled but not activated yet
- add the necessary support in the code
- before activation epoch is started, loading of nodes should not crash

Handle activation epoch where staking v4 flag is checked

---

src/endpoints/applications/application.module.ts
src/endpoints/applications/application.service.ts
src/endpoints/applications/entities/application.ts
src/test/unit/services/applications.spec.ts

- for every applications, `assets` details are missing
- add for each application ( if branded ) `assets` field
- update `applications.spec.ts` to reflect the new field
- `<api>/applications` -> some of the applications, should contain `assets`

 applications assets

---

src/endpoints/tokens/entities/token.filter.ts
src/endpoints/tokens/token.controller.ts
src/endpoints/tokens/token.service.ts

-  added token filter to be able to return all the tokens where priceSource is `dataApi` or `customUrl`
- `<api>/tokens?priceSource=customUrl`
- `<api>/tokens?priceSource=dataApi`

add support for token priceSource filter

---

src/endpoints/mex/entities/mex.pair.status.ts
src/endpoints/mex/entities/mex.pair.ts
src/endpoints/mex/mex.pair.service.ts

- `pairs` query from exchange graphql is deprecated
- remove deprecated `pairs` query and add `filteredPairs` query
- add pagination instead of `offset` and `pairsLimit`
- `<api>/mex/pairs` -> should return mex pairs ( 25 size by default )

update deprecated pairs query

---

src/common/indexer/elastic/elastic.indexer.helper.ts
src/endpoints/transactions/transaction.get.service.ts
src/endpoints/transactions/transaction.service.ts
src/endpoints/transfers/transfer.controller.ts

- add support for `isRelayed` filter in `transfers`
- add `relayer` field
- `<api>/accounts/erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u/transfers?relayer=erd17ndrqg38lqf2zjgeqvle90rsn9ejrd9upx8evkyvh8e0m5xlph5scv9l6n` -> should return all accounts transfers based on relayer address
- `<api>/transactions/107324e85cc770dc10b6134ad75d2eef3f48b76e4b2757ce962c1bef8fb3073f` -> should return `relayer` address
- `<api>/transfers?isRelayed=true` -> should return all relayed transfers
- `<api>/transfers/count?isRelayed=true` -> should return relayed count

 add support for relayer v3

---

src/common/indexer/elastic/elastic.indexer.helper.ts
src/endpoints/accounts/account.controller.ts
src/endpoints/accounts/entities/account.query.options.ts

- added support for wildcard account search
- added `search` filter on accounts endpoint
- `<api>/accounts?search=mex`

add support for wildSearchcard accounts

---

.github/workflows/build-docker-image.yaml
Dockerfile
entrypoint.sh

- we need a public docker image that contains api-service to use in other projects too.
- 
- 
- 
- 
- 
- 
- 
-

added dockerfile, workflow and entrypoint

---

src/common/indexer/elastic/elastic.indexer.helper.ts
src/endpoints/accounts/account.controller.ts
src/endpoints/accounts/entities/account.ts
src/endpoints/collections/collection.controller.ts
src/endpoints/tokens/token.controller.ts
src/endpoints/transactions/entities/transaction.filter.ts
src/endpoints/transactions/transaction.controller.ts
src/endpoints/transfers/transfer.controller.ts

- added `round` filter for the following endpoints
- `transfers` -> `transactions` -> `accounts/:address/transactions` -> `accounts/:address/transfers` -> `accounts/:address/transactions/count` -> `accounts/:address/transfers/count` -> `collections/:identifier/transfers` -> `collections/:identifier/transfers/count` -> `collections/:identifier/transactions` -> `collections/:identifier/transactions/count` -> `tokens/:identifier/transactions` -> `tokens/:identifier/transactions/count` -> `tokens/:identifier/transfers` -> `tokens/:identifier/transfers/count`
- `<api>/transactions?round=270791`
- `<api>/transactions/count?round=270791`
- `<api>/transfers?round=270791`
- `<api>/transfers/count?round=270791`
- `<api>/accounts/erd1essu6c8rv6n35s6whfklxj907e22msu786vzd9m65802qf2y9ukq8uqmtw/transact …

add round filter for transactions / transfers

---

src/common/indexer/elastic/elastic.indexer.helper.ts
src/common/indexer/elastic/elastic.indexer.service.ts
src/common/indexer/entities/events.ts
src/common/indexer/indexer.interface.ts
src/common/indexer/indexer.service.ts
src/common/indexer/postgres/postgres.indexer.service.ts
src/endpoints/endpoints.controllers.module.ts
src/endpoints/endpoints.services.module.ts
src/endpoints/events/entities/events.filter.ts
src/endpoints/events/entities/events.ts
src/endpoints/events/events.controller.ts
src/endpoints/events/events.module.ts
src/endpoints/events/events.service.ts
src/test/unit/services/events.spec.ts

-  added new `events` endpoints
-  added a list of `events`
-  added `events` count
- `<api>/events` -> should return a list of `events`
- `<api>/events/count` -> should return total `events` count
- `<api>/events/:txHash` -> should return event details

add events support

---

src/endpoints/pool/pool.controller.ts
src/endpoints/pool/pool.service.ts

- The filters used for getting the tx pool were not present for the pool count endpoint
- Added new filters
- <api>/transaction/pool?sender=...&receiver=...&senderShard=1&receiverShard=2&type=Transaction

added missing filters to tx pool count endpoint

---

.github/workflows/build-docker-image.yaml
src/common/gateway/gateway.service.ts

- `main` branch was ahead of the `development` due to a hotfix
- merge `main` into `development`
- 
- 
-

Merge main into dev nov15

---

src/endpoints/accounts/account.controller.ts
src/endpoints/nfts/entities/nft.sub.type.ts
src/endpoints/tokens/entities/token.filter.ts
src/endpoints/tokens/entities/token.ts
src/endpoints/tokens/token.service.ts
src/test/unit/services/tokens.spec.ts

- there were some inconsistencies with endpoints that return new NFTs
- added subType to missling places
- `<api>/accounts/<address>/tokens` for an address that has a dynamic MetaESDT should have `type` set to `MetaESDT` and `subType` set to `DynamicMetaESDT`

API-91: type + subType fixes

---

src/endpoints/tokens/token.service.ts

- `<api>/accounts/erd1.../tokens` would have returned empty `type` because an empty `type` field can come from gateway
- if empty `type` comes from gateway, then use the type fetched from indexer 
- `<api>/accounts/erd1tgqkv2yqdq2eytqhsut3rkcdyvmt7ngt4lq5pvhass3u79dl98tsc07cjq/tokens?size=400&includeMetaESDT=true` should have the `type` field for MetaESDT as well

Hotfix empty token type from gateway

---

.github/workflows/load-tests.yml

- the load testing workflow should only run on PRs
- remove the `push` trigger
-

Update load test workflow triggers

---

src/common/indexer/elastic/elastic.indexer.helper.ts
src/endpoints/accounts/account.controller.ts
src/endpoints/transactions/entities/transaction.filter.ts
src/endpoints/transfers/transfer.controller.ts

- by default, transactions marked as `canBeIgnored` in ES (usually receipt transactions) are not returned by the API
- add a new API flag `withRefunds` so such transactions are included as well
- check if refunds transactions are included

API-339: include transactions marked as canBeIgnored

---

src/endpoints/blocks/block.service.ts

- even though the caching unit will not store empty array anymore, bls service uses a local cache that could have still kept the empty result
- don't save empty array in local cache either
-

fix bls cache

---

src/endpoints/proxy/gateway.proxy.controller.ts

- when forwarding the `/transaction/simulate` endoint to gateway, the `checkSignature` query param was not forwarded
- pass the query param as well
```bash
curl --request POST \
--url http://localhost:3001/transaction/simulate \
--header 'Content-Type: application/json' \
--header 'User-Agent: insomnia/10.2.0' \
--data '{
"nonce":0,
"value":"0",
"receiver":"erd1qqqqqqqqqqqqqpgqccmyzj9sade2495w78h42erfrw7qmqxpd8sss6gmgn",
"sender":"erd1qyu5wthldzr8wx5c9ucg8kjagg0jfs53s8nr3zpz3hypefsdd8ssycr6th",
"senderUsername":"",
"receiverUsername":"",
"gasPrice":1000000000,
"gasLimit":5000000,
"data":"YWRkQDA3",
"chainID":"D",
"version":2,
"options":0,
"guardian":"",
"signature":"5f9f8ede6c993944095ffa9c4356ccbbafc0a2d98df2fff93ad9e000366e42af332a8c907d93fe43f22f5b4763b408152bb3fb6a454c73473c86a509f011b …
```

forward checkSignature param for tx simulation

---

src/common/gateway/entities/gateway.component.request.ts
src/common/gateway/gateway.service.ts
src/endpoints/accounts/account.controller.ts
src/endpoints/accounts/account.service.ts
src/endpoints/accounts/entities/account.query.options.ts

- Introduces a new query parameter to filter accounts by a list of addresses and includes validation to ensure the addresses array does not exceed 25 elements.
- `<api>/accounts?addresses=erd1an4xpn58j7ymd58m2jznr32t0vmas75egrdfa8mta6fzvqn9tkxq4jvghn,erd1kyle4p6chlvj0u6fyds7wj47jqwq6kh9h083kw8j76254l8u49dqepfz86`
- `<api>/accounts?addresses[... >25 ] -> should throw 400 Bad Request`

Add 'addresses' query parameter to filter accounts by a list of addresses

---

src/endpoints/nfts/nft.service.ts

- some tokens does not contain in ES ` type` field
- check if `type` field is defined
- add `DynamicSemiFungibleESDT` and `DynamicMetaESDT `

check if nft.type exist and add NftSubType filter

---

src/endpoints/keys/keys.service.ts

- The error "Cannot read properties of null (reading '0')" when trying o access encoded[0] for keys unbonding period
- Added a check for encoded data in KeysService to handle cases where no data is returned, ensuring a default response of `remainingUnBondPeriod` as 0.

check for remainingUnbonPeriod null response

---

src/common/metrics/api.metrics.service.ts
src/common/websockets/web-socket-publisher-controller.ts
src/test/unit/controllers/web.socket.publiser.controller.spec.ts
src/utils/metrics-events.constants.ts

- Need visibility into total WebSocket events at cluster level
- Missing basic counters for core WebSocket operations. (`transactionsCompleted`, `transactionsPendingResults`, `onBatchUpdated` 
- Added three simple counters:
- `websocket_transactions_completed_total`
- `websocket_transactions_pending_results_total`
- `websocket_batch_updates_total`
- `<localhost:4001>/metrics`

websockets transactions events metrics

---

src/endpoints/pool/entities/pool.filter.ts
src/endpoints/pool/entities/transaction.in.pool.dto.ts
src/endpoints/pool/pool.controller.ts
src/endpoints/pool/pool.module.ts
src/endpoints/pool/pool.service.ts
src/test/unit/services/pool.spec.ts

- pool transactions did not have the 'function' field which would make the pool analysis easier
- add function name to pool transactions if it exists
- `/transaction/pool` should contain the transactions functions

added function name for pool transactions

---

src/endpoints/transactions.batch/transactions.batch.service.ts

- invalid transactions(code 400 from gateway) do not throw errors, so they are not properly treated
- if the result of the gateway call does not contain a txHash, mark the batch transaction as invalid
- 
- 
-

Batch API: better treat invalid transactions

---

src/common/data-api/data-api.service.ts
src/common/data-api/entities/data-api.token.ts

- data API support new provider: `xoxno`
- include `xoxno` provider to fetch all the xoxno tokens prices

add support for xoxno data API provider

---

src/endpoints/accounts/account.controller.ts

- Added support for accounts count/c `search` filter
- `<api>/accounts/c?search=multiversx`
- `<api>/accounts/count?search=multiversx`

Add search query parameter to accounts count endpoints

---

src/common/indexer/elastic/elastic.indexer.helper.ts
src/common/indexer/entities/transaction.ts
src/endpoints/accounts/account.controller.ts
src/endpoints/tokens/token.controller.ts
src/endpoints/transactions/entities/transaction.filter.ts
src/endpoints/transactions/entities/transaction.ts
src/endpoints/transactions/transaction.controller.ts
src/endpoints/transfers/transfer.controller.ts
src/test/unit/services/accounts.spec.ts
src/test/unit/services/transactions.spec.ts

-  Added `isScCall` in transactions / transfers response
-  Added support for `isScCall` filter for `accounts, tokens, transactions, transfers` endpoints
- `<api>/accounts/:address/transactions?isScCall=true`
- `<api>/accounts/:address/transactions?isScCall=false`
- `<api>/accounts/:address/transfers?isScCall=true`
- `<api>/accounts/:address/transfers?isScCall=false`
- `<api>/tokens/:token/transactions?isScCall=true`
- `<api>/tokens/:token/transactions?isScCall=false`
- `<api>/tokens/:token/transfers?isScCall=true`
- `<api>/tokens/:token/transfers?isScCall=false`
- `<api>transfers?isScCall=true`
-  `<api>transfers?isScCall=false`
- `<api>transactions?isScCall=true`
- `<api>transactions?isScCall=false`

add transactions 'isScCall' filter support

---

.github/workflows/unit.tests.yml
config/config.devnet-old.yaml
config/config.devnet.yaml
config/config.e2e-mocked.mainnet.yaml
config/config.e2e.mainnet.yaml
config/config.mainnet.yaml
config/config.placeholder.yaml
config/config.testnet.yaml
src/common/api-config/api.config.service.ts
src/common/indexer/elastic/elastic.indexer.helper.ts
src/endpoints/accounts/account.controller.ts
src/endpoints/tokens/token.controller.ts
src/endpoints/transactions/entities/transaction.filter.ts
src/endpoints/transactions/transaction-action/entities/transaction.metadata.ts
src/endpoints/transactions/transaction-action/transaction.action.service.ts
src/endpoints/transactions/transaction.controller.ts
src/test/unit/services/bls.spec.ts

- by default, cross chain transfers (which are marked as `unsigned` at protocol level) did not appear on the explorer on various pages that included transactions
- if the new API query is set (`withCrossChainTransfers`), then the transactions' endpoints should also include cross chain transfers as transactions 
- `http://localhost:3001/accounts/erd1edypnrzwpun2zdcy95qzkq0tln9en39zdqpdlagfccwxzlkdgyeshulrlz/transactions?from=0&size=25&withCrossChainTransfers=true&fields=txHash,originalTxHash,receiver,receiverAssets,receiverShard,sender,senderAssets,senderShard,status,value,timestamp,round,tokenValue,tokenIdentifier,function,action,type,guardianSignature,relayer,isRelayed,relayedVersion&withUsername=true&withTxsRelayedByAddress=true` should include the cross chain transfer transaction(s)

API-417: added withCrossChainTransfers filter

---

.github/workflows/chain-simulator-e2e-tests.yml

- missing triggers for `main` -> `development` branch github actions for chain simulator

update chain simulator github action

---

.github/workflows/load-tests.yml
src/test/chain-simulator/transactions.cs-e2e.ts

-  Add e2e tests for transactions filtering by isScCall parameter
- `run chain simulator -> npm run test:cs-e2e transactions.cs-e2e.ts`

Add e2e tests for transactions filtering by isScCall parameter

---

src/endpoints/esdt/esdt.address.service.ts
src/endpoints/nfts/entities/nft.ts
src/endpoints/nfts/nft.service.ts
src/utils/token.helpers.ts

- the `hash` field of NFTs/SFTs/MetaESDTs was not reflected on the API
- return `hash` field as well
- 
- 
-

Export NFT/SFT/MetaESDT hash field

---

src/utils/cache.info.ts

- there is no need in altering the date to set in the data api token price cache key
- remove date altering
- 
- 
-

remove the cache key computation for the next day

---

config/config.devnet.yaml
config/config.testnet.yaml
src/endpoints/media/media.controller.ts
src/endpoints/nfts/nft.service.ts
src/queue.worker/nft.worker/queue/job-services/media/nft.media.service.ts
src/queue.worker/nft.worker/queue/nft.queue.controller.ts

- the default NFT thumbnail link was not dynamic
- the default NFT thumbnail link is built according to the config
- `/nfts` should return the correct link in the `media` array

Compute media url links

---

.eslintrc.js
src/common/rabbitmq/rabbitmq.nft.handler.service.ts
src/crons/cache.warmer/cache.warmer.service.ts
src/endpoints/blocks/block.service.ts
src/endpoints/caching/local.cache.controller.ts
src/endpoints/collections/collection.service.ts
src/endpoints/esdt/esdt.address.service.ts
src/endpoints/mex/mex.farm.service.ts
src/endpoints/mex/mex.pair.service.ts
src/endpoints/mex/mex.settings.service.ts
src/endpoints/mex/mex.token.service.ts
src/endpoints/mex/mex.warmer.service.ts
src/endpoints/nodes/node.service.ts
src/endpoints/tokens/token.service.ts
src/endpoints/transactions/transaction-action/recognizers/staking/transaction.action.stake.recognizer.service.ts
src/queue.worker/nft.worker/queue/job-services/media/nft.media.service.ts
src/queue.worker/nft.worker/queue/job-services/metadata/nft.metadata.service.ts

- when a function which is synchronous is awaited, it introduces an overhead for encapsulating the response into a promise
- remove async await for sync functions
- add new linter rule to prevent these cases

remove async await for sync functions

---

src/endpoints/transactions/entities/transaction.create.ts

- `relayer` and `relayerSignature` fields were missing from the class that mapped the transaction to be sent
- add missing fields
- 
- 
-

added missing relayer fields for sending txs

---

src/common/indexer/elastic/elastic.indexer.service.ts
src/endpoints/esdt/esdt.service.ts

- `isPaused` property for tokens were not handle properly
- when fetch all token properties from ES, also fetch `paused` property
- `<api>/tokens/OURO-9ecd6a` -> `isPaused` property should be true

fix token isPaused property

---

src/endpoints/dapp-config/dapp.config.controller.ts
src/endpoints/dapp-config/dapp.config.service.ts
src/endpoints/dapp-config/entities/dapp-config.ts

- include refreshRate round length info in dappConfig service
- inject gateway service to dapp config service
- `<api>/dapp/config` -> refreshRate should be defined

add support for refreshRate round length

---

src/endpoints/mex/mex.controller.ts
src/endpoints/mex/mex.token.charts.service.ts
src/test/unit/services/mex.token.charts.spec.ts
src/utils/cache.info.ts

- remove after query param for daily mex tokens prices
- `<api>/mex/tokens/prices/daily/TADA-5c032c` -> should return all daily token prices

remove query filters for mex/tokens/daily

---

src/endpoints/accounts/account.controller.ts

[#174 ](https://github.com/multiversx/mx-explorer-dapp/issues/174)
- allow the endpoint to receive the flag (the explorer already does it) and forward it to ES query
- http://localhost:3001/accounts/erd18taz9feuez07qew9zu48yxk98p9x0h7m0y8mdtmjreyfwpnzekkqvtrr7f/transfers/c?withTxsRelayedByAddress=true should return ~500 txs at the time of writing

fix transfers count with relayed txs

---

config/config.devnet-old.yaml
config/config.devnet.yaml
config/config.e2e.mainnet.yaml
config/config.mainnet.yaml
config/config.testnet.yaml
src/common/api-config/api.config.service.ts
src/queue.worker/nft.worker/queue/job-services/thumbnails/aws.service.ts

- we want to be able to upload files to other providers besides AWS S3, but we also needed to add an extra config for the bucket endpoint and set the view permissions
- added `aws.s3Endpoint` to the s3 config and the `public-read` option when uploading a file

Extend AWS S3 config

---

src/endpoints/mex/mex.token.service.ts

- The current implementation only takes volume24h from a single pair for each token, which is incorrect
- A token can be traded in multiple pairs (as base or quote token), so its total volume should be the sum of all its pair volumes
- Added a tokenVolumes map to track total volume for each token across all pairs
- Modified getAllMexTokensRaw to first calculate aggregated volumes for each token (both as base and quote)
- Updated volume assignment to use the pre-calculated aggregated volumes from tokenVolumes map
- `<api>/mex/tokens/EMR-d10ed9` -> should have correct `previous24hVolume` value

fix mex token previous24hVolume values

---

src/common/rabbitmq/entities/notifier.event.identifier.ts
src/common/rabbitmq/rabbitmq.consumer.ts
src/common/rabbitmq/rabbitmq.nft.handler.service.ts
src/endpoints/process-nfts/process.nfts.service.ts
src/test/unit/services/rabbitmq.consumer.spec.ts
src/test/unit/services/rabbitmq.nft.handler.service.spec.ts

add support for new NFT events

---

src/common/indexer/elastic/elastic.indexer.service.ts
src/common/indexer/entities/block.ts
src/common/indexer/entities/index.ts
src/common/indexer/indexer.interface.ts
src/common/indexer/indexer.service.ts
src/endpoints/transactions/entities/transactions.query.options.ts
src/endpoints/transfers/transfer.controller.ts
src/endpoints/transfers/transfer.service.ts

- Current transfer sorting uses nonce-based ordering (`nonce * 10 + 1`) which doesn't reflect actual blockchain execution order
- Elasticsearch blocks index contains `executionOrderTxsIndices` with real execution sequence
- Add `withTxsOrder` boolean parameter to `/transfers` endpoint
- Implement execution order sorting using `miniBlocksDetails` from Elasticsearch blocks
- `<api>/transfers?miniBlockHash= e61015d617eb00a33f4c83267f89d53740e209440d81e0f0e8e58b3efefb489a&withTxsOrder=true&size=10`
transactions sorted by `executionOrderTxsIndices` from blockchain
transactions with execution order `0` appears first, then `1`, then `2`, etc.
- `<api>/transfers?miniBlockHash=e61015d617eb00a33f4c83267f89d53740e209440d81e0f0e8e58b3efefb489a&size=10`
transactions sorted by `nonce * 10` + 1 for …

add execution order sorting using miniBlocksDetails from Elasticsearch

---

src/endpoints/delegation/delegation.service.ts
src/test/unit/services/delegation.spec.ts

- https://github.com/multiversx/mx-api-service/issues/1151
- mark userUndelegatedList as [] if is missing
- <api>/accounts/:address/delegation -> use an address that have some undelegated EGLD

fix userUndelegatedList field

---

src/endpoints/collections/collection.controller.ts

- collections count subType query is by default required 
- make subType query filter required false
- access API swagger docs -> collections count -> check if subType is not required

collections count subType required false fix

---

src/common/plugins/plugin.service.ts
src/endpoints/esdt/esdt.module.ts
src/endpoints/esdt/esdt.service.ts

Tokens supply format from plugin

---

src/common/indexer/entities/transaction.ts
src/endpoints/transactions/entities/transaction.ts
src/test/unit/services/accounts.spec.ts
src/test/unit/services/transactions.spec.ts

-  add `timestampMs` field
- `<api>/transactions/0d368e3081ee45f1179ed3845b504f9bead869ee665aea47259468faefac3b50`
- `<api>/transactions?hashes=0d368e3081ee45f1179ed3845b504f9bead869ee665aea47259468faefac3b50`

Api 672 add timestampMs field into transaction response

---

src/common/indexer/elastic/elastic.indexer.helper.ts
src/endpoints/events/entities/events.filter.ts
src/endpoints/events/events.controller.ts
src/test/unit/services/events.spec.ts

- added `order` filter to be able to return all the events in a specific order of execution
- update `events.spec.ts` file with more tests
- `<api>/events?order=2` -> should return all events with order field = 2

add events filtered by order

---

src/endpoints/accounts/account.service.ts

* Sequential async operations in `getAccountRaw` method causing performance bottleneck
* Three independent calls (`getAccountDeployedTxHash`, `getAccountDeployedAt`, `getAccountIsVerified` ) executed sequentially
- Replace sequential await calls with Promise.all() for parallel execution
- Call `/accounts/{address}` endpoint for smart contract addresses

optimized account raw parallel execution
